// Hierarchical DDA raymarch through a 3-level bit pyramid.
//
//   L3 chunk_mask  — bit per child tile  (one u64 covers a 64³ voxel region)
//   L2 tile_mask   — bit per child brick (one u64 covers a 16³ voxel region)
//   L1 brick.occ   — bit per voxel       (one u64 covers a  4³ voxel region)
//
// On a hit we compute per-corner ambient occlusion by reading 12 neighbour
// occupancy bits across the hit face (4 corners × 3 samples each). With the
// hierarchy, each "is this neighbour solid?" lookup is ~3 u32 fetches max
// (chunk → tile → brick) and most return false at L3/L2 immediately.

struct Camera {
    origin: vec3<f32>,
    _pad0: f32,
    forward: vec3<f32>,
    _pad1: f32,
    right: vec3<f32>,
    _pad2: f32,
    up: vec3<f32>,
    tan_half_fov: f32,
    resolution: vec2<f32>,
    time: f32,
    _pad3: f32,
    world_origin: vec3<i32>,
    _pad4: i32,
    jitter: vec2<f32>,
    taa_blend: f32,
    _pad5: f32,
};

// Toroidal storage: world voxel coords get folded into [0, WORLD_VOXELS_*)
// for the lookup. As the camera shifts the origin, only the small edge
// region's slots get reused — the rest of storage stays put.
fn pos_mod(a: i32, b: i32) -> i32 {
    let r = a % b;
    return select(r, r + b, r < 0);
}
fn world_to_slot_voxel(wv: vec3<i32>) -> vec3<i32> {
    return vec3<i32>(
        pos_mod(wv.x, WORLD_VOXELS_X),
        wv.y,
        pos_mod(wv.z, WORLD_VOXELS_Z),
    );
}

struct Brick {
    occ_lo: u32,
    occ_hi: u32,
    materials: array<u32, 16>,
};

@group(0) @binding(0) var<uniform> camera: Camera;
@group(0) @binding(1) var<storage, read> bricks: array<Brick>;
@group(0) @binding(2) var<storage, read> tile_mask: array<u32>;
@group(0) @binding(3) var<storage, read> chunk_mask: array<u32>;
@group(0) @binding(4) var<uniform> palette: array<vec4<f32>, 256>;
@group(0) @binding(5) var output_tex: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(6) var beam_depth: texture_2d<f32>;
@group(0) @binding(7) var<storage, read> tile_dirty: array<u32>;

struct PlayersBuf {
    count: u32,
    _pad0: u32,
    _pad1: u32,
    _pad2: u32,
    positions: array<vec4<f32>, 16>,
};
@group(0) @binding(8) var<storage, read> players: PlayersBuf;

// Uniform-material lookup tables. brick_uniform[bi] / tile_uniform[ti] = 0 means
// the brick/tile is non-uniform (must traverse children); any non-zero value is
// the material that fills it entirely. Packed 4 bytes per u32.
@group(0) @binding(9) var<storage, read> brick_uniform_packed: array<u32>;
@group(0) @binding(10) var<storage, read> tile_uniform_packed: array<u32>;

// L4 occupancy: one u64 (= 2 u32) per 256-voxel cell, one bit per child chunk.
// The coarsest pyramid level — one bit test skips a 256 region.
@group(0) @binding(11) var<storage, read> l4_mask: array<u32>;

fn brick_uniform_mat(bi: i32) -> u32 {
    let w = brick_uniform_packed[bi >> 2];
    let shift = u32(bi & 3) * 8u;
    return (w >> shift) & 0xFFu;
}

fn tile_uniform_mat(ti: i32) -> u32 {
    let w = tile_uniform_packed[ti >> 2];
    let shift = u32(ti & 3) * 8u;
    return (w >> shift) & 0xFFu;
}

fn ray_aabb_t(origin: vec3<f32>, inv_dir: vec3<f32>, mn: vec3<f32>, mx: vec3<f32>) -> f32 {
    let t0 = (mn - origin) * inv_dir;
    let t1 = (mx - origin) * inv_dir;
    let tmin3 = min(t0, t1);
    let tmax3 = max(t0, t1);
    let t_enter = max(max(tmin3.x, tmin3.y), max(tmin3.z, 0.0));
    let t_exit = min(min(tmax3.x, tmax3.y), tmax3.z);
    if (t_enter >= t_exit || t_exit < 0.0) { return 1e30; }
    return t_enter;
}

fn player_color_for(id: u32) -> vec3<f32> {
    let h = (id * 2654435761u) & 0xFFu;
    let r = f32((h * 73u) & 0xFFu) / 255.0;
    let g = f32((h * 41u + 91u) & 0xFFu) / 255.0;
    let b = f32((h * 113u + 53u) & 0xFFu) / 255.0;
    return vec3<f32>(0.5 + r * 0.5, 0.5 + g * 0.5, 0.5 + b * 0.5);
}

// World-dimension consts (BRICK_DIM, WORLD_BRICKS_*, WORLD_VOXELS_*,
// WORLD_TILES_*, WORLD_CHUNKS_*, WORLD_L4_*) are injected at the top of this
// module from $OUT_DIR/world_consts.wgsl, generated by build.rs from
// src/world_dims.rs. Do not redeclare them here.

fn brick_voxel_idx(lx: i32, ly: i32, lz: i32) -> i32 {
    return lx + lz * 4 + ly * 16;
}

fn world_brick_idx(bx: i32, by: i32, bz: i32) -> i32 {
    return bx + by * WORLD_BRICKS_X + bz * WORLD_BRICKS_X * WORLD_BRICKS_Y;
}

fn world_tile_idx(tx: i32, ty: i32, tz: i32) -> i32 {
    return tx + ty * WORLD_TILES_X + tz * WORLD_TILES_X * WORLD_TILES_Y;
}

fn world_chunk_idx(cx: i32, cy: i32, cz: i32) -> i32 {
    return cx + cy * WORLD_CHUNKS_X + cz * WORLD_CHUNKS_X * WORLD_CHUNKS_Y;
}

fn tile_has_child(ti: i32, child_lin: i32) -> bool {
    let base = ti * 2;
    if (child_lin < 32) {
        return (tile_mask[base] & (1u << u32(child_lin))) != 0u;
    }
    return (tile_mask[base + 1] & (1u << u32(child_lin - 32))) != 0u;
}

fn chunk_has_child(ci: i32, child_lin: i32) -> bool {
    let base = ci * 2;
    if (child_lin < 32) {
        return (chunk_mask[base] & (1u << u32(child_lin))) != 0u;
    }
    return (chunk_mask[base + 1] & (1u << u32(child_lin - 32))) != 0u;
}

fn world_l4_idx(x: i32, y: i32, z: i32) -> i32 {
    return x + y * WORLD_L4_X + z * WORLD_L4_X * WORLD_L4_Y;
}

// Is this child chunk occupied within its L4 cell?
fn l4_has_child(li: i32, child_lin: i32) -> bool {
    let base = li * 2;
    if (child_lin < 32) {
        return (l4_mask[base] & (1u << u32(child_lin))) != 0u;
    }
    return (l4_mask[base + 1] & (1u << u32(child_lin - 32))) != 0u;
}

// Is the entire 256-voxel L4 cell empty? One test skips a quarter-million voxels.
fn l4_cell_empty(li: i32) -> bool {
    let base = li * 2;
    return (l4_mask[base] | l4_mask[base + 1]) == 0u;
}

fn brick_voxel_solid(bi: i32, vi: i32) -> bool {
    let b = bricks[bi];
    if (vi < 32) {
        return (b.occ_lo & (1u << u32(vi))) != 0u;
    }
    return (b.occ_hi & (1u << u32(vi - 32))) != 0u;
}

fn brick_voxel_material(bi: i32, vi: i32) -> u32 {
    let word = vi / 4;
    let byte = vi - word * 4;
    return (bricks[bi].materials[word] >> u32(byte * 8)) & 0xFFu;
}

// LOD support: representative material of an entire brick — used at far
// distance where we terminate the DDA at brick granularity instead of
// per-voxel. Picks the topmost solid voxel so distant terrain reads as its
// surface (grass/snow/sand) rather than its hidden interior (stone/dirt).
fn brick_topmost_material(bi: i32) -> u32 {
    let b = bricks[bi];
    // Brick layout: voxel idx = x + z*4 + y*16. So y=3 layer = bits 48..63.
    // Walk from top y=3 layer down.
    let occ_hi = b.occ_hi;
    let occ_lo = b.occ_lo;
    // y=3 layer is occ_hi >> 16 (16 bits at bit 48..63).
    let y3 = (occ_hi >> 16u) & 0xFFFFu;
    if (y3 != 0u) {
        let bit = firstTrailingBit(y3);
        return brick_voxel_material(bi, i32(48u + bit));
    }
    // y=2 layer = occ_hi & 0xFFFF (bits 32..47).
    let y2 = occ_hi & 0xFFFFu;
    if (y2 != 0u) {
        let bit = firstTrailingBit(y2);
        return brick_voxel_material(bi, i32(32u + bit));
    }
    // y=1 layer = occ_lo >> 16 (bits 16..31).
    let y1 = (occ_lo >> 16u) & 0xFFFFu;
    if (y1 != 0u) {
        let bit = firstTrailingBit(y1);
        return brick_voxel_material(bi, i32(16u + bit));
    }
    // y=0 layer = occ_lo & 0xFFFF (bits 0..15).
    let y0 = occ_lo & 0xFFFFu;
    if (y0 != 0u) {
        let bit = firstTrailingBit(y0);
        return brick_voxel_material(bi, i32(bit));
    }
    return 0u;
}

fn is_voxel_solid(world_v: vec3<i32>) -> bool {
    // Bounds: voxel must be inside the loaded window.
    let rel = world_v - camera.world_origin;
    if (rel.x < 0 || rel.x >= WORLD_VOXELS_X
     || rel.y < 0 || rel.y >= WORLD_VOXELS_Y
     || rel.z < 0 || rel.z >= WORLD_VOXELS_Z) {
        return false;
    }
    // Fold into slot voxel for storage lookup.
    let v = world_to_slot_voxel(world_v);
    let bp = v >> vec3<u32>(2u);
    let tp = v >> vec3<u32>(4u);
    let cp = v >> vec3<u32>(6u);
    let ci = world_chunk_idx(cp.x, cp.y, cp.z);
    let tile_lin = (tp.x & 3) + (tp.z & 3) * 4 + (tp.y & 3) * 16;
    if (!chunk_has_child(ci, tile_lin)) { return false; }
    let ti = world_tile_idx(tp.x, tp.y, tp.z);
    let brick_lin = (bp.x & 3) + (bp.z & 3) * 4 + (bp.y & 3) * 16;
    if (!tile_has_child(ti, brick_lin)) { return false; }
    let bi = world_brick_idx(bp.x, bp.y, bp.z);
    let local = v - bp * BRICK_DIM;
    let vi = brick_voxel_idx(local.x, local.y, local.z);
    return brick_voxel_solid(bi, vi);
}

// Material at a WORLD voxel coord, or 0 (MAT_AIR) if empty / outside window.
// Used by `camera_in_water` for the underwater post-effect.
fn voxel_material_at(world_v: vec3<i32>) -> u32 {
    let rel = world_v - camera.world_origin;
    if (rel.x < 0 || rel.x >= WORLD_VOXELS_X
     || rel.y < 0 || rel.y >= WORLD_VOXELS_Y
     || rel.z < 0 || rel.z >= WORLD_VOXELS_Z) { return 0u; }
    let v = world_to_slot_voxel(world_v);
    let bp = v >> vec3<u32>(2u);
    let tp = v >> vec3<u32>(4u);
    let cp = v >> vec3<u32>(6u);
    let ci = world_chunk_idx(cp.x, cp.y, cp.z);
    let tile_lin = (tp.x & 3) + (tp.z & 3) * 4 + (tp.y & 3) * 16;
    if (!chunk_has_child(ci, tile_lin)) { return 0u; }
    let ti = world_tile_idx(tp.x, tp.y, tp.z);
    let brick_lin = (bp.x & 3) + (bp.z & 3) * 4 + (bp.y & 3) * 16;
    if (!tile_has_child(ti, brick_lin)) { return 0u; }
    let bi = world_brick_idx(bp.x, bp.y, bp.z);
    let local = v - bp * BRICK_DIM;
    let vi = brick_voxel_idx(local.x, local.y, local.z);
    if (!brick_voxel_solid(bi, vi)) { return 0u; }
    return brick_voxel_material(bi, vi);
}

fn sky(dir: vec3<f32>) -> vec3<f32> {
    return sky_color(dir);
}

/// Sky-like colour with **no stars, sun disc, or cloud emitters** — used for
/// the fog blend on distant terrain so far-away blocks don't visibly show
/// pinpoint stars through them at night.
fn fog_atmospheric(dir: vec3<f32>) -> vec3<f32> {
    let s = sun_dir();
    let day_t = sun_intensity(s);
    let up = clamp(dir.y, -0.2, 1.0);
    let zen_f = smoothstep(0.0, 0.55, up);
    let day_zenith  = vec3<f32>(0.22, 0.50, 0.95);
    let day_horizon = vec3<f32>(0.78, 0.86, 0.95);
    let day_sky = mix(day_horizon, day_zenith, zen_f);
    let night_zenith  = vec3<f32>(0.025, 0.035, 0.065);
    let night_horizon = vec3<f32>(0.055, 0.065, 0.110);
    let night_sky = mix(night_horizon, night_zenith, zen_f);
    return mix(night_sky, day_sky, day_t);
}

struct Hit {
    hit: bool,
    mat: u32,
    normal: vec3<f32>,
    voxel: vec3<i32>,
    last_axis: i32,
    t_hit: f32,
};

fn safe_inv(x: f32) -> f32 {
    if (abs(x) < 1e-8) { return 1e30; }
    return 1.0 / x;
}

// IGN (interleaved gradient noise) — high-quality low-discrepancy per-pixel
// hash. Used for shadow PCF jitter so adjacent pixels get well-distributed
// offsets without forming visible patterns.
fn ign(x: f32, y: f32, frame: f32) -> f32 {
    return fract(52.9829189 * fract(0.06711056 * (x + frame * 5.588238) + 0.00583715 * (y + frame * 4.182857)));
}

// Profiling toggles (const-folded out when false): PROFILE_FLAT skips all
// shading to isolate traversal cost; PROFILE_NO_L4 skips the L4/chunk coarse
// skips. Both off for normal rendering.
const PROFILE_FLAT: bool = false;
const PROFILE_NO_L4: bool = false;

@compute @workgroup_size(8, 8, 1)
fn cs_main(@builtin(global_invocation_id) gid: vec3<u32>) {
    let res = vec2<u32>(camera.resolution);
    if (gid.x >= res.x || gid.y >= res.y) { return; }

    // Temporal-differential gate.
    let tiles_w = (i32(camera.resolution.x) + 7) / 8;
    let tile_x = i32(gid.x) / 8;
    let tile_y = i32(gid.y) / 8;
    let tile_idx = tile_x + tile_y * tiles_w;
    let word = tile_idx >> 5;
    let bit = tile_idx & 31;
    if ((tile_dirty[word] & (1u << u32(bit))) == 0u) { return; }

    // Per-pixel + per-frame jitter, threaded through shading.
    let pix_jitter = ign(f32(gid.x), f32(gid.y), camera.time * 60.0);

    // Sub-pixel jitter for temporal anti-aliasing (zero unless accumulating).
    let uv = (vec2<f32>(f32(gid.x), f32(gid.y)) + vec2<f32>(0.5) + camera.jitter) / camera.resolution;
    let ndc = vec2<f32>(uv.x * 2.0 - 1.0, 1.0 - uv.y * 2.0);
    let aspect = camera.resolution.x / camera.resolution.y;
    let dir = normalize(
        camera.forward
        + camera.right * (ndc.x * camera.tan_half_fov * aspect)
        + camera.up    * (ndc.y * camera.tan_half_fov)
    );

    // Beam pre-pass: read the coarse first-tile-hit t for this 8×8 block
    // and start the per-pixel ray there. A 16-voxel safety margin (one
    // tile) keeps grazing-angle pixels from over-skipping.
    let beam_xy = vec2<i32>(i32(gid.x / 8u), i32(gid.y / 8u));
    let beam_t_raw = textureLoad(beam_depth, beam_xy, 0).r;
    let beam_skip = max(0.0, beam_t_raw - 16.0);
    let ray_origin = camera.origin + dir * beam_skip;

    // If the camera itself sits in a water voxel, the primary ray must
    // skip water (we're inside it) and find the first NON-water surface.
    // Otherwise the ray would hit the water voxel it's already inside and
    // render an opaque wall in our face.
    let cam_voxel_chk = vec3<i32>(floor(camera.origin));
    let cam_mat_chk = voxel_material_at(cam_voxel_chk);
    let cam_in_water = is_water_mat(cam_mat_chk);
    var hit: Hit;
    if (cam_in_water) {
        // Skip beam-skip when underwater — beam pre-pass doesn't know about
        // the camera being inside water and may have advanced past real geo.
        hit = trace_no_water(camera.origin, dir);
    } else {
        hit = trace(ray_origin, dir);
        if (hit.hit) {
            hit.t_hit = hit.t_hit + beam_skip;
        }
    }
    var col: vec3<f32>;
    if (PROFILE_FLAT) {
        col = select(sky(dir), palette[hit.mat].rgb, hit.hit);
        textureStore(output_tex, vec2<i32>(i32(gid.x), i32(gid.y)), vec4<f32>(col, 1.0));
        return;
    }
    if (hit.hit) {
        if (is_water_mat(hit.mat) && hit.normal.y > 0.5) {
            col = shade_water_top(hit, camera.origin, dir);
        } else if (hit.mat == MAT_GLASS) {
            col = shade_glass(hit, camera.origin, dir);
        } else {
            col = shade(hit, camera.origin, dir, pix_jitter);
        }
    } else {
        col = sky(dir);
    }

    // Remote-player markers: each player is a 1.6×2×1.6 box in world coords.
    // Pick the closest hit (player vs terrain) and override colour if a
    // player marker wins.
    let inv_dir_p = vec3<f32>(safe_inv(dir.x), safe_inv(dir.y), safe_inv(dir.z));
    var closest_t = select(1e30, hit.t_hit, hit.hit);
    for (var pi: u32 = 0u; pi < players.count; pi = pi + 1u) {
        let pp = players.positions[pi];
        let center = pp.xyz;
        let bmin = center - vec3<f32>(0.8, 0.5, 0.8);
        let bmax = center + vec3<f32>(0.8, 1.5, 0.8);
        let t = ray_aabb_t(camera.origin, inv_dir_p, bmin, bmax);
        if (t < closest_t) {
            closest_t = t;
            let pid = u32(pp.w);
            col = player_color_for(pid);
        }
    }

    // Volumetric clouds — slab raymarch with cone-shadowed sun samples.
    let t_terrain = select(1e6, hit.t_hit, hit.hit);
    let clouds = render_clouds(camera.origin, dir, t_terrain, vec2<f32>(f32(gid.x), f32(gid.y)));
    col = col * (1.0 - clouds.a) + clouds.rgb;

    // Volumetric god rays — accumulate sun visibility along the primary ray.
    let t_far = select(200.0, hit.t_hit, hit.hit);
    col += god_rays(camera.origin, dir, t_far, vec2<f32>(f32(gid.x), f32(gid.y)));

    // ---- underwater see-through post-effect ----
    if (cam_in_water) {
        let t_eye = select(80.0, hit.t_hit, hit.hit);
        let absorb = vec3<f32>(0.32, 0.16, 0.06);
        let trans = exp(-absorb * (t_eye * 0.18));
        let water_col = vec3<f32>(0.04, 0.18, 0.28);
        col = col * trans + water_col * (vec3<f32>(1.0) - trans);
    }

    textureStore(output_tex, vec2<i32>(i32(gid.x), i32(gid.y)), vec4<f32>(col, 1.0));
}

const MAT_GRASS:           u32 = 2u;
const MAT_WATER_L1:        u32 = 5u;
const MAT_WATER_L8:        u32 = 12u;
const MAT_LEAVES:          u32 = 14u;
const MAT_GLASS:           u32 = 18u;
const MAT_LEAVES_BIRCH:    u32 = 25u;
const MAT_LEAVES_PINE:     u32 = 26u;
const MAT_LEAVES_AUTUMN:   u32 = 27u;
const MAT_FLOWER:          u32 = 30u;
const MAT_TALL_GRASS:      u32 = 31u;

fn is_water_mat(m: u32) -> bool {
    return m >= MAT_WATER_L1 && m <= MAT_WATER_L8;
}
fn is_transparent_mat(m: u32) -> bool {
    return is_water_mat(m) || m == MAT_GLASS;
}
fn is_uniform_optimisable(m: u32) -> bool {
    // Skip foliage (sub-voxel cutout) + transparent (refraction / wave anim).
    return !is_foliage_mat(m) && !is_transparent_mat(m);
}
fn is_foliage_mat(m: u32) -> bool {
    return m == MAT_LEAVES || m == MAT_LEAVES_BIRCH
        || m == MAT_LEAVES_PINE || m == MAT_LEAVES_AUTUMN
        || m == MAT_FLOWER || m == MAT_TALL_GRASS;
}
// Ground decoration (single sub-voxel sprites). Far away these must NOT be
// drawn as solid cubes (that's the "pink flower blocks" bug) — they vanish
// instead. Leaves, by contrast, stay solid cubes far away so tree canopies
// don't disappear.
fn is_decoration_mat(m: u32) -> bool {
    return m == MAT_FLOWER || m == MAT_TALL_GRASS;
}

struct SubHit {
    hit: bool,
    t_hit: f32,
    normal: vec3<f32>,
    color_tint: vec3<f32>,  // multiplier for palette colour (1,1,1 = no change)
}

// Module-level: most recent foliage hit's colour tint. Set inside trace()
// when a foliage SubHit returns, read inside shade() to multiply the
// material colour (stem → green, blade → brightness variation).
var<private> g_foliage_tint: vec3<f32> = vec3<f32>(1.0);

// ---------- Wind: ONE consistent direction at any moment ----------
// A single wind direction blowing across the whole map, with slow rotation
// and time-varying strength. Per-voxel phase offsets the strength so not
// every blade peaks together, but the direction is shared so the whole
// scene leans the same way at the same time.
// Slower, smoother wind — direction rotates very gradually, strength
// oscillates calmly. Was way too fast before, made foliage look glitchy.
fn wind_offset(voxel_min: vec3<f32>, phase: f32, base_amp: f32) -> vec2<f32> {
    let dir_angle = camera.time * 0.04 + 0.4 * sin(camera.time * 0.12);
    let wind_x = cos(dir_angle);
    let wind_z = sin(dir_angle);
    let strength = base_amp * (0.55 + 0.45 * sin(camera.time * 0.55 + phase));
    return vec2<f32>(wind_x * strength, wind_z * strength);
}

// ---------- LEAVES: Minecraft-style full-cube with alpha-cutout texture ----------
// The leaf voxel keeps its CUBE shape. When the ray hits a face, we sample
// a 16x16 alpha-cutout "leaf texture" at that face's (u, v). If the texel
// is opaque we hit; if transparent we continue ray to test the EXIT face.
// Result: chunky cube-shaped foliage that looks like solid leaf tiles with
// holes (exactly Minecraft "fast" leaves). Wind shifts the UV sample.
fn leaf_face_alpha(voxel_min: vec3<f32>, face_axis: i32, uv: vec2<f32>, salt: f32) -> bool {
    let texel = clamp(floor(uv * 16.0), vec2<f32>(0.0), vec2<f32>(15.0));
    let h1 = hash3f(vec3<f32>(
        voxel_min.x * 16.0 + texel.x,
        voxel_min.y * 16.0 + texel.y + salt,
        voxel_min.z * 16.0 + f32(face_axis) * 2.7,
    ));
    let h2 = hash3f(vec3<f32>(
        voxel_min.x * 8.0 + floor(texel.x * 0.5),
        voxel_min.y * 8.0 + floor(texel.y * 0.5) + salt * 0.3,
        voxel_min.z * 8.0 + f32(face_axis),
    ));
    // Cluster bias — lower threshold = more see-through (about 50% opaque
    // pixels). Real Minecraft "fancy leaves" are sparser than my previous
    // 72% — the gaps make tree silhouettes feel actually leafy.
    let combined = h1 * 0.4 + h2 * 0.6;
    return combined < 0.52;
}

fn leaf_density_hit(voxel: vec3<i32>, origin: vec3<f32>, dir: vec3<f32>) -> SubHit {
    var out: SubHit;
    out.hit = false;
    out.color_tint = vec3<f32>(1.0);
    let voxel_min_base = vec3<f32>(f32(voxel.x), f32(voxel.y), f32(voxel.z));
    let vh_pre = hash3f(voxel_min_base);
    // PER-FACE sway: only the faces that aren't pressed against another
    // leaf voxel actually move. Inner leaf-to-leaf faces stay put; outer
    // faces extrude in the wind. Each of the 4 horizontal faces shifts
    // independently — the cube deforms into an asymmetric box.
    let n_xm = is_foliage_mat(voxel_material_at(voxel + vec3<i32>(-1, 0, 0)));
    let n_xp = is_foliage_mat(voxel_material_at(voxel + vec3<i32>( 1, 0, 0)));
    let n_zm = is_foliage_mat(voxel_material_at(voxel + vec3<i32>( 0, 0,-1)));
    let n_zp = is_foliage_mat(voxel_material_at(voxel + vec3<i32>( 0, 0, 1)));

    let phase_pre = voxel_min_base.x * 0.25 + voxel_min_base.z * 0.31 + vh_pre * 6.28;
    let wind_pre = wind_offset(voxel_min_base, phase_pre, 0.40);

    // Each face shifts ONLY if its corresponding neighbour is non-foliage.
    let s_xm = select(wind_pre.x, 0.0, n_xm);
    let s_xp = select(wind_pre.x, 0.0, n_xp);
    let s_zm = select(wind_pre.y, 0.0, n_zm);
    let s_zp = select(wind_pre.y, 0.0, n_zp);

    let voxel_min = vec3<f32>(
        voxel_min_base.x + s_xm,
        voxel_min_base.y,
        voxel_min_base.z + s_zm,
    );
    let voxel_max = vec3<f32>(
        voxel_min_base.x + 1.0 + s_xp,
        voxel_min_base.y + 1.0,
        voxel_min_base.z + 1.0 + s_zp,
    );
    let inv_dir = vec3<f32>(safe_inv(dir.x), safe_inv(dir.y), safe_inv(dir.z));
    let t0 = (voxel_min - origin) * inv_dir;
    let t1 = (voxel_max - origin) * inv_dir;
    let tmin = min(t0, t1);
    let tmax = max(t0, t1);
    let t_enter = max(max(tmin.x, tmin.y), max(tmin.z, 0.0));
    let t_exit = min(min(tmax.x, tmax.y), tmax.z);
    if (t_enter >= t_exit) { return out; }

    let vh = vh_pre;
    // Cube already moves — leave UV LOCKED to the (shifted) voxel so the
    // texture doesn't slide on top of the wobble. Was creating glitch
    // double-motion before.
    let uv_wind = vec2<f32>(0.0);

    // ENTRY-face alpha test.
    var entry_axis: i32 = 0;
    if (tmin.x >= tmin.y && tmin.x >= tmin.z) { entry_axis = 0; }
    else if (tmin.y >= tmin.z) { entry_axis = 1; }
    else { entry_axis = 2; }
    let p_entry = origin + dir * t_enter;
    let lp_e = p_entry - voxel_min;
    var uv_e: vec2<f32>;
    if (entry_axis == 0) { uv_e = vec2<f32>(lp_e.y, lp_e.z + uv_wind.y); }
    else if (entry_axis == 1) { uv_e = vec2<f32>(lp_e.x + uv_wind.x, lp_e.z + uv_wind.y); }
    else { uv_e = vec2<f32>(lp_e.x + uv_wind.x, lp_e.y); }
    if (leaf_face_alpha(voxel_min_base, entry_axis, fract(uv_e), 0.0)) {
        out.hit = true;
        out.t_hit = t_enter;
        var n = vec3<f32>(0.0);
        if (entry_axis == 0) { n.x = select(1.0, -1.0, dir.x > 0.0); }
        else if (entry_axis == 1) { n.y = select(1.0, -1.0, dir.y > 0.0); }
        else { n.z = select(1.0, -1.0, dir.z > 0.0); }
        out.normal = n;
        return out;
    }

    // ENTRY transparent — test EXIT face. Same pattern, different salt so
    // the back of the cube isn't a mirror of the front.
    var exit_axis: i32 = 0;
    if (tmax.x <= tmax.y && tmax.x <= tmax.z) { exit_axis = 0; }
    else if (tmax.y <= tmax.z) { exit_axis = 1; }
    else { exit_axis = 2; }
    let p_exit = origin + dir * t_exit;
    let lp_x = p_exit - voxel_min;
    var uv_x: vec2<f32>;
    if (exit_axis == 0) { uv_x = vec2<f32>(lp_x.y, lp_x.z + uv_wind.y); }
    else if (exit_axis == 1) { uv_x = vec2<f32>(lp_x.x + uv_wind.x, lp_x.z + uv_wind.y); }
    else { uv_x = vec2<f32>(lp_x.x + uv_wind.x, lp_x.y); }
    if (leaf_face_alpha(voxel_min_base, exit_axis, fract(uv_x), 5.7)) {
        out.hit = true;
        out.t_hit = t_exit;
        var n = vec3<f32>(0.0);
        if (exit_axis == 0) { n.x = select(-1.0, 1.0, dir.x > 0.0); }
        else if (exit_axis == 1) { n.y = select(-1.0, 1.0, dir.y > 0.0); }
        else { n.z = select(-1.0, 1.0, dir.z > 0.0); }
        out.normal = n;
        return out;
    }

    return out;
}

// ---------- GRASS: 3D bundle of tapered blades scattered through cell ----------
// Each grass voxel = ~14 thin vertical blades at hash-randomised xz positions
// across the FULL cell (not an X cross), with varied heights and per-blade
// tints. Each blade is a tapered AABB-bounded silhouette that tilts in the
// wind. Fills the volume of the voxel like a real tuft.
// (Flowers still use the simple X-plane silhouette below.)
// Returns (is_opaque, blade_brightness 0..1).
fn grass_blade_alpha(voxel_min: vec3<f32>, plane_id: i32, s: f32, v: f32) -> vec2<f32> {
    let plane_span = 0.92;
    let n_strips: i32 = 8;
    let strip_w = plane_span / f32(n_strips);
    for (var b: i32 = 0; b < 8; b = b + 1) {
        let strip_center_base = -plane_span * 0.5 + strip_w * (f32(b) + 0.5);
        let h1 = hash3f(vec3<f32>(voxel_min.x + f32(b) * 1.3, f32(plane_id) + voxel_min.z, voxel_min.y));
        if (h1 > 0.82) { continue; }
        let jitter = (h1 - 0.5) * strip_w * 0.7;
        let strip_center = strip_center_base + jitter;
        let h2 = hash3f(vec3<f32>(voxel_min.x + f32(b) * 0.9, f32(plane_id) * 0.5 + voxel_min.z + 11.0, voxel_min.y));
        let blade_top = 0.55 + h2 * 0.40;
        if (v > blade_top) { continue; }
        let v_norm = v / blade_top;
        let half_w = 0.045 * mix(1.0, 0.22, v_norm);
        if (abs(s - strip_center) < half_w) {
            let bright = 0.75 + v_norm * 0.35 + (h2 - 0.5) * 0.15;
            return vec2<f32>(1.0, bright);
        }
    }
    return vec2<f32>(0.0, 1.0);
}

// Returns (is_opaque, is_stem). Stem and petals need different colours.
fn flower_alpha_part(s: f32, v: f32) -> vec2<f32> {
    // STEM: thin vertical strip from bottom up to 0.55. (is_stem = 1)
    if (v < 0.55 && abs(s) < 0.025) { return vec2<f32>(1.0, 1.0); }
    // PETALS: 5 lobes around the top centre at y=0.78. Plus a small bud.
    let pc = vec2<f32>(0.0, 0.78);
    let d = vec2<f32>(s, v) - pc;
    if (dot(d, d) < 0.05 * 0.05) { return vec2<f32>(1.0, 0.0); }
    for (var i: i32 = 0; i < 5; i = i + 1) {
        let ang = f32(i) * 1.2566;
        let lobe_c = pc + vec2<f32>(cos(ang), sin(ang) * 0.6) * 0.12;
        let ld = vec2<f32>(s, v) - lobe_c;
        if (dot(ld, ld) < 0.07 * 0.07) { return vec2<f32>(1.0, 0.0); }
    }
    return vec2<f32>(0.0, 0.0);
}

fn grass_bundle_hit(voxel: vec3<i32>, origin: vec3<f32>, dir: vec3<f32>, mat: u32) -> SubHit {
    var out: SubHit;
    out.hit = false;
    out.color_tint = vec3<f32>(1.0);
    let voxel_min = vec3<f32>(f32(voxel.x), f32(voxel.y), f32(voxel.z));
    let vh = hash3f(voxel_min);
    if (vh > 0.92) { return out; }

    // Flowers stay on the X-plane silhouette (recognisable shape).
    if (mat == MAT_FLOWER) {
        return flower_planes_hit(voxel, origin, dir, voxel_min, vh);
    }

    // GRASS — packed bundle of 22 tapered, bowed blades filling the cell.
    // Each blade has independent xz position, height, lean direction, and
    // colour tint. Looks like a proper bushy tuft, not strips.
    let phase = voxel_min.x * 0.40 + voxel_min.z * 0.55 + vh * 6.28;
    let wind = wind_offset(voxel_min, phase, 0.22);
    let inv_dir = vec3<f32>(safe_inv(dir.x), safe_inv(dir.y), safe_inv(dir.z));

    let n_blades: i32 = 22;
    let blade_half_w_base = 0.030;

    var best_t: f32 = 1e30;
    var best_n = vec3<f32>(0.0, 1.0, 0.0);
    var best_bright: f32 = 1.0;

    for (var i: i32 = 0; i < 22; i = i + 1) {
        if (i >= n_blades) { break; }
        let h1 = hash3f(voxel_min + vec3<f32>(f32(i) * 1.13, 0.0, f32(i) * 0.71));
        let h2 = hash3f(voxel_min + vec3<f32>(f32(i) * 0.91, 0.0, f32(i) * 1.27));
        let h3 = hash3f(voxel_min + vec3<f32>(f32(i) * 1.31, 0.0, f32(i) * 0.83));
        let h4 = hash3f(voxel_min + vec3<f32>(f32(i) * 2.07, 0.0, f32(i) * 1.93));
        if (h1 > 0.93) { continue; }
        let bx_local = 0.05 + h1 * 0.90;
        let bz_local = 0.05 + h2 * 0.90;
        // VERY varied heights: short stubs (~0.2) to tall blades (~1.0).
        let blade_top = 0.20 + h3 * 0.80;
        // Per-blade natural lean direction (independent of wind) — gives
        // the tuft a curly random look rather than every blade ramrod.
        let lean_angle = h4 * 6.28318;
        let lean_amt = 0.05 + h4 * 0.10;
        let lean_x = cos(lean_angle) * lean_amt;
        let lean_z = sin(lean_angle) * lean_amt;

        // Combined sway = natural lean + wind shift.
        let total_x = lean_x + wind.x;
        let total_z = lean_z + wind.y;
        let sway_max_x = max(0.0, total_x);
        let sway_min_x = max(0.0, -total_x);
        let sway_max_z = max(0.0, total_z);
        let sway_min_z = max(0.0, -total_z);
        let bmin = vec3<f32>(
            voxel_min.x + bx_local - blade_half_w_base - sway_min_x,
            voxel_min.y,
            voxel_min.z + bz_local - blade_half_w_base - sway_min_z,
        );
        let bmax = vec3<f32>(
            voxel_min.x + bx_local + blade_half_w_base + sway_max_x,
            voxel_min.y + blade_top,
            voxel_min.z + bz_local + blade_half_w_base + sway_max_z,
        );
        let t0b = (bmin - origin) * inv_dir;
        let t1b = (bmax - origin) * inv_dir;
        let tmin_b = min(t0b, t1b);
        let tmax_b = max(t0b, t1b);
        let t_enter_b = max(max(tmin_b.x, tmin_b.y), max(tmin_b.z, 0.0));
        let t_exit_b = min(min(tmax_b.x, tmax_b.y), tmax_b.z);
        if (t_enter_b >= t_exit_b) { continue; }

        let n_in: i32 = 5;
        let s_step = (t_exit_b - t_enter_b) / f32(n_in);
        for (var j: i32 = 0; j < n_in; j = j + 1) {
            let t = t_enter_b + s_step * (f32(j) + 0.5);
            let p = origin + dir * t;
            let y_n = (p.y - voxel_min.y) / blade_top;
            if (y_n < 0.0 || y_n > 1.0) { continue; }
            let half_w = blade_half_w_base * mix(1.0, 0.15, y_n);
            // Bowed blade arcing in (lean + wind) direction. pow(y, 1.7)
            // curves smoothly from straight base to arched tip.
            let bow = pow(y_n, 1.7);
            let cx = voxel_min.x + bx_local + total_x * bow;
            let cz = voxel_min.z + bz_local + total_z * bow;
            let dxc = p.x - cx;
            let dzc = p.z - cz;
            if (abs(dxc) > half_w || abs(dzc) > half_w) { continue; }
            if (t < best_t) {
                best_t = t;
                best_n = normalize(vec3<f32>(dxc, 0.15, dzc) + vec3<f32>(0.0001));
                // Wider tint range: dark base 0.55 → bright tip 1.20.
                // Per-blade hue offset adds the colour variation a real
                // tuft has (some yellow-green tips, some deeper green).
                best_bright = 0.55 + y_n * 0.55 + (h4 - 0.5) * 0.30;
            }
            break;
        }
    }

    if (best_t < 1e30) {
        out.hit = true;
        out.t_hit = best_t;
        out.normal = best_n;
        out.color_tint = vec3<f32>(best_bright);
    }
    return out;
}

fn flower_planes_hit(voxel: vec3<i32>, origin: vec3<f32>, dir: vec3<f32>, voxel_min: vec3<f32>, vh: f32) -> SubHit {
    var out: SubHit;
    out.hit = false;
    out.color_tint = vec3<f32>(1.0);
    let voxel_center = voxel_min + vec3<f32>(0.5);
    let phase = voxel_min.x * 0.40 + voxel_min.z * 0.55 + vh * 6.28;
    let wind = wind_offset(voxel_min, phase, 0.22);

    var best_t: f32 = 1e30;
    var best_n = vec3<f32>(0.0, 1.0, 0.0);
    var tint = vec3<f32>(1.0);

    for (var i: i32 = 0; i < 2; i = i + 1) {
        var pn: vec3<f32>;
        var pt: vec3<f32>;
        if (i == 0) {
            pn = vec3<f32>(0.7071, 0.0, 0.7071);
            pt = vec3<f32>(0.7071, 0.0, -0.7071);
        } else {
            pn = vec3<f32>(0.7071, 0.0, -0.7071);
            pt = vec3<f32>(0.7071, 0.0, 0.7071);
        }
        let denom = dot(dir, pn);
        if (abs(denom) < 0.0001) { continue; }
        let t = dot(voxel_center - origin, pn) / denom;
        if (t < 0.0) { continue; }
        let p_hit = origin + dir * t;
        let local = p_hit - voxel_min;
        if (local.x < 0.0 || local.x > 1.0
         || local.y < 0.0 || local.y > 1.0
         || local.z < 0.0 || local.z > 1.0) { continue; }

        let s = (local.x - 0.5) * pt.x + (local.z - 0.5) * pt.z;
        let v = local.y;
        let wind_along = (wind.x * pt.x + wind.y * pt.z) * v;
        let s_w = s - wind_along;

        let fa = flower_alpha_part(s_w, v);
        if (fa.x < 0.5) { continue; }
        var local_tint = vec3<f32>(1.0);
        if (fa.y > 0.5) {
            // Stem → green.
            local_tint = vec3<f32>(0.32 / 1.10, 0.62 / 0.35, 0.20 / 0.65);
        }
        if (t < best_t) {
            best_t = t;
            best_n = select(pn, -pn, denom > 0.0);
            tint = local_tint;
        }
    }

    if (best_t < 1e30) {
        out.hit = true;
        out.t_hit = best_t;
        out.normal = best_n;
        out.color_tint = tint;
    }
    return out;
}

fn foliage_subvoxel(voxel: vec3<i32>, origin: vec3<f32>, dir: vec3<f32>, mat: u32) -> SubHit {
    var hit: SubHit;
    if (mat == MAT_TALL_GRASS || mat == MAT_FLOWER) {
        hit = grass_bundle_hit(voxel, origin, dir, mat);
    } else {
        hit = leaf_density_hit(voxel, origin, dir);
    }
    return hit;
}

// Sun rotates east→up→west→under. Start near midday so the very first frame
// isn't dim/orange; cycle slows to ~5 minutes for a less twitchy feel.
fn sun_dir() -> vec3<f32> {
    let a = camera.time * 0.025 + 1.20;
    return normalize(vec3<f32>(cos(a), sin(a), 0.30));
}

fn sun_intensity(s: vec3<f32>) -> f32 {
    // Smoothstep into night below the horizon.
    return smoothstep(-0.05, 0.10, s.y);
}

fn sun_color(s: vec3<f32>) -> vec3<f32> {
    let h = clamp(s.y, 0.0, 1.0);
    // Sunset/sunrise = warm orange. Midday = neutral. Lerp on solar elevation.
    let warm = vec3<f32>(1.40, 0.60, 0.25);
    let mid = vec3<f32>(1.10, 1.02, 0.92);
    return mix(warm, mid, smoothstep(0.05, 0.40, h)) * sun_intensity(s);
}

// IQ-style fract hash. The previous sin-based hash had visible periodic
// patterns at integer-aligned coords (that's where the "chess grid" came
// from). This one is uniform across all positions we sample.
fn hash3f(pin: vec3<f32>) -> f32 {
    var q = fract(pin * vec3<f32>(0.1031, 0.1030, 0.0973));
    q = q + dot(q, q.yzx + 33.33);
    return fract((q.x + q.y) * q.z);
}
fn vnoise3(p: vec3<f32>) -> f32 {
    let i = floor(p);
    let f = fract(p);
    let u = f * f * (3.0 - 2.0 * f);
    let n000 = hash3f(i + vec3<f32>(0.0, 0.0, 0.0));
    let n100 = hash3f(i + vec3<f32>(1.0, 0.0, 0.0));
    let n010 = hash3f(i + vec3<f32>(0.0, 1.0, 0.0));
    let n110 = hash3f(i + vec3<f32>(1.0, 1.0, 0.0));
    let n001 = hash3f(i + vec3<f32>(0.0, 0.0, 1.0));
    let n101 = hash3f(i + vec3<f32>(1.0, 0.0, 1.0));
    let n011 = hash3f(i + vec3<f32>(0.0, 1.0, 1.0));
    let n111 = hash3f(i + vec3<f32>(1.0, 1.0, 1.0));
    let a = mix(n000, n100, u.x);
    let b = mix(n010, n110, u.x);
    let c = mix(n001, n101, u.x);
    let d = mix(n011, n111, u.x);
    return mix(mix(a, b, u.y), mix(c, d, u.y), u.z);
}

// Cumulus-style cloud density. Low-frequency coverage mask gates a fbm body
// so the sky has discrete clumps with empty regions between (not haze). The
// height-falloff bell concentrates density mid-slab — flat bottoms and
// rounded tops, like real cumulus.
fn cloud_density(p: vec3<f32>, t: f32) -> f32 {
    let pa = p * 0.0055 + vec3<f32>(t * 0.06, 0.0, t * 0.035);
    // Coverage: very low-freq + secondary mid-freq — produces irregular
    // clump outlines rather than uniformly-sized blobs.
    let cov_lo = vnoise3(pa * 0.30);
    let cov_mid = vnoise3(pa * 0.85);
    let coverage = cov_lo * 0.7 + cov_mid * 0.3 - 0.50;
    if (coverage < 0.0) { return 0.0; }
    // Body: 4 octaves of fbm. Vertical noise is scaled finer so a horizontal
    // slice doesn't look like a flat layer when viewed sideways.
    let pb = vec3<f32>(pa.x, pa.y * 3.5, pa.z);
    let n1 = vnoise3(pb);
    let n2 = vnoise3(pb * 2.7);
    let n3 = vnoise3(pb * 6.3);
    let n4 = vnoise3(pb * 13.1);
    let body = n1 * 0.50 + n2 * 0.28 + n3 * 0.15 + n4 * 0.07;
    // Softer vertical envelope — flat bottoms / rounded tops without making
    // the slab so thin it reads as a flat layer when viewed obliquely.
    let h = clamp((p.y - CLOUD_BASE) / max(1.0, CLOUD_TOP - CLOUD_BASE), 0.0, 1.0);
    let bottom_fade = smoothstep(0.0, 0.15, h);
    let top_fade = 1.0 - smoothstep(0.85, 1.0, h);
    let envelope = min(bottom_fade, top_fade);
    let d = (body - 0.38) * coverage * 4.5 * envelope;
    return clamp(d, 0.0, 1.0);
}

fn sky_color(dir: vec3<f32>) -> vec3<f32> {
    let s = sun_dir();
    let day_t = sun_intensity(s);

    // Atmosphere: smoothstep elevation, hazier near the horizon (Rayleigh-ish
    // tint). Down-facing rays inherit the horizon color (camera looking
    // *under* shouldn't see deep-blue zenith showing through ground gaps).
    let up = clamp(dir.y, -0.2, 1.0);
    let zen_f = smoothstep(0.0, 0.55, up);
    let day_zenith  = vec3<f32>(0.22, 0.50, 0.95);
    let day_horizon = vec3<f32>(0.78, 0.86, 0.95);
    let day_sky = mix(day_horizon, day_zenith, zen_f);
    let night_zenith  = vec3<f32>(0.005, 0.010, 0.035);
    let night_horizon = vec3<f32>(0.030, 0.040, 0.090);
    let night_sky = mix(night_horizon, night_zenith, zen_f);

    var col = mix(night_sky, day_sky, day_t);

    // Sunset / sunrise warmth: warm wash near horizon weighted by alignment
    // to the sun's azimuth and the sun's altitude (peak around horizon).
    let dusk_w = smoothstep(-0.08, 0.18, s.y) * (1.0 - smoothstep(0.05, 0.40, s.y));
    let azi = clamp(dot(normalize(vec2<f32>(dir.x, dir.z)), normalize(vec2<f32>(s.x, s.z))), 0.0, 1.0);
    let warm_horizon = vec3<f32>(1.50, 0.55, 0.18) * dusk_w * pow(azi, 3.0) * (1.0 - zen_f);
    col = col + warm_horizon;

    // General halo / forward-scatter near the sun.
    let sun_align = max(0.0, dot(dir, s));
    let halo = vec3<f32>(1.0, 0.78, 0.52) * pow(sun_align, 6.0) * day_t * 0.45;
    col = col + halo;

    // Sun disc.
    if (sun_align > 0.9985) {
        col = mix(col, vec3<f32>(2.4, 2.0, 1.5), 0.9);
    }

    // Stars when sun is below the horizon. Simple high-frequency noise
    // threshold; faint and scattered.
    if (day_t < 0.30) {
        let stn = vnoise3(dir * 95.0);
        if (stn > 0.93) {
            let amp = (stn - 0.93) * 14.0 * (1.0 - day_t);
            col = col + vec3<f32>(0.9, 0.92, 1.0) * amp;
        }
    }

    // Clouds disabled for now.
    return col;
}

// ---- world-projected procedural textures ----------------------------------
// Tri-planar UV: pick the plane perpendicular to the face's dominant axis,
// then read world-space coords on that plane. Same material across multiple
// voxels reads continuous texture; voxel boundaries vanish.
fn tex_uv(p: vec3<f32>, n: vec3<f32>) -> vec2<f32> {
    let an = abs(n);
    if (an.y > an.x && an.y > an.z) { return p.xz; }    // top/bottom face
    if (an.x > an.z)                { return p.zy; }    // ±X face
    return p.xy;                                        // ±Z face
}

// Classic running-bond brick: rows offset by half a brick. Returns a
// brightness multiplier (1.0 = brick face, 0.55 = mortar gap).
fn brick_pattern(uv: vec2<f32>) -> f32 {
    let bw = 1.6;   // brick width  (voxels)
    let bh = 0.8;   // brick height (voxels)
    let mw = 0.10;  // mortar thickness
    let row = floor(uv.y / bh);
    var offset_row: f32 = 0.0;
    if ((i32(row) & 1) == 1) { offset_row = bw * 0.5; }
    let lx = fract((uv.x + offset_row) / bw) * bw;
    let ly = fract(uv.y / bh) * bh;
    let in_v = (lx < mw) || (lx > bw - mw);
    let in_h = (ly < mw) || (ly > bh - mw);
    if (in_v || in_h) { return 0.55; }
    return 1.0;
}

// Wood grain — rings concentric around the trunk's vertical axis (Y) on
// horizontal faces, longitudinal stripes on side faces.
fn wood_pattern(p: vec3<f32>, n: vec3<f32>) -> f32 {
    let an = abs(n);
    if (an.y > 0.5) {
        // End-grain: rings.
        let r = sqrt(p.x * p.x + p.z * p.z);
        let rings = 0.5 + 0.5 * sin(r * 4.5 + vnoise3(vec3<f32>(p.x * 0.4, 0.0, p.z * 0.4)) * 2.0);
        return 0.75 + rings * 0.25;
    }
    // Side: longitudinal grain.
    let grain = 0.5 + 0.5 * sin(p.y * 6.0 + vnoise3(p * 0.3) * 3.0);
    let fine = vnoise3(vec3<f32>(p.x * 8.0, p.y * 1.2, p.z * 8.0));
    return 0.78 + grain * 0.18 + fine * 0.08;
}

// All material textures return a *luminance multiplier* (~0.7–1.2 range)
// applied to the material's base palette colour. That way each material
// keeps its identifying colour but gains world-projected detail — voxels of
// the same material show continuous texture across faces, single voxels
// removed just gap a slice of the pattern. We deliberately avoid recolouring
// (e.g. the previous brick pattern turned stone terra-cotta — that was a
// surprise; user wanted "texture", not a colour swap).
fn material_texture(p: vec3<f32>, n: vec3<f32>, mat: u32) -> vec3<f32> {
    let uv = tex_uv(p, n);
    // Stone — cracked mortar look, but the gray base colour is preserved.
    if (mat == 4u) {
        let cracks = brick_pattern(uv);          // 0.55 in mortar, 1.0 in face
        let grain = vnoise3(vec3<f32>(uv * 2.0, 0.0)) * 0.20 + 0.90;
        return vec3<f32>(grain * mix(0.7, 1.0, cracks));
    }
    // Wood variants — directional grain.
    if (mat == 13u || mat == 23u || mat == 24u) {
        return vec3<f32>(wood_pattern(p, n));
    }
    // Grass — small clumpy variation.
    if (mat == 2u) {
        let nn = vnoise3(vec3<f32>(uv * 2.2, 0.0));
        return vec3<f32>(0.85 + nn * 0.30);
    }
    // Dirt.
    if (mat == 3u) {
        let nn = vnoise3(vec3<f32>(uv * 1.6, 0.0));
        return vec3<f32>(0.78 + nn * 0.30);
    }
    // Sand — fine granular.
    if (mat == 1u) {
        let nn = vnoise3(vec3<f32>(uv * 7.0, 0.0));
        return vec3<f32>(0.92 + nn * 0.16);
    }
    // Snow — sparkles.
    if (mat == 15u) {
        let nn = vnoise3(vec3<f32>(uv * 16.0, 0.0));
        let sparkle = max(0.0, (nn - 0.85) * 6.0);
        return vec3<f32>(0.97 + sparkle);
    }
    // Leaves variants.
    if (mat == 14u || mat == 25u || mat == 26u || mat == 27u) {
        let nn = vnoise3(vec3<f32>(uv * 4.0, 0.0));
        return vec3<f32>(0.80 + nn * 0.40);
    }
    // Ice.
    if (mat == 17u) {
        let nn = vnoise3(vec3<f32>(uv * 1.2, 0.0));
        return vec3<f32>(0.88 + nn * 0.20);
    }
    // Coal.
    if (mat == 19u) {
        let nn = vnoise3(vec3<f32>(uv * 3.5, 0.0));
        return vec3<f32>(0.70 + nn * 0.50);
    }
    // Lava — keep the warm palette colour; modulate luminance with crack noise.
    if (mat == 16u) {
        let nn = vnoise3(vec3<f32>(uv * 1.4, p.y * 0.05));
        let crack = smoothstep(0.45, 0.55, nn);
        return vec3<f32>(mix(1.15, 0.55, crack));
    }
    return vec3<f32>(1.0);
}

fn ambient_color() -> vec3<f32> {
    let s = sun_dir();
    let day_t = sun_intensity(s);
    let day = vec3<f32>(0.30, 0.42, 0.58);
    let night = vec3<f32>(0.04, 0.05, 0.10);
    return mix(night, day, day_t);
}

// Real Gerstner-style wave normals. Four waves with varied directions,
// wavelengths, amplitudes and steepness so the surface looks like genuine
// ocean — not a tiled sinusoid. We return the perturbed normal computed
// from the closed-form partial derivatives of the wave height field.
//
//   h_i(P,t) = A_i · cos(D_i · P · k_i - ω_i · t + φ_i)
//   ∂h_i/∂x = -A_i · k_i · D_i.x · sin(...)
//   ∂h_i/∂z = -A_i · k_i · D_i.z · sin(...)
//
// Then normal = normalize(vec3(-Σ∂h/∂x, 1, -Σ∂h/∂z)).
fn water_normal(p: vec3<f32>, t: f32) -> vec3<f32> {
    // (dir.x, dir.z, k=2π/λ, A, ω-multiplier, phase)
    let w1: array<f32, 6> = array<f32, 6>(  1.00,  0.20, 0.60, 0.16, 1.10, 0.0);
    let w2: array<f32, 6> = array<f32, 6>( -0.55,  0.85, 0.95, 0.10, 1.40, 1.7);
    let w3: array<f32, 6> = array<f32, 6>(  0.30, -0.95, 1.50, 0.05, 1.90, 3.1);
    let w4: array<f32, 6> = array<f32, 6>( -0.90, -0.30, 2.40, 0.03, 2.60, 5.2);

    var dx = 0.0;
    var dz = 0.0;
    for (var i: i32 = 0; i < 4; i = i + 1) {
        var w: array<f32, 6>;
        if      (i == 0) { w = w1; }
        else if (i == 1) { w = w2; }
        else if (i == 2) { w = w3; }
        else             { w = w4; }
        let dirx = w[0];
        let dirz = w[1];
        let k = w[2];
        let A = w[3];
        let om = w[4];
        let ph = w[5];
        let phase = (p.x * dirx + p.z * dirz) * k - t * om + ph;
        let s = sin(phase);
        dx = dx - A * k * dirx * s;
        dz = dz - A * k * dirz * s;
    }
    return normalize(vec3<f32>(-dx, 1.0, -dz));
}

// Vertical height field — used for foam thresholding and caustics.
fn water_height(p: vec3<f32>, t: f32) -> f32 {
    let w1: array<f32, 6> = array<f32, 6>(  1.00,  0.20, 0.60, 0.16, 1.10, 0.0);
    let w2: array<f32, 6> = array<f32, 6>( -0.55,  0.85, 0.95, 0.10, 1.40, 1.7);
    let w3: array<f32, 6> = array<f32, 6>(  0.30, -0.95, 1.50, 0.05, 1.90, 3.1);
    let w4: array<f32, 6> = array<f32, 6>( -0.90, -0.30, 2.40, 0.03, 2.60, 5.2);
    var h = 0.0;
    for (var i: i32 = 0; i < 4; i = i + 1) {
        var w: array<f32, 6>;
        if      (i == 0) { w = w1; }
        else if (i == 1) { w = w2; }
        else if (i == 2) { w = w3; }
        else             { w = w4; }
        let phase = (p.x * w[0] + p.z * w[1]) * w[2] - t * w[4] + w[5];
        h = h + w[3] * cos(phase);
    }
    return h;
}

// Variant of `trace` that treats every water voxel as empty. Used to find
// what lies *beneath* a water surface for refraction-style transparency.
fn trace_no_water(origin: vec3<f32>, dir: vec3<f32>) -> Hit {
    var out: Hit;
    out.hit = false;
    out.mat = 0u;
    out.normal = vec3<f32>(0.0);
    out.voxel = vec3<i32>(0);
    out.last_axis = -1;
    out.t_hit = 0.0;

    // Origin-rebased (see trace() for the rationale).
    let ro = camera.world_origin;
    let org = origin - vec3<f32>(ro);
    let dims = vec3<f32>(f32(WORLD_VOXELS_X), f32(WORLD_VOXELS_Y), f32(WORLD_VOXELS_Z));
    let inv_dir = vec3<f32>(safe_inv(dir.x), safe_inv(dir.y), safe_inv(dir.z));
    let t0 = (vec3<f32>(0.0) - org) * inv_dir;
    let t1 = (dims - org) * inv_dir;
    let tmin3 = min(t0, t1);
    let tmax3 = max(t0, t1);
    let t_enter = max(max(tmin3.x, tmin3.y), max(tmin3.z, 0.0));
    let t_exit = min(min(tmax3.x, tmax3.y), tmax3.z);
    if (t_enter >= t_exit || t_exit < 0.0) { return out; }

    let bias = 1e-3;
    var p = org + dir * (t_enter + bias);
    p = clamp(p, vec3<f32>(0.01), dims - vec3<f32>(0.01));
    let step = vec3<i32>(sign(dir));
    let t_delta = abs(inv_dir);

    var voxel = vec3<i32>(floor(p)) + ro;
    let vl0 = voxel - ro;
    var t_max: vec3<f32>;
    if (step.x > 0) { t_max.x = (f32(vl0.x + 1) - org.x) * inv_dir.x; } else { t_max.x = (f32(vl0.x) - org.x) * inv_dir.x; }
    if (step.y > 0) { t_max.y = (f32(vl0.y + 1) - org.y) * inv_dir.y; } else { t_max.y = (f32(vl0.y) - org.y) * inv_dir.y; }
    if (step.z > 0) { t_max.z = (f32(vl0.z + 1) - org.z) * inv_dir.z; } else { t_max.z = (f32(vl0.z) - org.z) * inv_dir.z; }

    var last_axis: i32 = -1;
    for (var s: i32 = 0; s < 1024; s = s + 1) {
        let rel = voxel - camera.world_origin;
        if (rel.x < 0 || rel.x >= WORLD_VOXELS_X
         || rel.y < 0 || rel.y >= WORLD_VOXELS_Y
         || rel.z < 0 || rel.z >= WORLD_VOXELS_Z) { return out; }

        let slot_v = world_to_slot_voxel(voxel);
        let bp = slot_v >> vec3<u32>(2u);
        let tp = slot_v >> vec3<u32>(4u);
        let cp = slot_v >> vec3<u32>(6u);
        // Nested hierarchy: skip the coarsest empty cell (L4 → chunk → tile → brick).
        let l4p = slot_v >> vec3<u32>(8u);
        let l4i = world_l4_idx(l4p.x, l4p.y, l4p.z);
        if (l4_cell_empty(l4i)) {
            skip_to_cell(256, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
            continue;
        }
        let chunk_lin = (cp.x & 3) + (cp.z & 3) * 4 + (cp.y & 3) * 16;
        if (!l4_has_child(l4i, chunk_lin)) {
            skip_to_cell(64, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
            continue;
        }
        let ci = world_chunk_idx(cp.x, cp.y, cp.z);
        let tile_lin = (tp.x & 3) + (tp.z & 3) * 4 + (tp.y & 3) * 16;
        if (!chunk_has_child(ci, tile_lin)) {
            skip_to_cell(16, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
            continue;
        }
        let ti = world_tile_idx(tp.x, tp.y, tp.z);
        let brick_lin = (bp.x & 3) + (bp.z & 3) * 4 + (bp.y & 3) * 16;
        if (!tile_has_child(ti, brick_lin)) {
            skip_to_cell(4, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
            continue;
        }
        let bi = world_brick_idx(bp.x, bp.y, bp.z);
        let local = slot_v - bp * BRICK_DIM;
        let vi = brick_voxel_idx(local.x, local.y, local.z);
        if (brick_voxel_solid(bi, vi)) {
            let m = brick_voxel_material(bi, vi);
            if (!is_transparent_mat(m)) {
                var n = vec3<f32>(0.0);
                var t_hit: f32;
                if (last_axis == 0) { n.x = -f32(step.x); t_hit = t_max.x - t_delta.x; }
                else if (last_axis == 1) { n.y = -f32(step.y); t_hit = t_max.y - t_delta.y; }
                else if (last_axis == 2) { n.z = -f32(step.z); t_hit = t_max.z - t_delta.z; }
                else { t_hit = t_enter; if (tmin3.x >= tmin3.y && tmin3.x >= tmin3.z) { n.x = -f32(step.x); } else if (tmin3.y >= tmin3.z) { n.y = -f32(step.y); } else { n.z = -f32(step.z); } }
                out.hit = true;
                out.mat = m;
                out.normal = n;
                out.voxel = voxel;
                out.last_axis = last_axis_after_entry(last_axis, tmin3);
                out.t_hit = t_hit;
                return out;
            }
            // Water cell — fall through to the regular step so we keep going.
        }

        if (t_max.x < t_max.y && t_max.x < t_max.z) {
            voxel.x = voxel.x + step.x;
            t_max.x = t_max.x + t_delta.x;
            last_axis = 0;
        } else if (t_max.y < t_max.z) {
            voxel.y = voxel.y + step.y;
            t_max.y = t_max.y + t_delta.y;
            last_axis = 1;
        } else {
            voxel.z = voxel.z + step.z;
            t_max.z = t_max.z + t_delta.z;
            last_axis = 2;
        }
    }
    return out;
}

fn shade_water_top(hit: Hit, origin: vec3<f32>, dir: vec3<f32>) -> vec3<f32> {
    let p_hit = origin + dir * hit.t_hit;
    let n = water_normal(p_hit, camera.time);
    let s = sun_dir();
    let sc = sun_color(s);
    // Per-pixel jitter substitute for shading-of-reflections — derive from
    // hit position since we're not in cs_main scope.
    let jit = fract(p_hit.x * 17.0 + p_hit.z * 23.0 + camera.time * 13.0);

    // ---- reflection: primary ray reflected off the perturbed normal ----
    let refl_dir = reflect(dir, n);
    let refl_origin = p_hit + n * 0.01;
    let refl_hit = trace(refl_origin, refl_dir);
    var refl_col: vec3<f32>;
    if (refl_hit.hit) {
        refl_col = shade(refl_hit, refl_origin, refl_dir, jit);
    } else {
        refl_col = sky(refl_dir);
    }

    // ---- refraction: primary ray bent into the water, trace through it ----
    // Snell's law via WGSL `refract`. eta = n_air / n_water ≈ 1/1.33.
    let eta = 1.0 / 1.33;
    var refr_dir = refract(dir, n, eta);
    // Total internal reflection would return zero; fall back to dir.
    if (length(refr_dir) < 0.01) { refr_dir = dir; }
    let refr_origin = p_hit + dir * 0.001; // step inside the water column
    let under = trace_no_water(refr_origin, refr_dir);
    var under_col: vec3<f32>;
    if (under.hit) {
        under_col = shade(under, refr_origin, refr_dir, jit);
    } else {
        under_col = sky(refr_dir) * 0.6;
    }
    // Beer-Lambert absorption — red and green are eaten faster than blue.
    let depth = max(0.0, under.t_hit);
    let absorb = vec3<f32>(0.55, 0.25, 0.10); // per-unit-distance attenuation
    let transmittance = exp(-absorb * depth);
    // Water tint modulated by ambient + a bit of sun colour, so the water
    // body actually goes dark at night instead of staying daytime-blue.
    let tint_base = vec3<f32>(0.10, 0.32, 0.42);
    let water_tint = tint_base * (ambient_color() * 1.6 + sc * 0.20);
    let refr_col = under_col * transmittance + water_tint * (1.0 - transmittance.x);

    // ---- Fresnel mix of reflection and refraction ----
    let cos_theta = clamp(dot(-dir, n), 0.0, 1.0);
    let f0 = 0.02;
    let fresnel = f0 + (1.0 - f0) * pow(1.0 - cos_theta, 5.0);

    // ---- specular sun glint (sharper for stronger highlight) ----
    let h = normalize(s - dir);
    let spec = pow(max(0.0, dot(n, h)), 256.0);
    var shadow = 0.0;
    if (sun_intensity(s) > 0.0 && dot(n, s) > 0.0) {
        shadow = select(1.0, 0.0, trace_any(refl_origin, s));
    }

    // ---- shoreline foam: triggered by shallow water (under.t_hit small) ----
    // The closer the underwater hit, the brighter the white foam contribution.
    // Wave-crest noise modulates so foam looks like spray, not a flat ring.
    var foam = 0.0;
    if (under.hit && under.t_hit < 2.5) {
        let shore = 1.0 - clamp(under.t_hit / 2.5, 0.0, 1.0);
        let crest = clamp(water_height(p_hit, camera.time) * 4.0 + 0.5, 0.0, 1.0);
        foam = shore * crest * 0.85;
    }

    // ---- caustics: brighten the underwater colour where the surface wave
    // gradient focuses light. Approximation: |∇h| → dispersion factor, where
    // small gradient = focused beams. Only applies to the refracted column.
    let caustic = 0.6 + 0.8 * pow(max(0.0, n.y), 18.0);

    var col = mix(refr_col * caustic, refl_col, fresnel) + sc * spec * shadow * 1.4;
    // Foam colour also dims at night — at dawn/dusk it picks up the warm
    // sun tint, at noon it's bright white, at night it fades into ambient.
    let foam_col = ambient_color() * 1.5 + sc * 0.50;
    col = mix(col, foam_col, foam);
    let fog_t = clamp(hit.t_hit / 280.0, 0.0, 0.85);
    return mix(col, fog_atmospheric(dir), fog_t);
}

fn shade(hit: Hit, origin: vec3<f32>, dir: vec3<f32>, pix_jit: f32) -> vec3<f32> {
    let p_hit = origin + dir * hit.t_hit;
    let tex = material_texture(p_hit, hit.normal, hit.mat);
    var base = palette[hit.mat].rgb * tex;
    // Foliage sub-hit may override colour (flower stem → green, blade
    // shading variations etc.)
    if (hit.last_axis < 0 && is_foliage_mat(hit.mat)) {
        base = base * g_foliage_tint;
    }
    // Skip the cube-face AO for sub-voxel sphere hits (foliage). The curved
    // sphere normal already gives rim/falloff that reads as 3D.
    // AO (12 hierarchical neighbour lookups) only near the camera — its
    // contact-shadow detail is invisible far away, so skip it past AO_DIST and
    // for sub-voxel foliage hits.
    let skip_ao = hit.last_axis < 0 || hit.t_hit > AO_DIST;
    let ao = select(compute_ao(hit, origin, dir), 1.0, skip_ao);

    // ---- swaying foliage ----
    // Leaves and grass-tops perturb their shading normal with a wind field
    // so they look animated even though the underlying voxel is rigid.
    var n = hit.normal;
    if (is_foliage_mat(hit.mat)) {
        let t = camera.time;
        let sway = sin(p_hit.x * 0.40 + t * 1.8) * cos(p_hit.z * 0.40 + t * 1.2)
                 + 0.4 * sin((p_hit.x + p_hit.z) * 0.25 + t * 2.4);
        // Flowers + tall grass sway harder (thin & light) than tree leaves.
        let amp = select(0.30, 0.55, hit.mat == MAT_FLOWER || hit.mat == MAT_TALL_GRASS);
        n.x += sway * amp;
        n.z += sway * amp * 0.7;
        n = normalize(n);
        base *= 1.0 + sway * 0.12;
    } else if (hit.mat == MAT_GRASS && hit.normal.y > 0.5) {
        let t = camera.time;
        let sway = sin(p_hit.x * 0.55 + t * 2.1) * cos(p_hit.z * 0.55 + t * 1.7);
        n.x += sway * 0.20;
        n.z += sway * 0.18;
        n = normalize(n);
        base *= 1.0 + sway * 0.07;
    }

    let s = sun_dir();
    let s_int = sun_intensity(s);
    let p_off = p_hit + n * 0.001;
    let n_dot_l = max(0.0, dot(n, s));
    var shadow_term = 0.0;
    if (n_dot_l > 0.0 && s_int > 0.0) {
        // ONE jittered shadow ray (was 2). The per-pixel + per-frame jitter
        // (pix_jit rotates each frame) plus the TAA history accumulation average
        // the single sample into a soft penumbra over time — at half the cost.
        // Shadows are the single most expensive per-pixel term, so this is the
        // biggest shading win.
        let golden = 2.39996323; // 137.5° in radians
        let cone = 0.07;
        let theta = pix_jit * golden;
        let radius = cone * sqrt(pix_jit * 0.5);
        // Offset in the plane perpendicular to the sun so the penumbra is
        // uniform regardless of sun azimuth.
        var tangent = normalize(cross(s, vec3<f32>(0.0, 1.0, 0.0)));
        if (length(cross(s, vec3<f32>(0.0, 1.0, 0.0))) < 0.01) {
            tangent = vec3<f32>(1.0, 0.0, 0.0);
        }
        let bitangent = cross(s, tangent);
        let off = (tangent * cos(theta) + bitangent * sin(theta)) * radius;
        let ss = normalize(s + off);
        shadow_term = select(0.0, 1.0, !trace_any(p_off, ss));
    }

    let direct = sun_color(s) * (n_dot_l * shadow_term);
    let ambient = ambient_color() * ao;
    let lit = base * (direct + ambient);

    let fog_t = clamp(hit.t_hit / 280.0, 0.0, 0.85);
    return mix(lit, fog_atmospheric(dir), fog_t);
}

// Glass — Fresnel reflection + per-channel refraction (chromatic dispersion),
// Total Internal Reflection handling, and a specular sun glint. The cyan
// tint compounds with travel distance for chunky glass blocks.
fn shade_glass(hit: Hit, origin: vec3<f32>, dir: vec3<f32>) -> vec3<f32> {
    let p_hit = origin + dir * hit.t_hit;
    let n = hit.normal;
    let s = sun_dir();
    let sc = sun_color(s);
    let jit = fract(p_hit.x * 17.0 + p_hit.z * 23.0 + camera.time * 13.0);

    let refl_dir = reflect(dir, n);
    let refl_origin = p_hit + n * 0.01;
    let refl_hit = trace(refl_origin, refl_dir);
    var refl_col: vec3<f32>;
    if (refl_hit.hit) {
        refl_col = shade(refl_hit, refl_origin, refl_dir, jit);
    } else {
        refl_col = sky(refl_dir);
    }

    // Chromatic dispersion: shift the refractive index slightly per channel.
    // R refracts less than B, so a flat glass face shows a faint rainbow at
    // grazing angles. Three trace calls is more expensive — only do it when
    // we'd actually see the dispersion (cos_theta < 0.9, i.e. near edges).
    let cos_theta_pre = clamp(dot(-dir, n), 0.0, 1.0);
    let eta_r = 1.0 / 1.48;
    let eta_g = 1.0 / 1.50;
    let eta_b = 1.0 / 1.52;

    var refr_dir_r = refract(dir, n, eta_r);
    var refr_dir_g = refract(dir, n, eta_g);
    var refr_dir_b = refract(dir, n, eta_b);

    // Total internal reflection on any channel → fall back to the reflection.
    let tir = length(refr_dir_g) < 0.01;
    if (tir) {
        let fog_t = clamp(hit.t_hit / 280.0, 0.0, 0.85);
        return mix(refl_col, fog_atmospheric(dir), fog_t);
    }
    if (length(refr_dir_r) < 0.01) { refr_dir_r = refr_dir_g; }
    if (length(refr_dir_b) < 0.01) { refr_dir_b = refr_dir_g; }

    let refr_origin = p_hit + dir * 0.001;
    var glass_col: vec3<f32>;
    if (cos_theta_pre > 0.92) {
        // Near head-on: dispersion invisible — single trace, save 2/3 cost.
        let under = trace_no_water(refr_origin, refr_dir_g);
        var under_col: vec3<f32>;
        if (under.hit) { under_col = shade(under, refr_origin, refr_dir_g, jit); }
        else { under_col = sky(refr_dir_g); }
        let depth = max(0.0, under.t_hit);
        let tint = vec3<f32>(0.05, 0.02, 0.02) * depth;
        glass_col = under_col * exp(-tint);
    } else {
        let ur = trace_no_water(refr_origin, refr_dir_r);
        let ug = trace_no_water(refr_origin, refr_dir_g);
        let ub = trace_no_water(refr_origin, refr_dir_b);
        var cr = select(sky(refr_dir_r).r, shade(ur, refr_origin, refr_dir_r, jit).r, ur.hit);
        var cg = select(sky(refr_dir_g).g, shade(ug, refr_origin, refr_dir_g, jit).g, ug.hit);
        var cb = select(sky(refr_dir_b).b, shade(ub, refr_origin, refr_dir_b, jit).b, ub.hit);
        let depth_g = max(0.0, ug.t_hit);
        let tint = vec3<f32>(0.05, 0.02, 0.02) * depth_g;
        glass_col = vec3<f32>(cr, cg, cb) * exp(-tint);
    }

    // Specular sun glint on the glass face — bright pinpoint highlight when
    // the surface aligns the sun reflection toward the camera.
    let h_vec = normalize(s - dir);
    let spec = pow(max(0.0, dot(n, h_vec)), 200.0);
    var shadow = 0.0;
    if (sun_intensity(s) > 0.0 && dot(n, s) > 0.0) {
        shadow = select(1.0, 0.0, trace_any(refl_origin, s));
    }

    let cos_theta = clamp(dot(-dir, n), 0.0, 1.0);
    let f0 = 0.04;
    let fresnel = f0 + (1.0 - f0) * pow(1.0 - cos_theta, 5.0);

    let fog_t = clamp(hit.t_hit / 280.0, 0.0, 0.85);
    let combined = mix(glass_col, refl_col, fresnel) + sc * spec * shadow * 1.2;
    return mix(combined, fog_atmospheric(dir), fog_t);
}

// Volumetric clouds: raymarch a horizontal slab. Altitude lowered (was
// 200-250) so clouds sit inside the world Y = 192 — view rays past
// mountains can actually reach the cloud band instead of stopping at the
// world ceiling.
const CLOUD_BASE: f32 = 145.0;
const CLOUD_TOP:  f32 = 180.0;

fn render_clouds(origin: vec3<f32>, dir: vec3<f32>, t_terrain: f32, pix: vec2<f32>) -> vec4<f32> {
    // Slab intersection. A horizontal ray (|dir.y| ~ 0) gets nothing because
    // the slab is thin compared to the marchable distance.
    if (abs(dir.y) < 1e-3) { return vec4<f32>(0.0); }
    let inv_dy = 1.0 / dir.y;
    var t_in  = (CLOUD_BASE - origin.y) * inv_dy;
    var t_out = (CLOUD_TOP  - origin.y) * inv_dy;
    if (t_in > t_out) { let tmp = t_in; t_in = t_out; t_out = tmp; }
    let t_start = max(t_in, 0.0);
    let t_end   = min(t_out, t_terrain);
    if (t_end <= t_start + 0.5) { return vec4<f32>(0.0); }
    // Distance-clamp the slab — beyond this clouds blend into atmospheric fog.
    let t_far_clamp = min(t_end, t_start + 600.0);

    let s = sun_dir();
    let sc = sun_color(s);

    // Half the marching steps of the original full-res march — the TAA pass
    // temporally accumulates the result on a static camera, so the lower
    // per-frame sample count is upsampled over time instead of in one frame
    // (checklist: clouds at reduced res + temporal upsample).
    let N: i32 = 6;
    let step_t = (t_far_clamp - t_start) / f32(N);
    // Spatial-only jitter (no time) — time-varying jitter combined with the
    // temporal-differential pass that re-renders only some tiles per frame
    // creates a stable-but-time-correlated mismatch between adjacent
    // pixels, which reads as a checkerboard pattern over time.
    let h = ign(pix.x, pix.y, 0.0);

    // Henyey-Greenstein forward-scatter — gives the "silver lining" effect
    // when looking toward the sun through cloud edges.
    let cos_sun = dot(dir, s);
    let phase = phase_hg(cos_sun, 0.65) * 4.0 + 0.5;

    var transmittance: f32 = 1.0;
    var scattered: vec3<f32> = vec3<f32>(0.0);
    // Day/night-aware ambient (was hardcoded blue — clouds glowed at night).
    // Scale ambient_color a bit so daytime clouds still read as bright.
    let ambient = ambient_color() * 1.6 + sc * 0.10;

    for (var i: i32 = 0; i < N; i = i + 1) {
        let t = t_start + (f32(i) + h) * step_t;
        let p = origin + dir * t;
        let d = cloud_density(p, camera.time);
        if (d < 0.01) { continue; }

        // 2 cone samples toward the sun for self-shadowing (TAA accumulates).
        var sun_dens: f32 = 0.0;
        for (var j: i32 = 1; j <= 2; j = j + 1) {
            let pj = p + s * f32(j) * 9.0;
            sun_dens = sun_dens + cloud_density(pj, camera.time);
        }
        let sun_t = exp(-sun_dens * 0.62);
        let local_col = ambient + sc * sun_t * phase;

        let sample_t = exp(-d * step_t * 0.14);
        let alpha = (1.0 - sample_t) * transmittance;
        scattered = scattered + local_col * alpha;
        transmittance = transmittance * sample_t;
        if (transmittance < 0.02) { break; }
    }

    let alpha = 1.0 - transmittance;
    return vec4<f32>(scattered, alpha);
}

// Henyey-Greenstein phase function — anisotropic single-scatter widely used
// for clouds/atmosphere. g ∈ [-1, 1]: positive = forward-scatter (Mie-like),
// matches real sunbeam behaviour. Returns the *relative* phase; we apply our
// own brightness scaling.
fn phase_hg(cos_th: f32, g: f32) -> f32 {
    let denom = 1.0 + g * g - 2.0 * g * cos_th;
    return (1.0 - g * g) / (4.0 * 3.14159265 * pow(max(denom, 1e-3), 1.5));
}

// Volumetric god rays. Henyey-Greenstein phase (g≈0.7) gives the natural
// "halo gets brighter as you look closer to the sun" falloff. IGN jitter is
// reused so adjacent pixels get well-distributed offsets — important for
// noise that the temporal-differential pass can average away.
fn god_rays(origin: vec3<f32>, dir: vec3<f32>, t_far: f32, pix: vec2<f32>) -> vec3<f32> {
    let s = sun_dir();
    let s_int = sun_intensity(s);
    if (s_int <= 0.0) { return vec3<f32>(0.0); }
    let cos_sun = dot(dir, s);
    // Normalize HG phase to a 0..~1 scale at g=0.7 — peak ≈ 0.65 forward, ≈ 0.014 back.
    let phase = phase_hg(cos_sun, 0.7) * 4.0;
    if (phase < 0.05) { return vec3<f32>(0.0); }

    let t_max = min(t_far, 140.0);
    if (t_max <= 1.0) { return vec3<f32>(0.0); }
    // Sample count scales with phase — looking right at the sun gets denser
    // sampling for a smooth halo; off-axis stays cheap.
    // Reduced step count; TAA accumulates the god-ray term across frames.
    let N: i32 = select(3, 6, phase > 0.40);
    let step_t = t_max / f32(N);
    let h = ign(pix.x, pix.y, camera.time * 60.0);
    var sum = 0.0;
    for (var i: i32 = 0; i < N; i = i + 1) {
        let t = (f32(i) + h) * step_t;
        let p = origin + dir * t;
        if (!trace_any(p + s * 0.5, s)) {
            // Distance-weighted contribution: nearer scatter looks brighter.
            sum = sum + exp(-t * 0.008);
        }
    }
    let frac = sum / f32(N);
    return sun_color(s) * frac * phase * 0.22 * s_int;
}

// Stripped-down DDA — same hierarchy as `trace()` but returns the moment we
// know the ray is occluded. No normal / material work.
fn trace_any(origin: vec3<f32>, dir: vec3<f32>) -> bool {
    // Origin-rebased (see trace() for the rationale).
    let ro = camera.world_origin;
    let org = origin - vec3<f32>(ro);
    let dims = vec3<f32>(f32(WORLD_VOXELS_X), f32(WORLD_VOXELS_Y), f32(WORLD_VOXELS_Z));
    let inv_dir = vec3<f32>(safe_inv(dir.x), safe_inv(dir.y), safe_inv(dir.z));
    let t0 = (vec3<f32>(0.0) - org) * inv_dir;
    let t1 = (dims - org) * inv_dir;
    let tmin3 = min(t0, t1);
    let tmax3 = max(t0, t1);
    let t_enter = max(max(tmin3.x, tmin3.y), max(tmin3.z, 0.0));
    let t_exit = min(min(tmax3.x, tmax3.y), tmax3.z);
    if (t_enter >= t_exit || t_exit < 0.0) { return false; }

    let bias = 1e-3;
    var p = org + dir * (t_enter + bias);
    p = clamp(p, vec3<f32>(0.01), dims - vec3<f32>(0.01));
    let step = vec3<i32>(sign(dir));
    let t_delta = abs(inv_dir);

    var voxel = vec3<i32>(floor(p)) + ro;
    let vl0 = voxel - ro;
    var t_max: vec3<f32>;
    if (step.x > 0) { t_max.x = (f32(vl0.x + 1) - org.x) * inv_dir.x; } else { t_max.x = (f32(vl0.x) - org.x) * inv_dir.x; }
    if (step.y > 0) { t_max.y = (f32(vl0.y + 1) - org.y) * inv_dir.y; } else { t_max.y = (f32(vl0.y) - org.y) * inv_dir.y; }
    if (step.z > 0) { t_max.z = (f32(vl0.z + 1) - org.z) * inv_dir.z; } else { t_max.z = (f32(vl0.z) - org.z) * inv_dir.z; }

    var last_axis: i32 = -1;
    var t_cur = t_enter;
    for (var s: i32 = 0; s < 768; s = s + 1) {
        if (t_cur > SHADOW_MAX_DIST) { return false; }
        let rel = voxel - camera.world_origin;
        if (rel.x < 0 || rel.x >= WORLD_VOXELS_X
         || rel.y < 0 || rel.y >= WORLD_VOXELS_Y
         || rel.z < 0 || rel.z >= WORLD_VOXELS_Z) { return false; }

        let slot_v = world_to_slot_voxel(voxel);
        let bp = slot_v >> vec3<u32>(2u);
        let tp = slot_v >> vec3<u32>(4u);
        let cp = slot_v >> vec3<u32>(6u);
        // Nested hierarchy: skip the coarsest empty cell (L4 → chunk → tile → brick).
        let l4p = slot_v >> vec3<u32>(8u);
        let l4i = world_l4_idx(l4p.x, l4p.y, l4p.z);
        if (l4_cell_empty(l4i)) {
            skip_to_cell(256, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
            t_cur = axis_select(t_max, last_axis) - axis_select(t_delta, last_axis);
            continue;
        }
        let chunk_lin = (cp.x & 3) + (cp.z & 3) * 4 + (cp.y & 3) * 16;
        if (!l4_has_child(l4i, chunk_lin)) {
            skip_to_cell(64, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
            t_cur = axis_select(t_max, last_axis) - axis_select(t_delta, last_axis);
            continue;
        }
        let ci = world_chunk_idx(cp.x, cp.y, cp.z);
        let tile_lin = (tp.x & 3) + (tp.z & 3) * 4 + (tp.y & 3) * 16;
        if (!chunk_has_child(ci, tile_lin)) {
            skip_to_cell(16, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
            t_cur = axis_select(t_max, last_axis) - axis_select(t_delta, last_axis);
            continue;
        }
        let ti = world_tile_idx(tp.x, tp.y, tp.z);
        let brick_lin = (bp.x & 3) + (bp.z & 3) * 4 + (bp.y & 3) * 16;
        if (!tile_has_child(ti, brick_lin)) {
            skip_to_cell(4, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
            t_cur = axis_select(t_max, last_axis) - axis_select(t_delta, last_axis);
            continue;
        }
        let bi = world_brick_idx(bp.x, bp.y, bp.z);
        let local = slot_v - bp * BRICK_DIM;
        let vi = brick_voxel_idx(local.x, local.y, local.z);
        if (brick_voxel_solid(bi, vi)) {
            let m = brick_voxel_material(bi, vi);
            if (is_foliage_mat(m)) {
                // Far foliage blocks as a solid cube (cheap); only near foliage
                // pays for the per-blade dappled-shadow test.
                if (t_cur > FOLIAGE_NEAR_T) { return true; }
                let fh = foliage_subvoxel(voxel, origin, dir, m);
                if (fh.hit) { return true; }
            } else {
                return true;
            }
        }

        if (t_max.x < t_max.y && t_max.x < t_max.z) {
            t_cur = t_max.x;
            voxel.x = voxel.x + step.x;
            t_max.x = t_max.x + t_delta.x;
            last_axis = 0;
        } else if (t_max.y < t_max.z) {
            t_cur = t_max.y;
            voxel.y = voxel.y + step.y;
            t_max.y = t_max.y + t_delta.y;
            last_axis = 1;
        } else {
            t_cur = t_max.z;
            voxel.z = voxel.z + step.z;
            t_max.z = t_max.z + t_delta.z;
            last_axis = 2;
        }
    }
    return false;
}

// Bit-packed AO. We project the hit point onto the face we entered through,
// compute fractional (fa, fb) coords on that face, sample 4 corner AOs, and
// bilinear-interpolate. Each corner samples 3 neighbours (two side voxels
// and the diagonal) — classic "Minecraft" AO formula, but every lookup is a
// hierarchical bit test rather than a struct fetch.
fn compute_ao(hit: Hit, origin: vec3<f32>, dir: vec3<f32>) -> f32 {
    let p_hit = origin + dir * hit.t_hit;
    let v = hit.voxel;
    let na = hit.last_axis;
    if (na < 0) { return 1.0; }
    // n_dir is +1 or -1 — the outward-facing component of the normal axis.
    let n_dir = i32(hit.normal[na]);
    var n_off = vec3<i32>(0);
    if (na == 0) { n_off.x = n_dir; }
    else if (na == 1) { n_off.y = n_dir; }
    else { n_off.z = n_dir; }

    var da_pos: vec3<i32>;
    var db_pos: vec3<i32>;
    var fa: f32;
    var fb: f32;
    let local_frac = p_hit - vec3<f32>(f32(v.x), f32(v.y), f32(v.z));
    if (na == 0) {
        da_pos = vec3<i32>(0, 1, 0); db_pos = vec3<i32>(0, 0, 1);
        fa = local_frac.y; fb = local_frac.z;
    } else if (na == 1) {
        da_pos = vec3<i32>(1, 0, 0); db_pos = vec3<i32>(0, 0, 1);
        fa = local_frac.x; fb = local_frac.z;
    } else {
        da_pos = vec3<i32>(1, 0, 0); db_pos = vec3<i32>(0, 1, 0);
        fa = local_frac.x; fb = local_frac.y;
    }
    let da_neg = -da_pos;
    let db_neg = -db_pos;
    let base = v + n_off;

    let ao00 = ao_corner(base, da_neg, db_neg);
    let ao10 = ao_corner(base, da_pos, db_neg);
    let ao01 = ao_corner(base, da_neg, db_pos);
    let ao11 = ao_corner(base, da_pos, db_pos);

    let fa_c = clamp(fa, 0.0, 1.0);
    let fb_c = clamp(fb, 0.0, 1.0);
    let ao_x0 = mix(ao00, ao10, fa_c);
    let ao_x1 = mix(ao01, ao11, fa_c);
    return mix(ao_x0, ao_x1, fb_c);
}

fn ao_corner(face_base: vec3<i32>, da: vec3<i32>, db: vec3<i32>) -> f32 {
    let s1 = is_voxel_solid(face_base + da);
    let s2 = is_voxel_solid(face_base + db);
    let cd = is_voxel_solid(face_base + da + db);
    // Full occlusion if both side voxels are solid (corner case).
    if (s1 && s2) { return 0.35; }
    let cnt = i32(s1) + i32(s2) + i32(cd);
    return 1.0 - f32(cnt) * 0.22;
}

fn axis_select(v: vec3<f32>, ax: i32) -> f32 {
    if (ax == 0) { return v.x; }
    if (ax == 1) { return v.y; }
    return v.z;
}

// LOD: past this many voxels of distance, terminate the DDA at brick
// granularity instead of per-voxel.
const LOD_BRICK_T: f32 = 400.0;

// Even further out, terminate at TILE (16-voxel) granularity: far terrain is
// blocky but each occupied tile costs one hit instead of a brick/voxel descent
// (checklist: tile-level LOD for far terrain).
const TILE_LOD_T: f32 = 520.0;

// Distance-based ray budget (in voxels). Traversal stops here regardless of how
// many DDA steps it took — replaces the old fixed voxel-step count so small
// voxels can't run the loop out before reaching far geometry (holes-through-
// terrain) and so empty rays don't waste steps. Comfortably covers the loaded
// window (the camera sits at its centre).
const MAX_RAY_DIST: f32 = 700.0;

// Beyond this distance, procedural sub-voxel foliage (22-blade grass, leaf
// alpha-cutouts) is treated as a solid cube rather than ray-marched. The
// per-blade detail is sub-pixel far away and that inner loop is the single most
// divergent/expensive thing a ray can hit (checklist: limit procedural foliage
// to the nearest few metres).
const FOLIAGE_NEAR_T: f32 = 72.0;

// Shadow / occlusion rays give up past this distance (treated as lit). Far
// shadows contribute little and are the most expensive secondary rays
// (checklist: cheaper secondary rays / coarse shadows).
const SHADOW_MAX_DIST: f32 = 480.0;

// Beyond this distance, skip per-corner ambient occlusion (its contact-shadow
// detail is sub-pixel far away). 12 hierarchical lookups/pixel saved on the
// bulk of the screen.
const AO_DIST: f32 = 64.0;

fn trace(origin: vec3<f32>, dir: vec3<f32>) -> Hit {
    var out: Hit;
    out.hit = false;
    out.mat = 0u;
    out.normal = vec3<f32>(0.0);
    out.voxel = vec3<i32>(0);
    out.last_axis = -1;
    out.t_hit = 0.0;

    // ---- Origin-rebased traversal (checklist: rebase to window-relative) ----
    // The integer voxel grid stays in ABSOLUTE world coords (so cell alignment
    // and the toroidal slot lookup are unchanged), but every FLOAT computation
    // is done relative to the window corner `ro`. At large world coords
    // `f32(voxel) - origin` catastrophically cancels (the "sky through hills"
    // bug + the 1e-2 bias hack); `f32(voxel - ro) - (origin - ro)` keeps both
    // operands small and exact. The ray parameter t is a distance, unchanged by
    // the rebase.
    let ro = camera.world_origin;
    let org = origin - vec3<f32>(ro);
    let dims = vec3<f32>(f32(WORLD_VOXELS_X), f32(WORLD_VOXELS_Y), f32(WORLD_VOXELS_Z));
    let inv_dir = vec3<f32>(safe_inv(dir.x), safe_inv(dir.y), safe_inv(dir.z));

    let t0 = (vec3<f32>(0.0) - org) * inv_dir;
    let t1 = (dims - org) * inv_dir;
    let tmin3 = min(t0, t1);
    let tmax3 = max(t0, t1);
    let t_enter = max(max(tmin3.x, tmin3.y), max(tmin3.z, 0.0));
    let t_exit = min(min(tmax3.x, tmax3.y), tmax3.z);
    if (t_enter >= t_exit || t_exit < 0.0) { return out; }

    let bias = 1e-3;
    var p = org + dir * (t_enter + bias);
    p = clamp(p, vec3<f32>(0.01), dims - vec3<f32>(0.01));

    let step = vec3<i32>(sign(dir));
    let t_delta = abs(inv_dir);

    var voxel = vec3<i32>(floor(p)) + ro;
    let vl0 = voxel - ro;
    var t_max: vec3<f32>;
    if (step.x > 0) { t_max.x = (f32(vl0.x + 1) - org.x) * inv_dir.x; } else { t_max.x = (f32(vl0.x) - org.x) * inv_dir.x; }
    if (step.y > 0) { t_max.y = (f32(vl0.y + 1) - org.y) * inv_dir.y; } else { t_max.y = (f32(vl0.y) - org.y) * inv_dir.y; }
    if (step.z > 0) { t_max.z = (f32(vl0.z + 1) - org.z) * inv_dir.z; } else { t_max.z = (f32(vl0.z) - org.z) * inv_dir.z; }

    var last_axis: i32 = -1;
    var t_cur: f32 = t_enter;
    let max_steps: i32 = 1024;
    for (var s: i32 = 0; s < max_steps; s = s + 1) {
        // Distance budget — primary termination (the step cap is just a backstop).
        if (t_cur > MAX_RAY_DIST) { return out; }
        // Bounds check on the LOADED WINDOW (world coords).
        let rel = voxel - camera.world_origin;
        if (rel.x < 0 || rel.x >= WORLD_VOXELS_X
         || rel.y < 0 || rel.y >= WORLD_VOXELS_Y
         || rel.z < 0 || rel.z >= WORLD_VOXELS_Z) {
            return out;
        }

        let slot_v = world_to_slot_voxel(voxel);
        let bp = slot_v >> vec3<u32>(2u);
        let tp = slot_v >> vec3<u32>(4u);
        let cp = slot_v >> vec3<u32>(6u);

        // ---- Nested hierarchical descent: skip the COARSEST empty cell ----
        // L4 (256) → chunk (64) → tile (16) → brick (4) → voxel. Each empty
        // level skips its whole cell in one DDA jump, so empty space (most of a
        // ray) costs O(coarse steps) instead of O(voxels) — this is what keeps
        // traversal cheap as voxels shrink.
        if (!PROFILE_NO_L4) {
            let l4p = slot_v >> vec3<u32>(8u);
            let l4i = world_l4_idx(l4p.x, l4p.y, l4p.z);
            if (l4_cell_empty(l4i)) {
                skip_to_cell(256, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
                t_cur = axis_select(t_max, last_axis) - axis_select(t_delta, last_axis);
                continue;
            }
            let chunk_lin = (cp.x & 3) + (cp.z & 3) * 4 + (cp.y & 3) * 16;
            if (!l4_has_child(l4i, chunk_lin)) {
                skip_to_cell(64, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
                t_cur = axis_select(t_max, last_axis) - axis_select(t_delta, last_axis);
                continue;
            }
        }

        let ci = world_chunk_idx(cp.x, cp.y, cp.z);
        let tile_in_chunk_lin = (tp.x & 3) + (tp.z & 3) * 4 + (tp.y & 3) * 16;
        if (!chunk_has_child(ci, tile_in_chunk_lin)) {
            skip_to_cell(16, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
            t_cur = axis_select(t_max, last_axis) - axis_select(t_delta, last_axis);
            continue;
        }

        let ti = world_tile_idx(tp.x, tp.y, tp.z);

        // ---- Tile-level LOD: far terrain terminates at the (occupied) tile ----
        if (t_cur > TILE_LOD_T) {
            let lm = tile_representative_material(ti, tp);
            if (lm != 0u && is_uniform_optimisable(lm)) {
                var n = vec3<f32>(0.0);
                var t_hit: f32;
                if (last_axis == 0)      { n.x = -f32(step.x); t_hit = t_max.x - t_delta.x; }
                else if (last_axis == 1) { n.y = -f32(step.y); t_hit = t_max.y - t_delta.y; }
                else if (last_axis == 2) { n.z = -f32(step.z); t_hit = t_max.z - t_delta.z; }
                else {
                    t_hit = t_enter;
                    if      (tmin3.x >= tmin3.y && tmin3.x >= tmin3.z) { n.x = -f32(step.x); }
                    else if (tmin3.y >= tmin3.z)                       { n.y = -f32(step.y); }
                    else                                               { n.z = -f32(step.z); }
                }
                out.hit = true;
                out.mat = lm;
                out.normal = n;
                out.voxel = voxel;
                out.last_axis = last_axis_after_entry(last_axis, tmin3);
                out.t_hit = t_hit;
                return out;
            }
        }

        // ---- Fast-skip: uniform 16-voxel tile (one material throughout) ----
        // Whole 4096-voxel tile is one opaque material — surface at entry face.
        let tum = tile_uniform_mat(ti);
        if (tum != 0u && is_uniform_optimisable(tum)) {
            var n = vec3<f32>(0.0);
            var t_hit: f32;
            if (last_axis == 0)      { n.x = -f32(step.x); t_hit = t_max.x - t_delta.x; }
            else if (last_axis == 1) { n.y = -f32(step.y); t_hit = t_max.y - t_delta.y; }
            else if (last_axis == 2) { n.z = -f32(step.z); t_hit = t_max.z - t_delta.z; }
            else {
                t_hit = t_enter;
                if      (tmin3.x >= tmin3.y && tmin3.x >= tmin3.z) { n.x = -f32(step.x); }
                else if (tmin3.y >= tmin3.z)                       { n.y = -f32(step.y); }
                else                                               { n.z = -f32(step.z); }
            }
            out.hit = true;
            out.mat = tum;
            out.normal = n;
            out.voxel = voxel;
            out.last_axis = last_axis_after_entry(last_axis, tmin3);
            out.t_hit = t_hit;
            return out;
        }

        let brick_in_tile_lin = (bp.x & 3) + (bp.z & 3) * 4 + (bp.y & 3) * 16;
        if (!tile_has_child(ti, brick_in_tile_lin)) {
            skip_to_cell(4, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
            t_cur = axis_select(t_max, last_axis) - axis_select(t_delta, last_axis);
            continue;
        }

        let bi = world_brick_idx(bp.x, bp.y, bp.z);

        // ---- Fast-skip: uniform 4-voxel brick (one material throughout) ----
        let bum = brick_uniform_mat(bi);
        if (bum != 0u && is_uniform_optimisable(bum)) {
            var n = vec3<f32>(0.0);
            var t_hit: f32;
            if (last_axis == 0)      { n.x = -f32(step.x); t_hit = t_max.x - t_delta.x; }
            else if (last_axis == 1) { n.y = -f32(step.y); t_hit = t_max.y - t_delta.y; }
            else if (last_axis == 2) { n.z = -f32(step.z); t_hit = t_max.z - t_delta.z; }
            else {
                t_hit = t_enter;
                if      (tmin3.x >= tmin3.y && tmin3.x >= tmin3.z) { n.x = -f32(step.x); }
                else if (tmin3.y >= tmin3.z)                       { n.y = -f32(step.y); }
                else                                               { n.z = -f32(step.z); }
            }
            out.hit = true;
            out.mat = bum;
            out.normal = n;
            out.voxel = voxel;
            out.last_axis = last_axis_after_entry(last_axis, tmin3);
            out.t_hit = t_hit;
            return out;
        }

        // ---- LOD: brick-level early termination at far distance ----
        // If we're far enough away that voxels are sub-pixel anyway, take
        // the brick's representative material and return — saves the inner
        // per-voxel DDA loop (up to ~7 steps per brick).
        if (t_cur > LOD_BRICK_T) {
            let b = bricks[bi];
            if ((b.occ_lo | b.occ_hi) == 0u) {
                // Empty brick — skip the whole 4-voxel cell.
                skip_to_cell(4, &voxel, &t_max, ro, org, dir, inv_dir, step, &last_axis);
                t_cur = axis_select(t_max, last_axis) - axis_select(t_delta, last_axis);
                continue;
            }
            let m = brick_topmost_material(bi);
            // Collapse the brick to its representative material — UNLESS the top
            // is foliage (a flower/grass/leaf cube would look wrong); in that
            // case fall through to the per-voxel descent below.
            if (!is_foliage_mat(m)) {
                var n = vec3<f32>(0.0);
                var t_hit: f32;
                if (last_axis == 0)      { n.x = -f32(step.x); t_hit = t_max.x - t_delta.x; }
                else if (last_axis == 1) { n.y = -f32(step.y); t_hit = t_max.y - t_delta.y; }
                else if (last_axis == 2) { n.z = -f32(step.z); t_hit = t_max.z - t_delta.z; }
                else {
                    t_hit = t_enter;
                    if      (tmin3.x >= tmin3.y && tmin3.x >= tmin3.z) { n.x = -f32(step.x); }
                    else if (tmin3.y >= tmin3.z)                      { n.y = -f32(step.y); }
                    else                                              { n.z = -f32(step.z); }
                }
                out.hit = true;
                out.mat = m;
                out.normal = n;
                out.voxel = voxel;
                out.last_axis = last_axis_after_entry(last_axis, tmin3);
                out.t_hit = t_hit;
                return out;
            }
        }

        let local = slot_v - bp * BRICK_DIM;
        let vi = brick_voxel_idx(local.x, local.y, local.z);
        if (brick_voxel_solid(bi, vi)) {
            let m = brick_voxel_material(bi, vi);
            // Near foliage gets the full per-blade procedural cutout. Far
            // foliage: leaves become solid cubes (the else branch) so canopies
            // survive, but ground decoration (flowers / tall grass) is skipped
            // entirely — drawing it as a solid cube is the "pink blocks" bug.
            if (is_foliage_mat(m) && t_cur <= FOLIAGE_NEAR_T) {
                let fh = foliage_subvoxel(voxel, origin, dir, m);
                if (fh.hit) {
                    out.hit = true;
                    out.mat = m;
                    out.normal = fh.normal;
                    out.voxel = voxel;
                    out.last_axis = -1;
                    out.t_hit = fh.t_hit;
                    g_foliage_tint = fh.color_tint;
                    return out;
                }
                // cutout missed → fall through to the DDA step below.
            } else if (is_decoration_mat(m)) {
                // Far decoration → invisible; fall through to the DDA step.
            } else {
                var n = vec3<f32>(0.0);
                var t_hit: f32;
                if (last_axis == 0) {
                    n.x = -f32(step.x);
                    t_hit = t_max.x - t_delta.x;
                } else if (last_axis == 1) {
                    n.y = -f32(step.y);
                    t_hit = t_max.y - t_delta.y;
                } else if (last_axis == 2) {
                    n.z = -f32(step.z);
                    t_hit = t_max.z - t_delta.z;
                } else {
                    t_hit = t_enter;
                    if      (tmin3.x >= tmin3.y && tmin3.x >= tmin3.z) { n.x = -f32(step.x); }
                    else if (tmin3.y >= tmin3.z)                      { n.y = -f32(step.y); }
                    else                                              { n.z = -f32(step.z); }
                }
                out.hit = true;
                out.mat = m;
                out.normal = n;
                out.voxel = voxel;
                out.last_axis = last_axis_after_entry(last_axis, tmin3);
                out.t_hit = t_hit;
                return out;
            }
        }

        if (t_max.x < t_max.y && t_max.x < t_max.z) {
            t_cur = t_max.x;
            voxel.x = voxel.x + step.x;
            t_max.x = t_max.x + t_delta.x;
            last_axis = 0;
        } else if (t_max.y < t_max.z) {
            t_cur = t_max.y;
            voxel.y = voxel.y + step.y;
            t_max.y = t_max.y + t_delta.y;
            last_axis = 1;
        } else {
            t_cur = t_max.z;
            voxel.z = voxel.z + step.z;
            t_max.z = t_max.z + t_delta.z;
            last_axis = 2;
        }
    }
    return out;
}

// Representative material of a 16-voxel tile for far tile-LOD: the topmost
// solid voxel of the tile's first occupied child brick. tp = tile coord in slot
// space.
fn tile_representative_material(ti: i32, tp: vec3<i32>) -> u32 {
    let base = ti * 2;
    var lin: i32 = -1;
    let lo = tile_mask[base];
    if (lo != 0u) {
        lin = i32(firstTrailingBit(lo));
    } else {
        let hi = tile_mask[base + 1];
        if (hi != 0u) { lin = 32 + i32(firstTrailingBit(hi)); }
    }
    if (lin < 0) { return 0u; }
    let lx = lin & 3;
    let lz = (lin >> 2) & 3;
    let ly = (lin >> 4) & 3;
    let bi = world_brick_idx(tp.x * 4 + lx, tp.y * 4 + ly, tp.z * 4 + lz);
    return brick_topmost_material(bi);
}

fn last_axis_after_entry(la: i32, tmin3: vec3<f32>) -> i32 {
    if (la >= 0) { return la; }
    if (tmin3.x >= tmin3.y && tmin3.x >= tmin3.z) { return 0; }
    if (tmin3.y >= tmin3.z) { return 1; }
    return 2;
}

fn skip_to_cell(
    cell_size: i32,
    voxel: ptr<function, vec3<i32>>,
    t_max: ptr<function, vec3<f32>>,
    ro: vec3<i32>,        // rebase reference (window corner, world voxels)
    org: vec3<f32>,       // ray origin in window-local coords (= origin - ro)
    dir: vec3<f32>,
    inv_dir: vec3<f32>,
    step: vec3<i32>,
    last_axis: ptr<function, i32>,
) {
    // Cell alignment is in ABSOLUTE world coords (cell_size divides
    // WORLD_VOXELS so this matches the toroidal slot cells). Only the float t
    // math is done relative to `ro` for precision.
    let cell_origin = vec3<i32>(
        (*voxel).x - pos_mod((*voxel).x, cell_size),
        (*voxel).y - pos_mod((*voxel).y, cell_size),
        (*voxel).z - pos_mod((*voxel).z, cell_size),
    );
    // Local-space cell boundary (small integers → exact in f32).
    var bnd: vec3<f32>;
    bnd.x = f32(select(cell_origin.x, cell_origin.x + cell_size, step.x > 0) - ro.x);
    bnd.y = f32(select(cell_origin.y, cell_origin.y + cell_size, step.y > 0) - ro.y);
    bnd.z = f32(select(cell_origin.z, cell_origin.z + cell_size, step.z > 0) - ro.z);
    let t_face = (bnd - org) * inv_dir;
    let eps = 1e-6;
    var t_min: f32 = 1e30;
    var ax: i32 = 0;
    if (step.x != 0 && t_face.x > eps && t_face.x < t_min) { t_min = t_face.x; ax = 0; }
    if (step.y != 0 && t_face.y > eps && t_face.y < t_min) { t_min = t_face.y; ax = 1; }
    if (step.z != 0 && t_face.z > eps && t_face.z < t_min) { t_min = t_face.z; ax = 2; }
    let bias = 1e-3;
    let p_new = org + dir * (t_min + bias);
    var nv = vec3<i32>(floor(p_new)) + ro;
    // Integer-snap the crossed axis exactly (float floor can land on the wrong
    // side of a boundary; the cell math is exact).
    if (ax == 0) {
        if (step.x > 0) { nv.x = cell_origin.x + cell_size; }
        else            { nv.x = cell_origin.x - 1; }
    } else if (ax == 1) {
        if (step.y > 0) { nv.y = cell_origin.y + cell_size; }
        else            { nv.y = cell_origin.y - 1; }
    } else {
        if (step.z > 0) { nv.z = cell_origin.z + cell_size; }
        else            { nv.z = cell_origin.z - 1; }
    }
    (*voxel) = nv;
    // t_max for the new cell, computed in local coords.
    let vl = nv - ro;
    if (step.x > 0) { (*t_max).x = (f32(vl.x + 1) - org.x) * inv_dir.x; } else { (*t_max).x = (f32(vl.x) - org.x) * inv_dir.x; }
    if (step.y > 0) { (*t_max).y = (f32(vl.y + 1) - org.y) * inv_dir.y; } else { (*t_max).y = (f32(vl.y) - org.y) * inv_dir.y; }
    if (step.z > 0) { (*t_max).z = (f32(vl.z + 1) - org.z) * inv_dir.z; } else { (*t_max).z = (f32(vl.z) - org.z) * inv_dir.z; }
    *last_axis = ax;
}
