use std::sync::Arc;

use bytemuck::{Pod, Zeroable};
use wgpu::util::DeviceExt;
use winit::window::Window;

/// WGSL world-dimension constants generated by build.rs from `src/world_dims.rs`.
/// Prepended to every shader so the GPU and CPU agree on world size with a
/// single source of truth.
const WORLD_CONSTS_WGSL: &str = include_str!(concat!(env!("OUT_DIR"), "/world_consts.wgsl"));

/// Shared render-shader prelude (Camera uniform + tiny helpers). Prepended
/// after the world consts to raymarch/beam/taa so those three carry one
/// definition instead of a hand-maintained copy each. NOT used by physics/blit.
const COMMON_WGSL: &str = include_str!("../shaders/common.wgsl");

/// Pack a Vec<u8> into Vec<u32> for storage-buffer upload (WGSL storage
/// buffers can't directly index u8 arrays; reading byte b of word w via
/// `(packed[w] >> ((b & 3) * 8)) & 0xFF` is the canonical pattern).
fn pack_u8_to_u32(src: &[u8]) -> Vec<u32> {
    let n_words = (src.len() + 3) / 4;
    let mut out = vec![0u32; n_words];
    for (i, &b) in src.iter().enumerate() {
        let w = i >> 2;
        let bit = (i & 3) * 8;
        out[w] |= (b as u32) << bit;
    }
    out
}

/// Coalesce a SORTED, DEDUPED slice of element indices into contiguous runs and
/// invoke `f(start, end_inclusive)` once per run. Turns thousands of tiny DMAs
/// into a handful of multi-KB writes.
fn upload_spans(sorted: &[u32], mut f: impl FnMut(u32, u32)) {
    let mut i = 0usize;
    while i < sorted.len() {
        let start = sorted[i];
        let mut end = start;
        let mut j = i + 1;
        while j < sorted.len() && sorted[j] == end + 1 {
            end = sorted[j];
            j += 1;
        }
        f(start, end);
        i = j;
    }
}

/// Upload the given packed-u32 word indices (sorted, deduped) of a byte table
/// (1 byte per element, packed 4 per word) by re-packing each contiguous word
/// run from `bytes` and writing it at the matching word offset.
fn upload_packed_word_spans(
    words: &[u32],
    bytes: &[u8],
    queue: &wgpu::Queue,
    buf: &wgpu::Buffer,
) {
    upload_spans(words, |w_start, w_end| {
        let b0 = (w_start as usize) * 4;
        let b1 = (((w_end as usize) + 1) * 4).min(bytes.len());
        let packed = pack_u8_to_u32(&bytes[b0..b1]);
        queue.write_buffer(buf, w_start as u64 * 4, bytemuck::cast_slice(&packed));
    });
}

/// Project element indices `src` to their packed-u32 word indices (deduped via
/// `scratch`) and re-pack + upload only those words of the byte `table`. Shared
/// by the brick-uniform and tile-uniform incremental uploads.
fn upload_words_for(
    scratch: &mut Vec<u32>, src: &[u32], table: &[u8], queue: &wgpu::Queue, buf: &wgpu::Buffer,
) {
    scratch.clear();
    for &x in src {
        let w = x >> 2;
        if scratch.last() != Some(&w) { scratch.push(w); }
    }
    upload_packed_word_spans(scratch, table, queue, buf);
}

/// Project a set of tile indices up to their parent chunks (via `scratch`, which
/// is sorted+deduped) and DMA the touched chunk_mask runs. Does NOT refresh L4 —
/// the caller decides that.
fn upload_chunks_for_tiles(
    scratch: &mut Vec<u32>, tiles: &[u32], chunk_mask: &[u64], queue: &wgpu::Queue, buf: &wgpu::Buffer,
) {
    scratch.clear();
    for &t in tiles {
        let tx = t % WORLD_TILES_X;
        let ty = (t / WORLD_TILES_X) % WORLD_TILES_Y;
        let tz = t / (WORLD_TILES_X * WORLD_TILES_Y);
        scratch.push(chunk_idx(tx / 4, ty / 4, tz / 4));
    }
    scratch.sort_unstable();
    scratch.dedup();
    upload_spans(scratch, |s, e| {
        let slice = &chunk_mask[s as usize..=e as usize];
        queue.write_buffer(buf, s as u64 * 8, bytemuck::cast_slice(slice));
    });
}

use crate::camera::{Camera, CameraUniform};
use crate::voxel::{
    Brick, World, WORLD_TILES_X, WORLD_TILES_Y,
    tile_idx, chunk_idx, brick_coords,
    MAT_AIR, MAT_SAND, MAT_GRASS, MAT_DIRT, MAT_STONE,
    MAT_WATER_L1, MAT_WATER_L8,
    MAT_WOOD, MAT_LEAVES, MAT_SNOW, MAT_LAVA, MAT_ICE, MAT_GLASS,
    MAT_COAL, MAT_IRON, MAT_GOLD, MAT_DIAMOND,
    MAT_WOOD_BIRCH, MAT_WOOD_PINE, MAT_LEAVES_BIRCH, MAT_LEAVES_PINE, MAT_LEAVES_AUTUMN,
    MAT_SMOKE, MAT_FIRE, MAT_FLOWER, MAT_TALL_GRASS, MAT_CACTUS,
};

#[repr(C)]
#[derive(Copy, Clone, Pod, Zeroable)]
struct PaletteEntry([f32; 4]);

pub const MAX_REMOTE_PLAYERS: usize = 16;

#[repr(C)]
#[derive(Copy, Clone, Pod, Zeroable)]
struct PlayersBuf {
    count: u32,
    _pad: [u32; 3],
    positions: [[f32; 4]; MAX_REMOTE_PLAYERS],
}

const PALETTE_SIZE: usize = 256;

fn default_palette() -> [PaletteEntry; PALETTE_SIZE] {
    let mut p = [PaletteEntry([0.0; 4]); PALETTE_SIZE];
    p[MAT_AIR   as usize] = PaletteEntry([0.0, 0.0, 0.0, 0.0]);
    p[MAT_SAND  as usize] = PaletteEntry([0.94, 0.85, 0.55, 1.0]);
    p[MAT_GRASS as usize] = PaletteEntry([0.30, 0.65, 0.20, 1.0]);
    p[MAT_DIRT  as usize] = PaletteEntry([0.40, 0.27, 0.15, 1.0]);
    p[MAT_STONE as usize] = PaletteEntry([0.55, 0.55, 0.55, 1.0]);
    let water = [0.10, 0.45, 0.75, 1.0];
    for m in MAT_WATER_L1..=MAT_WATER_L8 {
        p[m as usize] = PaletteEntry(water);
    }
    p[MAT_WOOD as usize]   = PaletteEntry([0.42, 0.27, 0.13, 1.0]);
    p[MAT_LEAVES as usize] = PaletteEntry([0.30, 0.58, 0.20, 1.0]);
    p[MAT_SNOW as usize]   = PaletteEntry([0.95, 0.96, 0.99, 1.0]);
    p[MAT_LAVA as usize]   = PaletteEntry([1.40, 0.40, 0.10, 1.0]);
    p[MAT_ICE as usize]    = PaletteEntry([0.70, 0.85, 0.95, 1.0]);
    p[MAT_GLASS as usize]  = PaletteEntry([0.90, 0.96, 0.99, 1.0]);
    p[MAT_COAL as usize]    = PaletteEntry([0.10, 0.10, 0.12, 1.0]);
    p[MAT_IRON as usize]    = PaletteEntry([0.62, 0.55, 0.45, 1.0]);
    p[MAT_GOLD as usize]    = PaletteEntry([1.20, 0.90, 0.20, 1.0]);
    p[MAT_DIAMOND as usize] = PaletteEntry([0.55, 0.92, 0.98, 1.0]);
    p[MAT_WOOD_BIRCH as usize]    = PaletteEntry([0.85, 0.82, 0.72, 1.0]);
    p[MAT_WOOD_PINE as usize]     = PaletteEntry([0.25, 0.15, 0.08, 1.0]);
    p[MAT_LEAVES_BIRCH as usize]  = PaletteEntry([0.55, 0.78, 0.34, 1.0]);
    p[MAT_LEAVES_PINE as usize]   = PaletteEntry([0.14, 0.38, 0.16, 1.0]);
    p[MAT_LEAVES_AUTUMN as usize] = PaletteEntry([0.90, 0.42, 0.15, 1.0]);
    p[MAT_SMOKE as usize]   = PaletteEntry([0.65, 0.65, 0.70, 1.0]);
    p[MAT_FIRE as usize]    = PaletteEntry([1.60, 0.60, 0.10, 1.0]);
    p[MAT_FLOWER as usize]      = PaletteEntry([1.10, 0.35, 0.65, 1.0]);
    p[MAT_TALL_GRASS as usize]  = PaletteEntry([0.38, 0.70, 0.25, 1.0]);
    p[MAT_CACTUS as usize]      = PaletteEntry([0.28, 0.50, 0.30, 1.0]);
    p
}

/// Render at 1/N the swapchain resolution per axis. 1 = native resolution,
/// 2 = half-res = 1/4 pixel count. The blit upscales with bilinear filtering
/// + light sharpen so values >1 still read as crisp, but the user prefers
/// the sharp native look so we run at 1:1.
pub const RENDER_SCALE: u32 = 1;

pub struct Renderer {
    pub device: wgpu::Device,
    pub queue: wgpu::Queue,
    pub surface: wgpu::Surface<'static>,
    pub config: wgpu::SurfaceConfiguration,
    /// Compute / raymarch render-target size. = `surface_size / RENDER_SCALE`.
    /// Dispatch counts, temporal-differential tile counts and the camera
    /// uniform's `resolution` all use this.
    pub size: (u32, u32),
    /// Swapchain / window size — used for surface configuration and the blit
    /// pass. Stays at the native resolution the OS gives us.
    pub surface_size: (u32, u32),

    camera_buf: wgpu::Buffer,
    bricks_buf: wgpu::Buffer,
    // GPU-compute physics (#25): second brick buffer + pipeline. `gpu_physics`
    // is opt-in via the VOXELG_GPU_PHYSICS env var.
    bricks_buf_b: wgpu::Buffer,
    physics_pipeline: wgpu::ComputePipeline,
    physics_bg: wgpu::BindGroup,
    pub gpu_physics: bool,
    tile_mask_buf: wgpu::Buffer,
    chunk_mask_buf: wgpu::Buffer,
    l4_mask_buf: wgpu::Buffer,
    brick_uniform_buf: wgpu::Buffer,
    tile_uniform_buf: wgpu::Buffer,
    palette_buf: wgpu::Buffer,
    sprites_buf: wgpu::Buffer,
    tile_dirty_buf: wgpu::Buffer,
    players_buf: wgpu::Buffer,

    output_tex: wgpu::Texture,
    output_view: wgpu::TextureView,
    beam_tex: wgpu::Texture,
    beam_view: wgpu::TextureView,
    // TAA: history = previous resolved frame; resolve = this frame's resolved
    // output (also what the blit samples). output_tex is the raw raymarch.
    history_tex: wgpu::Texture,
    history_view: wgpu::TextureView,
    resolve_tex: wgpu::Texture,
    resolve_view: wgpu::TextureView,
    sampler: wgpu::Sampler,

    beam_bgl: wgpu::BindGroupLayout,
    beam_pipeline: wgpu::ComputePipeline,
    beam_bg: wgpu::BindGroup,

    compute_bgl: wgpu::BindGroupLayout,
    compute_pipeline: wgpu::ComputePipeline,
    compute_bg: wgpu::BindGroup,
    // Deferred transparent pass (#16): shares compute_bgl/compute_bg.
    transparent_pipeline: wgpu::ComputePipeline,
    transp_buf: wgpu::Buffer,

    // Half-res volumetric (cloud) pass. The texture handle is dropped after
    // creation — its views keep the GPU resource alive.
    cloud_bgl: wgpu::BindGroupLayout,
    cloud_pipeline: wgpu::ComputePipeline,
    cloud_bg: wgpu::BindGroup,
    cloud_sampled_view: wgpu::TextureView,
    cloud_storage_view: wgpu::TextureView,

    // Reprojected shadow/AO cache: ping-pong G-buffer (write this frame, read
    // next). `light_out` is copied into `light_hist` at the end of each frame.
    light_out_tex: wgpu::Texture,
    light_out_view: wgpu::TextureView,
    light_hist_tex: wgpu::Texture,
    light_hist_view: wgpu::TextureView,

    blit_bgl: wgpu::BindGroupLayout,
    blit_pipeline: wgpu::RenderPipeline,
    blit_bg: wgpu::BindGroup,

    taa_bgl: wgpu::BindGroupLayout,
    taa_pipeline: wgpu::ComputePipeline,
    taa_bg: wgpu::BindGroup,
    /// Set after (re)creating the history texture so the next frame skips the
    /// TAA blend — otherwise it would read uninitialised history (garbage).
    taa_reset: bool,

    // Reused per-frame scratch for incremental mask/uniform uploads — derived
    // from the dirty-brick list so no extra dirty tracking is needed and no
    // allocation happens on the upload hot path.
    dirty_tiles_scratch: Vec<u32>,
    dirty_chunks_scratch: Vec<u32>,
    dirty_words_scratch: Vec<u32>,

    // Previous frame's camera + world origin, for the lighting reprojection
    // cache. None on the first frame (no reuse).
    prev_cam: Option<Camera>,
    prev_world_origin: glam::IVec3,
}

impl Renderer {
    pub fn new(window: Arc<Window>, world: &World) -> Result<Self, String> {
        let inner = window.inner_size();
        let (surface_w, surface_h) = (inner.width.max(1), inner.height.max(1));
        let (width, height) = (
            (surface_w / RENDER_SCALE).max(1),
            (surface_h / RENDER_SCALE).max(1),
        );

        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            backends: wgpu::Backends::PRIMARY,
            ..Default::default()
        });

        let surface = instance
            .create_surface(window.clone())
            .map_err(|e| format!("create_surface failed: {e}"))?;

        let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::HighPerformance,
            compatible_surface: Some(&surface),
            force_fallback_adapter: false,
        }))
        .ok_or_else(|| "no compatible GPU adapter found".to_string())?;

        let (device, queue) = pollster::block_on(adapter.request_device(
            &wgpu::DeviceDescriptor {
                label: Some("voxel device"),
                required_features: wgpu::Features::empty(),
                required_limits: wgpu::Limits {
                    max_storage_buffer_binding_size: 256 << 20, // 256 MB headroom
                    // Compute pass binds 9 storage buffers (default cap is 8);
                    // the deferred-transparent record buffer pushed it over.
                    max_storage_buffers_per_shader_stage: 12,
                    ..wgpu::Limits::default()
                },
                memory_hints: wgpu::MemoryHints::Performance,
            },
            None,
        ))
        .map_err(|e| format!("request_device failed: {e}"))?;

        let caps = surface.get_capabilities(&adapter);
        let surface_format = caps
            .formats
            .iter()
            .copied()
            .find(|f| !f.is_srgb())
            .unwrap_or(caps.formats[0]);
        let config = wgpu::SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format: surface_format,
            width: surface_w,
            height: surface_h,
            // Explicit present policy: prefer Mailbox (low-latency, tear-free,
            // capped to the display refresh) and fall back to Fifo (vsync,
            // always supported). We deliberately avoid Immediate — it was the
            // source of the uncapped ~1800 fps idle GPU burn.
            present_mode: if std::env::var("VOXELG_UNCAPPED").is_ok()
                && caps.present_modes.contains(&wgpu::PresentMode::Immediate) {
                wgpu::PresentMode::Immediate // measurement: no vsync, uncapped
            } else if caps.present_modes.contains(&wgpu::PresentMode::Mailbox) {
                wgpu::PresentMode::Mailbox
            } else {
                wgpu::PresentMode::Fifo
            },
            alpha_mode: caps.alpha_modes[0],
            view_formats: vec![],
            desired_maximum_frame_latency: 2,
        };
        surface.configure(&device, &config);

        // -- buffers --
        let camera_init = CameraUniform::from_camera(&Camera::new(), width, height, 0.0, glam::IVec3::ZERO, [0.0, 0.0], 0.0);
        let camera_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("camera"),
            contents: bytemuck::bytes_of(&camera_init),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });

        let bricks_bytes: &[u8] = bytemuck::cast_slice(&world.bricks);
        let bricks_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("bricks"),
            contents: bricks_bytes,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });
        // Second brick buffer for the GPU-compute physics ping-pong (#25). The CA
        // reads bricks_buf and writes bricks_buf_b, which is then copied back.
        let bricks_buf_b = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("bricks_b (gpu physics)"),
            size: bricks_bytes.len() as u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
            mapped_at_creation: false,
        });

        let tile_mask_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("tile_mask"),
            contents: bytemuck::cast_slice(&world.tile_mask),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });
        let chunk_mask_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("chunk_mask"),
            contents: bytemuck::cast_slice(&world.chunk_mask),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });
        let l4_mask_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("l4_mask"),
            contents: bytemuck::cast_slice(&world.l4_mask),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });

        // Packed uniform-material lookups (1 byte per brick / tile, packed
        // 4 per u32 word). Lets the DDA skip uniform regions in 1 lookup
        // instead of walking them.
        let brick_uniform_packed = pack_u8_to_u32(&world.brick_uniform);
        let tile_uniform_packed = pack_u8_to_u32(&world.tile_uniform);
        let brick_uniform_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("brick_uniform"),
            contents: bytemuck::cast_slice(&brick_uniform_packed),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });
        let tile_uniform_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("tile_uniform"),
            contents: bytemuck::cast_slice(&tile_uniform_packed),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });

        let palette = default_palette();
        let palette_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("palette"),
            contents: bytemuck::cast_slice(&palette),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });

        // Authored foliage sprites (src/sprites.rs ASCII art, 2bpp texels).
        let sprites_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("foliage sprites"),
            contents: bytemuck::cast_slice(&crate::sprites::encoded()),
            usage: wgpu::BufferUsages::STORAGE,
        });

        // Tile-dirty bitmask.
        let tile_dirty_words: u64 = ((3840u64 / 8 + 1) * (2160u64 / 8 + 1) + 31) / 32;
        let tile_dirty_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("tile_dirty"),
            size: tile_dirty_words * 4,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        // Remote-player marker positions (multiplayer rendering).
        let players_init = PlayersBuf {
            count: 0,
            _pad: [0; 3],
            positions: [[0.0; 4]; MAX_REMOTE_PLAYERS],
        };
        let players_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("players"),
            contents: bytemuck::bytes_of(&players_init),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });

        let (output_tex, output_view) = create_output_texture(&device, width, height);
        let (beam_tex, beam_view) = create_beam_texture(&device, width, height);
        // resolve_tex shares the output usage (storage write + sampled + copy
        // src); history_tex is sampled + copy dst.
        let (resolve_tex, resolve_view) = create_output_texture(&device, width, height);
        let (history_tex, history_view) = create_history_texture(&device, width, height);

        // Bilinear filtering for the half-res → full-res blit upscale.
        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("blit sampler"),
            address_mode_u: wgpu::AddressMode::ClampToEdge,
            address_mode_v: wgpu::AddressMode::ClampToEdge,
            address_mode_w: wgpu::AddressMode::ClampToEdge,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::FilterMode::Nearest,
            ..Default::default()
        });

        // Half-res cloud target for the volumetric pass (reuses `sampler`). The
        // texture handle is dropped; the views keep it alive.
        let (_, cloud_sampled_view, cloud_storage_view) =
            create_cloud_texture(&device, width, height);
        // Ping-pong lighting G-buffer for the reprojection cache.
        let (light_out_tex, light_out_view) = create_lighting_texture(&device, width, height);
        let (light_hist_tex, light_hist_view) = create_lighting_texture(&device, width, height);
        // Deferred transparent records (#16).
        let transp_buf = create_transp_buf(&device, width, height);

        // -- compute pipeline --
        let compute_bgl = create_compute_bgl(&device);

        let compute_pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("compute pl"),
            bind_group_layouts: &[&compute_bgl],
            push_constant_ranges: &[],
        });
        let raymarch_src = format!(
            "{}\n{}\n{}",
            WORLD_CONSTS_WGSL,
            COMMON_WGSL,
            include_str!("../shaders/raymarch.wgsl")
        );
        let compute_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("raymarch shader"),
            source: wgpu::ShaderSource::Wgsl(raymarch_src.into()),
        });
        let compute_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("raymarch pipeline"),
            layout: Some(&compute_pl),
            module: &compute_shader,
            entry_point: Some("cs_main"),
            compilation_options: Default::default(),
            cache: None,
        });

        let compute_bg = make_compute_bg(
            &device, &compute_bgl, &camera_buf, &bricks_buf,
            &tile_mask_buf, &chunk_mask_buf, &palette_buf, &output_view, &beam_view,
            &tile_dirty_buf, &players_buf, &brick_uniform_buf, &tile_uniform_buf, &l4_mask_buf,
            &cloud_sampled_view, &sampler, &light_hist_view, &light_out_view, &transp_buf,
            &sprites_buf,
        );

        // -- deferred transparent pipeline (cs_transparent, same module + bgl) --
        let transparent_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("transparent pipeline"),
            layout: Some(&compute_pl),
            module: &compute_shader,
            entry_point: Some("cs_transparent"),
            compilation_options: Default::default(),
            cache: None,
        });

        // -- half-res cloud pipeline (cs_clouds, same shader module) --
        let cloud_bgl = create_cloud_bgl(&device);
        let cloud_pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("cloud pl"),
            bind_group_layouts: &[&cloud_bgl],
            push_constant_ranges: &[],
        });
        let cloud_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("cloud pipeline"),
            layout: Some(&cloud_pl),
            module: &compute_shader,
            entry_point: Some("cs_clouds"),
            compilation_options: Default::default(),
            cache: None,
        });
        let cloud_bg = make_cloud_bg(&device, &cloud_bgl, &camera_buf, &cloud_storage_view);

        // -- GPU-compute physics pipeline (#25): pull-only sand CA --
        let physics_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("physics bgl"),
            entries: &[
                bgl_storage(0, true),
                bgl_storage(1, false),
            ],
        });
        let physics_pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("physics pl"),
            bind_group_layouts: &[&physics_bgl],
            push_constant_ranges: &[],
        });
        let physics_src = format!("{}\n{}", WORLD_CONSTS_WGSL, include_str!("../shaders/physics.wgsl"));
        let physics_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("physics shader"),
            source: wgpu::ShaderSource::Wgsl(physics_src.into()),
        });
        let physics_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("physics pipeline"),
            layout: Some(&physics_pl),
            module: &physics_shader,
            entry_point: Some("cs_physics"),
            compilation_options: Default::default(),
            cache: None,
        });
        let physics_bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("physics bg"),
            layout: &physics_bgl,
            entries: &[
                wgpu::BindGroupEntry { binding: 0, resource: bricks_buf.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bricks_buf_b.as_entire_binding() },
            ],
        });
        // Opt-in (default off): GPU sand physics replaces the CPU CA. When on, the
        // CPU world.bricks is not kept in sync (raycast picking sees the pre-physics
        // state) — that CPU<->GPU sync is the next migration stage in the design doc.
        let gpu_physics_enabled = std::env::var("VOXELG_GPU_PHYSICS").is_ok();

        // -- beam pipeline (1/8-res coarse pre-pass) --
        let beam_bgl = create_beam_bgl(&device);
        let beam_pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("beam pl"),
            bind_group_layouts: &[&beam_bgl],
            push_constant_ranges: &[],
        });
        let beam_src = format!(
            "{}\n{}\n{}",
            WORLD_CONSTS_WGSL,
            COMMON_WGSL,
            include_str!("../shaders/beam.wgsl")
        );
        let beam_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("beam shader"),
            source: wgpu::ShaderSource::Wgsl(beam_src.into()),
        });
        let beam_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("beam pipeline"),
            layout: Some(&beam_pl),
            module: &beam_shader,
            entry_point: Some("cs_beam"),
            compilation_options: Default::default(),
            cache: None,
        });
        let beam_bg = make_beam_bg(&device, &beam_bgl, &camera_buf, &chunk_mask_buf, &beam_view);

        // -- blit pipeline --
        let blit_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("blit bgl"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
            ],
        });
        let blit_pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("blit pl"),
            bind_group_layouts: &[&blit_bgl],
            push_constant_ranges: &[],
        });
        let blit_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("blit shader"),
            source: wgpu::ShaderSource::Wgsl(include_str!("../shaders/blit.wgsl").into()),
        });
        let blit_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("blit pipeline"),
            layout: Some(&blit_pl),
            vertex: wgpu::VertexState {
                module: &blit_shader,
                entry_point: Some("vs_main"),
                buffers: &[],
                compilation_options: Default::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &blit_shader,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: surface_format,
                    blend: None,
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: Default::default(),
            }),
            primitive: wgpu::PrimitiveState::default(),
            depth_stencil: None,
            multisample: wgpu::MultisampleState::default(),
            multiview: None,
            cache: None,
        });

        // The blit now samples the TAA-resolved image, not the raw raymarch.
        let blit_bg = make_blit_bg(&device, &blit_bgl, &resolve_view, &sampler);

        // -- TAA resolve pipeline --
        let taa_bgl = create_taa_bgl(&device);
        let taa_pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("taa pl"),
            bind_group_layouts: &[&taa_bgl],
            push_constant_ranges: &[],
        });
        let taa_src = format!("{}\n{}\n{}", WORLD_CONSTS_WGSL, COMMON_WGSL, include_str!("../shaders/taa.wgsl"));
        let taa_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("taa shader"),
            source: wgpu::ShaderSource::Wgsl(taa_src.into()),
        });
        let taa_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("taa pipeline"),
            layout: Some(&taa_pl),
            module: &taa_shader,
            entry_point: Some("cs_taa"),
            compilation_options: Default::default(),
            cache: None,
        });
        let taa_bg = make_taa_bg(&device, &taa_bgl, &camera_buf, &output_view, &history_view, &resolve_view, &light_out_view);

        Ok(Self {
            device, queue, surface, config,
            size: (width, height),
            surface_size: (surface_w, surface_h),
            camera_buf, bricks_buf, tile_mask_buf, chunk_mask_buf, l4_mask_buf, palette_buf,
            sprites_buf,
            brick_uniform_buf, tile_uniform_buf,
            tile_dirty_buf, players_buf,
            output_tex, output_view, beam_tex, beam_view,
            history_tex, history_view, resolve_tex, resolve_view, sampler,
            beam_bgl, beam_pipeline, beam_bg,
            compute_bgl, compute_pipeline, compute_bg,
            transparent_pipeline, transp_buf,
            bricks_buf_b, physics_pipeline, physics_bg, gpu_physics: gpu_physics_enabled,
            cloud_bgl, cloud_pipeline, cloud_bg, cloud_sampled_view, cloud_storage_view,
            light_out_tex, light_out_view, light_hist_tex, light_hist_view,
            blit_bgl, blit_pipeline, blit_bg,
            taa_bgl, taa_pipeline, taa_bg,
            taa_reset: true,
            dirty_tiles_scratch: Vec::with_capacity(4096),
            dirty_chunks_scratch: Vec::with_capacity(512),
            dirty_words_scratch: Vec::with_capacity(4096),
            prev_cam: None,
            prev_world_origin: glam::IVec3::ZERO,
        })
    }

    pub fn resize(&mut self, w: u32, h: u32) {
        if w == 0 || h == 0 || (w, h) == self.surface_size { return; }
        self.surface_size = (w, h);
        let rw = (w / RENDER_SCALE).max(1);
        let rh = (h / RENDER_SCALE).max(1);
        self.size = (rw, rh);
        self.config.width = w;
        self.config.height = h;
        self.surface.configure(&self.device, &self.config);

        let (tex, view) = create_output_texture(&self.device, rw, rh);
        self.output_tex = tex;
        self.output_view = view;
        let (btex, bview) = create_beam_texture(&self.device, rw, rh);
        self.beam_tex = btex;
        self.beam_view = bview;
        let (rtex, rview) = create_output_texture(&self.device, rw, rh);
        self.resolve_tex = rtex;
        self.resolve_view = rview;
        let (htex, hview) = create_history_texture(&self.device, rw, rh);
        self.history_tex = htex;
        self.history_view = hview;
        let (_, csampled, cstorage) = create_cloud_texture(&self.device, rw, rh);
        self.cloud_sampled_view = csampled;
        self.cloud_storage_view = cstorage;
        let (lo_tex, lo_view) = create_lighting_texture(&self.device, rw, rh);
        self.light_out_tex = lo_tex;
        self.light_out_view = lo_view;
        let (lh_tex, lh_view) = create_lighting_texture(&self.device, rw, rh);
        self.light_hist_tex = lh_tex;
        self.light_hist_view = lh_view;
        self.transp_buf = create_transp_buf(&self.device, rw, rh);

        self.compute_bg = make_compute_bg(
            &self.device, &self.compute_bgl, &self.camera_buf, &self.bricks_buf,
            &self.tile_mask_buf, &self.chunk_mask_buf, &self.palette_buf, &self.output_view, &self.beam_view,
            &self.tile_dirty_buf, &self.players_buf, &self.brick_uniform_buf, &self.tile_uniform_buf,
            &self.l4_mask_buf, &self.cloud_sampled_view, &self.sampler,
            &self.light_hist_view, &self.light_out_view, &self.transp_buf,
            &self.sprites_buf,
        );
        self.cloud_bg = make_cloud_bg(
            &self.device, &self.cloud_bgl, &self.camera_buf, &self.cloud_storage_view,
        );
        self.beam_bg = make_beam_bg(
            &self.device, &self.beam_bgl, &self.camera_buf, &self.chunk_mask_buf, &self.beam_view,
        );
        self.taa_bg = make_taa_bg(
            &self.device, &self.taa_bgl, &self.camera_buf, &self.output_view, &self.history_view, &self.resolve_view,
            &self.light_out_view,
        );
        self.blit_bg = make_blit_bg(&self.device, &self.blit_bgl, &self.resolve_view, &self.sampler);
        // History texture is newly (re)created and uninitialised — skip the TAA
        // blend next frame so it isn't read as garbage.
        self.taa_reset = true;
    }

    /// Returns whether the TAA history was just (re)created, clearing the flag.
    /// The caller forces taa_blend = 0 for that one frame.
    pub fn take_taa_reset(&mut self) -> bool {
        std::mem::take(&mut self.taa_reset)
    }

    pub fn upload_world(&mut self, world: &mut World) {
        // Whole-world refresh (first frame / explicit invalidate only). A chunk
        // cross must NEVER reach this path — it goes through the incremental
        // path below, which is why crossing a boundary no longer re-DMAs ~75 MB.
        if world.all_dirty {
            self.queue.write_buffer(&self.bricks_buf, 0, bytemuck::cast_slice(&world.bricks));
            self.queue.write_buffer(&self.tile_mask_buf, 0, bytemuck::cast_slice(&world.tile_mask));
            self.queue.write_buffer(&self.chunk_mask_buf, 0, bytemuck::cast_slice(&world.chunk_mask));
            self.queue.write_buffer(&self.l4_mask_buf, 0, bytemuck::cast_slice(&world.l4_mask));
            let bu = pack_u8_to_u32(&world.brick_uniform);
            let tu = pack_u8_to_u32(&world.tile_uniform);
            self.queue.write_buffer(&self.brick_uniform_buf, 0, bytemuck::cast_slice(&bu));
            self.queue.write_buffer(&self.tile_uniform_buf, 0, bytemuck::cast_slice(&tu));
            world.all_dirty = false;
            world.dirty_bricks.clear();
            return;
        }
        if world.dirty_bricks.is_empty() { return; }
        world.dirty_bricks.sort_unstable();
        world.dirty_bricks.dedup();

        // 1. Brick voxel data — coalesced contiguous spans (one DMA per run).
        let stride = std::mem::size_of::<Brick>() as u64;
        upload_spans(&world.dirty_bricks, |s, e| {
            let slice = &world.bricks[s as usize..=e as usize];
            self.queue.write_buffer(&self.bricks_buf, s as u64 * stride, bytemuck::cast_slice(slice));
        });

        // 2. Per-brick uniform-material table (packed 4 bricks / u32 word).
        //    Re-pack and upload only the words touched by dirty bricks — this
        //    is the table the DDA's uniform-skip reads, and it was previously
        //    NEVER refreshed incrementally, so streamed chunks rendered with
        //    stale skip data.
        upload_words_for(
            &mut self.dirty_words_scratch, &world.dirty_bricks, &world.brick_uniform,
            &self.queue, &self.brick_uniform_buf,
        );

        // 3. Tiles touched by the dirty bricks → tile_mask (u64) + tile_uniform.
        self.dirty_tiles_scratch.clear();
        for &b in &world.dirty_bricks {
            let (bx, by, bz) = brick_coords(b);
            self.dirty_tiles_scratch.push(tile_idx(bx / 4, by / 4, bz / 4));
        }
        self.dirty_tiles_scratch.sort_unstable();
        self.dirty_tiles_scratch.dedup();
        upload_spans(&self.dirty_tiles_scratch, |s, e| {
            let slice = &world.tile_mask[s as usize..=e as usize];
            self.queue.write_buffer(&self.tile_mask_buf, s as u64 * 8, bytemuck::cast_slice(slice));
        });
        upload_words_for(
            &mut self.dirty_words_scratch, &self.dirty_tiles_scratch, &world.tile_uniform,
            &self.queue, &self.tile_uniform_buf,
        );

        // 4. Chunks touched by those tiles → chunk_mask (u64).
        upload_chunks_for_tiles(
            &mut self.dirty_chunks_scratch, &self.dirty_tiles_scratch, &world.chunk_mask,
            &self.queue, &self.chunk_mask_buf,
        );
        // L4 mask is only a handful of u64s — if any chunk changed, just push
        // the whole thing.
        if !self.dirty_chunks_scratch.is_empty() {
            self.queue.write_buffer(&self.l4_mask_buf, 0, bytemuck::cast_slice(&world.l4_mask));
        }

        world.dirty_bricks.clear();
    }

    /// Upload mask-only clears (slots recycled by shift_origin) — just the
    /// touched tile_mask / tile_uniform + their chunk_mask + L4, no brick data.
    /// This is what makes a recycled slot render as sky immediately and cheaply.
    pub fn upload_mask_clears(&mut self, world: &mut World) {
        if world.mask_dirty_tiles.is_empty() {
            return;
        }
        world.mask_dirty_tiles.sort_unstable();
        world.mask_dirty_tiles.dedup();
        upload_spans(&world.mask_dirty_tiles, |s, e| {
            let slice = &world.tile_mask[s as usize..=e as usize];
            self.queue.write_buffer(&self.tile_mask_buf, s as u64 * 8, bytemuck::cast_slice(slice));
        });
        upload_words_for(
            &mut self.dirty_words_scratch, &world.mask_dirty_tiles, &world.tile_uniform,
            &self.queue, &self.tile_uniform_buf,
        );
        upload_chunks_for_tiles(
            &mut self.dirty_chunks_scratch, &world.mask_dirty_tiles, &world.chunk_mask,
            &self.queue, &self.chunk_mask_buf,
        );
        self.queue.write_buffer(&self.l4_mask_buf, 0, bytemuck::cast_slice(&world.l4_mask));
        world.mask_dirty_tiles.clear();
    }

    pub fn upload_tile_dirty(&self, mask: &[u32]) {
        if mask.is_empty() { return; }
        self.queue.write_buffer(&self.tile_dirty_buf, 0, bytemuck::cast_slice(mask));
    }

    pub fn upload_players(&self, positions: &[(glam::Vec3, u32)]) {
        let mut data = PlayersBuf {
            count: 0,
            _pad: [0; 3],
            positions: [[0.0; 4]; MAX_REMOTE_PLAYERS],
        };
        let n = positions.len().min(MAX_REMOTE_PLAYERS);
        data.count = n as u32;
        for (i, (p, id)) in positions.iter().take(n).enumerate() {
            data.positions[i] = [p.x, p.y, p.z, *id as f32];
        }
        self.queue.write_buffer(&self.players_buf, 0, bytemuck::bytes_of(&data));
    }

    pub fn update_camera(
        &mut self,
        camera: &Camera,
        time: f32,
        world_origin_voxel: glam::IVec3,
        jitter: [f32; 2],
        taa_blend: f32,
    ) {
        let mut u = CameraUniform::from_camera(
            camera, self.size.0, self.size.1, time, world_origin_voxel, jitter, taa_blend,
        );
        // Lighting + colour-history reprojection runs only while ACCUMULATING
        // (taa_blend > 0 = static camera), with a previous frame and an unchanged
        // world origin. On motion (taa_blend == 0) it's disabled so we trace fresh
        // — motion reprojection warped the image and the engine has the headroom.
        let reproject_ok = taa_blend > 0.0 && self.prev_world_origin == world_origin_voxel;
        match &self.prev_cam {
            Some(prev) => u.set_prev_camera(prev, reproject_ok),
            None => u.set_prev_camera(camera, false),
        }
        self.queue.write_buffer(&self.camera_buf, 0, bytemuck::bytes_of(&u));
        self.prev_cam = Some(camera.clone());
        self.prev_world_origin = world_origin_voxel;
    }

    /// Run one GPU-compute physics step (#25): dispatch the pull-only sand CA
    /// (bricks_buf → bricks_buf_b) then copy the result back so the render path
    /// (which reads bricks_buf) sees it. Opt-in via `gpu_physics`. NOTE: the CPU
    /// `World.bricks` is not updated here — raycast picking sees the pre-physics
    /// state until the design doc's CPU<->GPU sync stage lands.
    pub fn run_gpu_physics(&self) {
        let total = crate::voxel::WORLD_BRICKS_TOTAL;
        let mut enc = self.device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
            label: Some("gpu physics"),
        });
        {
            let mut cp = enc.begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: Some("gpu physics"),
                timestamp_writes: None,
            });
            cp.set_pipeline(&self.physics_pipeline);
            cp.set_bind_group(0, &self.physics_bg, &[]);
            cp.dispatch_workgroups((total + 63) / 64, 1, 1);
        }
        enc.copy_buffer_to_buffer(&self.bricks_buf_b, 0, &self.bricks_buf, 0, self.bricks_buf.size());
        self.queue.submit(std::iter::once(enc.finish()));
    }

    pub fn render(&mut self, any_dirty: bool) -> Result<(), wgpu::SurfaceError> {
        let frame = self.surface.get_current_texture()?;
        let frame_view = frame
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        let mut encoder = self.device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
            label: Some("frame"),
        });

        // Temporal-differential: if no tile is dirty, we still blit (so the
        // swapchain stays in sync), but skip the beam + raymarch compute
        // passes entirely. The output_tex from the prior frame is preserved.
        if any_dirty {
            // ---- half-res cloud pre-pass ----
            {
                let mut cp = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                    label: Some("clouds"),
                    timestamp_writes: None,
                });
                cp.set_pipeline(&self.cloud_pipeline);
                cp.set_bind_group(0, &self.cloud_bg, &[]);
                let hx = ((self.size.0 + 1) / 2 + 7) / 8;
                let hy = ((self.size.1 + 1) / 2 + 7) / 8;
                cp.dispatch_workgroups(hx, hy, 1);
            }
            // ---- beam pre-pass at 1/8 resolution ----
            {
                let mut cp = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                    label: Some("beam"),
                    timestamp_writes: None,
                });
                cp.set_pipeline(&self.beam_pipeline);
                cp.set_bind_group(0, &self.beam_bg, &[]);
                let bx = ((self.size.0 + 7) / 8 + 7) / 8;
                let by = ((self.size.1 + 7) / 8 + 7) / 8;
                cp.dispatch_workgroups(bx, by, 1);
            }
            // ---- main raymarch (skips clean tiles in-shader) ----
            {
                let mut cp = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                    label: Some("raymarch"),
                    timestamp_writes: None,
                });
                cp.set_pipeline(&self.compute_pipeline);
                cp.set_bind_group(0, &self.compute_bg, &[]);
                let gx = (self.size.0 + 7) / 8;
                let gy = (self.size.1 + 7) / 8;
                cp.dispatch_workgroups(gx, gy, 1);
            }
            // ---- deferred transparent pass (#16): shade water/glass pixels ----
            {
                let mut cp = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                    label: Some("transparent"),
                    timestamp_writes: None,
                });
                cp.set_pipeline(&self.transparent_pipeline);
                cp.set_bind_group(0, &self.compute_bg, &[]);
                let gx = (self.size.0 + 7) / 8;
                let gy = (self.size.1 + 7) / 8;
                cp.dispatch_workgroups(gx, gy, 1);
            }
            // ---- TAA resolve: raymarch output + history -> resolve ----
            {
                let mut cp = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                    label: Some("taa"),
                    timestamp_writes: None,
                });
                cp.set_pipeline(&self.taa_pipeline);
                cp.set_bind_group(0, &self.taa_bg, &[]);
                let gx = (self.size.0 + 7) / 8;
                let gy = (self.size.1 + 7) / 8;
                cp.dispatch_workgroups(gx, gy, 1);
            }
            // Feed this frame's resolved image back as next frame's history.
            encoder.copy_texture_to_texture(
                wgpu::ImageCopyTexture {
                    texture: &self.resolve_tex,
                    mip_level: 0,
                    origin: wgpu::Origin3d::ZERO,
                    aspect: wgpu::TextureAspect::All,
                },
                wgpu::ImageCopyTexture {
                    texture: &self.history_tex,
                    mip_level: 0,
                    origin: wgpu::Origin3d::ZERO,
                    aspect: wgpu::TextureAspect::All,
                },
                wgpu::Extent3d { width: self.size.0, height: self.size.1, depth_or_array_layers: 1 },
            );
            // Ping-pong the lighting G-buffer: this frame's output becomes next
            // frame's reprojection source.
            encoder.copy_texture_to_texture(
                wgpu::ImageCopyTexture {
                    texture: &self.light_out_tex,
                    mip_level: 0,
                    origin: wgpu::Origin3d::ZERO,
                    aspect: wgpu::TextureAspect::All,
                },
                wgpu::ImageCopyTexture {
                    texture: &self.light_hist_tex,
                    mip_level: 0,
                    origin: wgpu::Origin3d::ZERO,
                    aspect: wgpu::TextureAspect::All,
                },
                wgpu::Extent3d { width: self.size.0, height: self.size.1, depth_or_array_layers: 1 },
            );
        }

        {
            let mut rp = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("blit"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &frame_view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: 0.0, g: 0.0, b: 0.0, a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
                occlusion_query_set: None,
            });
            rp.set_pipeline(&self.blit_pipeline);
            rp.set_bind_group(0, &self.blit_bg, &[]);
            rp.draw(0..3, 0..1);
        }

        self.queue.submit(std::iter::once(encoder.finish()));
        frame.present();
        Ok(())
    }
}

fn create_output_texture(device: &wgpu::Device, w: u32, h: u32) -> (wgpu::Texture, wgpu::TextureView) {
    let tex = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("output"),
        size: wgpu::Extent3d { width: w, height: h, depth_or_array_layers: 1 },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8Unorm,
        // COPY_SRC lets the headless render test read the frame back for
        // automated validation; harmless for the windowed path.
        usage: wgpu::TextureUsages::STORAGE_BINDING
            | wgpu::TextureUsages::TEXTURE_BINDING
            | wgpu::TextureUsages::COPY_SRC,
        view_formats: &[],
    });
    let view = tex.create_view(&wgpu::TextureViewDescriptor::default());
    (tex, view)
}

fn create_history_texture(device: &wgpu::Device, w: u32, h: u32) -> (wgpu::Texture, wgpu::TextureView) {
    let tex = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("taa history"),
        size: wgpu::Extent3d { width: w, height: h, depth_or_array_layers: 1 },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8Unorm,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    });
    let view = tex.create_view(&wgpu::TextureViewDescriptor::default());
    (tex, view)
}

fn create_taa_bgl(device: &wgpu::Device) -> wgpu::BindGroupLayout {
    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some("taa bgl"),
        entries: &[
            bgl_uniform(0),
            bgl_tex(1, false), // current (raymarch output)
            bgl_tex(2, false), // history
            bgl_storage_tex(3, wgpu::TextureFormat::Rgba8Unorm), // resolve out
            bgl_tex(4, false), // hit G-buffer (reprojection motion vectors)
        ],
    })
}

fn make_taa_bg(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    camera_buf: &wgpu::Buffer,
    current_view: &wgpu::TextureView,
    history_view: &wgpu::TextureView,
    resolve_view: &wgpu::TextureView,
    gbuffer_view: &wgpu::TextureView,
) -> wgpu::BindGroup {
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("taa bg"),
        layout,
        entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: camera_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 1, resource: wgpu::BindingResource::TextureView(current_view) },
            wgpu::BindGroupEntry { binding: 2, resource: wgpu::BindingResource::TextureView(history_view) },
            wgpu::BindGroupEntry { binding: 3, resource: wgpu::BindingResource::TextureView(resolve_view) },
            wgpu::BindGroupEntry { binding: 4, resource: wgpu::BindingResource::TextureView(gbuffer_view) },
        ],
    })
}

fn create_beam_texture(device: &wgpu::Device, w: u32, h: u32) -> (wgpu::Texture, wgpu::TextureView) {
    let bw = ((w + 7) / 8).max(1);
    let bh = ((h + 7) / 8).max(1);
    let tex = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("beam"),
        size: wgpu::Extent3d { width: bw, height: bh, depth_or_array_layers: 1 },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::R32Float,
        usage: wgpu::TextureUsages::STORAGE_BINDING | wgpu::TextureUsages::TEXTURE_BINDING,
        view_formats: &[],
    });
    let view = tex.create_view(&wgpu::TextureViewDescriptor::default());
    (tex, view)
}

/// Compute-pass bind-group layout. Single definition shared by the renderer and
/// the headless render test so the two can never drift. Binding order matches
/// `make_compute_bg` and the `@group(0) @binding(N)` declarations in
/// shaders/raymarch.wgsl.
// Shared BindGroupLayoutEntry builders for the COMPUTE-stage layouts, so each
// create_*_bgl below lists its bindings instead of repeating the descriptor
// boilerplate. (create_compute_bgl previously carried two of these as locals.)
fn bgl_uniform(binding: u32) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::Buffer {
            ty: wgpu::BufferBindingType::Uniform,
            has_dynamic_offset: false,
            min_binding_size: None,
        },
        count: None,
    }
}

fn bgl_storage(binding: u32, read_only: bool) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::Buffer {
            ty: wgpu::BufferBindingType::Storage { read_only },
            has_dynamic_offset: false,
            min_binding_size: None,
        },
        count: None,
    }
}

fn bgl_tex(binding: u32, filterable: bool) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::Texture {
            sample_type: wgpu::TextureSampleType::Float { filterable },
            view_dimension: wgpu::TextureViewDimension::D2,
            multisampled: false,
        },
        count: None,
    }
}

fn bgl_storage_tex(binding: u32, format: wgpu::TextureFormat) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::StorageTexture {
            access: wgpu::StorageTextureAccess::WriteOnly,
            format,
            view_dimension: wgpu::TextureViewDimension::D2,
        },
        count: None,
    }
}

fn bgl_sampler(binding: u32) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
        count: None,
    }
}

fn create_compute_bgl(device: &wgpu::Device) -> wgpu::BindGroupLayout {
    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some("compute bgl"),
        entries: &[
            bgl_uniform(0),       // camera
            bgl_storage(1, true), // bricks
            bgl_storage(2, true), // tile_mask
            bgl_storage(3, true), // chunk_mask
            bgl_uniform(4),       // palette
            bgl_storage_tex(5, wgpu::TextureFormat::Rgba8Unorm), // output
            bgl_tex(6, false),    // beam depth texture
            bgl_storage(7, true),  // tile_dirty
            bgl_storage(8, true),  // players
            bgl_storage(9, true),  // brick_uniform
            bgl_storage(10, true), // tile_uniform
            bgl_storage(11, true), // l4_mask (coarsest pyramid level)
            bgl_tex(12, true),     // half-res cloud texture (bilinear upsample)
            bgl_sampler(13),       // cloud sampler (filtering)
            bgl_tex(15, false),    // light_in: previous-frame lighting G-buffer
            bgl_storage_tex(16, wgpu::TextureFormat::Rgba32Float), // light_out
            bgl_storage(17, false), // transp_buf: deferred transparent records (rw)
            bgl_storage(18, true),  // foliage sprites (2bpp authored cutout art)
        ],
    })
}

fn create_transp_buf(device: &wgpu::Device, w: u32, h: u32) -> wgpu::Buffer {
    device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("transp records"),
        size: (w.max(1) * h.max(1)) as u64 * 16, // vec4<f32> per pixel
        usage: wgpu::BufferUsages::STORAGE,
        mapped_at_creation: false,
    })
}

// Full-res lighting G-buffer for the reprojected shadow/AO cache (ping-ponged).
// Rgba32Float: xyz = hit pos rel world_origin, w = packed shadow/AO.
fn create_lighting_texture(
    device: &wgpu::Device, w: u32, h: u32,
) -> (wgpu::Texture, wgpu::TextureView) {
    let tex = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("lighting gbuffer"),
        size: wgpu::Extent3d { width: w.max(1), height: h.max(1), depth_or_array_layers: 1 },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba32Float,
        usage: wgpu::TextureUsages::STORAGE_BINDING
            | wgpu::TextureUsages::TEXTURE_BINDING
            | wgpu::TextureUsages::COPY_SRC
            | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    });
    let view = tex.create_view(&wgpu::TextureViewDescriptor::default());
    (tex, view)
}

// cs_clouds writes the half-res clouds; its own (tiny) layout: camera + the
// cloud storage texture. Separate from compute_bgl so the cloud texture is
// never bound as storage-write and sampled in the same bind group.
fn create_cloud_bgl(device: &wgpu::Device) -> wgpu::BindGroupLayout {
    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some("cloud bgl"),
        entries: &[
            bgl_uniform(0), // camera
            bgl_storage_tex(14, wgpu::TextureFormat::Rgba16Float), // cloud_out
        ],
    })
}

// Half-res cloud texture: (texture, sampled_view, storage_view). Rgba16Float to
// keep HDR cloud/scatter values.
fn create_cloud_texture(
    device: &wgpu::Device, w: u32, h: u32,
) -> (wgpu::Texture, wgpu::TextureView, wgpu::TextureView) {
    let hw = (w + 1) / 2;
    let hh = (h + 1) / 2;
    let tex = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("cloud tex (half-res)"),
        size: wgpu::Extent3d { width: hw.max(1), height: hh.max(1), depth_or_array_layers: 1 },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba16Float,
        usage: wgpu::TextureUsages::STORAGE_BINDING | wgpu::TextureUsages::TEXTURE_BINDING,
        view_formats: &[],
    });
    let sampled = tex.create_view(&wgpu::TextureViewDescriptor::default());
    let storage = tex.create_view(&wgpu::TextureViewDescriptor::default());
    (tex, sampled, storage)
}

fn create_beam_bgl(device: &wgpu::Device) -> wgpu::BindGroupLayout {
    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some("beam bgl"),
        entries: &[
            bgl_uniform(0),
            bgl_storage(1, true),
            bgl_storage_tex(2, wgpu::TextureFormat::R32Float),
        ],
    })
}

fn make_compute_bg(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    camera_buf: &wgpu::Buffer,
    bricks_buf: &wgpu::Buffer,
    tile_mask_buf: &wgpu::Buffer,
    chunk_mask_buf: &wgpu::Buffer,
    palette_buf: &wgpu::Buffer,
    output_view: &wgpu::TextureView,
    beam_view: &wgpu::TextureView,
    tile_dirty_buf: &wgpu::Buffer,
    players_buf: &wgpu::Buffer,
    brick_uniform_buf: &wgpu::Buffer,
    tile_uniform_buf: &wgpu::Buffer,
    l4_mask_buf: &wgpu::Buffer,
    cloud_sampled_view: &wgpu::TextureView,
    cloud_sampler: &wgpu::Sampler,
    light_in_view: &wgpu::TextureView,
    light_out_view: &wgpu::TextureView,
    transp_buf: &wgpu::Buffer,
    sprites_buf: &wgpu::Buffer,
) -> wgpu::BindGroup {
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("compute bg"),
        layout,
        entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: camera_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 1, resource: bricks_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 2, resource: tile_mask_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 3, resource: chunk_mask_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 4, resource: palette_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 5, resource: wgpu::BindingResource::TextureView(output_view) },
            wgpu::BindGroupEntry { binding: 6, resource: wgpu::BindingResource::TextureView(beam_view) },
            wgpu::BindGroupEntry { binding: 7, resource: tile_dirty_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 8, resource: players_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 9, resource: brick_uniform_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 10, resource: tile_uniform_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 11, resource: l4_mask_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 12, resource: wgpu::BindingResource::TextureView(cloud_sampled_view) },
            wgpu::BindGroupEntry { binding: 13, resource: wgpu::BindingResource::Sampler(cloud_sampler) },
            wgpu::BindGroupEntry { binding: 15, resource: wgpu::BindingResource::TextureView(light_in_view) },
            wgpu::BindGroupEntry { binding: 16, resource: wgpu::BindingResource::TextureView(light_out_view) },
            wgpu::BindGroupEntry { binding: 17, resource: transp_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 18, resource: sprites_buf.as_entire_binding() },
        ],
    })
}

fn make_cloud_bg(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    camera_buf: &wgpu::Buffer,
    cloud_storage_view: &wgpu::TextureView,
) -> wgpu::BindGroup {
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("cloud bg"),
        layout,
        entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: camera_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 14, resource: wgpu::BindingResource::TextureView(cloud_storage_view) },
        ],
    })
}

fn make_beam_bg(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    camera_buf: &wgpu::Buffer,
    chunk_mask_buf: &wgpu::Buffer,
    beam_view: &wgpu::TextureView,
) -> wgpu::BindGroup {
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("beam bg"),
        layout,
        entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: camera_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 1, resource: chunk_mask_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 2, resource: wgpu::BindingResource::TextureView(beam_view) },
        ],
    })
}

fn make_blit_bg(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    view: &wgpu::TextureView,
    sampler: &wgpu::Sampler,
) -> wgpu::BindGroup {
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("blit bg"),
        layout,
        entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: wgpu::BindingResource::TextureView(view) },
            wgpu::BindGroupEntry { binding: 1, resource: wgpu::BindingResource::Sampler(sampler) },
        ],
    })
}

#[cfg(test)]
mod shader_tests {
    //! Headless WGSL parse + validation. Catches shader regressions in
    //! `cargo test` without a window or a GPU — the shaders are otherwise only
    //! validated at runtime when the pipelines are created. The const-prepending
    //! mirrors exactly what `Renderer::new` does, so the validated source is the
    //! source that actually runs.
    use super::{WORLD_CONSTS_WGSL, COMMON_WGSL};

    fn validate(name: &str, src: &str) {
        let module = naga::front::wgsl::parse_str(src)
            .unwrap_or_else(|e| panic!("WGSL parse error in {name}:\n{}", e.emit_to_string(src)));
        let mut v = naga::valid::Validator::new(
            naga::valid::ValidationFlags::all(),
            naga::valid::Capabilities::all(),
        );
        v.validate(&module)
            .unwrap_or_else(|e| panic!("WGSL validation error in {name}: {e:?}"));
    }

    #[test]
    fn raymarch_wgsl_valid() {
        let src = format!("{}\n{}\n{}", WORLD_CONSTS_WGSL, COMMON_WGSL, include_str!("../shaders/raymarch.wgsl"));
        validate("raymarch.wgsl", &src);
    }

    #[test]
    fn beam_wgsl_valid() {
        let src = format!("{}\n{}\n{}", WORLD_CONSTS_WGSL, COMMON_WGSL, include_str!("../shaders/beam.wgsl"));
        validate("beam.wgsl", &src);
    }

    #[test]
    fn blit_wgsl_valid() {
        validate("blit.wgsl", include_str!("../shaders/blit.wgsl"));
    }

    #[test]
    fn taa_wgsl_valid() {
        let src = format!("{}\n{}\n{}", WORLD_CONSTS_WGSL, COMMON_WGSL, include_str!("../shaders/taa.wgsl"));
        validate("taa.wgsl", &src);
    }

    #[test]
    fn physics_wgsl_valid() {
        let src = format!("{}\n{}", WORLD_CONSTS_WGSL, include_str!("../shaders/physics.wgsl"));
        validate("physics.wgsl", &src);
    }
}

#[cfg(test)]
mod gpu_render_tests {
    //! Headless offscreen render + pixel readback. Runs the REAL raymarch
    //! pipeline (reusing the renderer's own bind-group / buffer helpers) on a
    //! windowless device, then reads the frame back and asserts the scene has
    //! both sky and terrain. This is the automated regression net for shader
    //! changes (the DDA rewrite, LOD, etc.) where there's no display to look at.
    //! Skips cleanly when no GPU adapter is available (e.g. headless CI).
    use super::*;
    use crate::camera::{Camera, CameraUniform};
    use crate::voxel::World;
    use wgpu::util::DeviceExt;

    fn headless_device() -> Option<(wgpu::Device, wgpu::Queue)> {
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            backends: wgpu::Backends::PRIMARY,
            ..Default::default()
        });
        let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::HighPerformance,
            compatible_surface: None,
            force_fallback_adapter: false,
        }))?;
        let (device, queue) = pollster::block_on(adapter.request_device(
            &wgpu::DeviceDescriptor {
                label: Some("headless test device"),
                required_features: wgpu::Features::empty(),
                required_limits: wgpu::Limits {
                    max_storage_buffer_binding_size: 256 << 20,
                    max_storage_buffers_per_shader_stage: 12,
                    ..wgpu::Limits::default()
                },
                memory_hints: wgpu::MemoryHints::Performance,
            },
            None,
        ))
        .ok()?;
        Some((device, queue))
    }

    fn storage(device: &wgpu::Device, label: &str, bytes: &[u8]) -> wgpu::Buffer {
        device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some(label),
            contents: bytes,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        })
    }

    /// Render the default world from a camera placed high above the loaded
    /// window (optionally streamed far from spawn to exercise origin-rebasing
    /// precision) and read the frame back. Returns per-pixel luma
    /// (min, max, mean), or None if no GPU.
    pub(super) fn render_luma_stats_at(origin_chunk: glam::IVec2) -> Option<(f32, f32, f32)> {
        let mut world = World::new();
        world.fill_demo_terrain();
        if origin_chunk != glam::IVec2::ZERO {
            world.shift_origin(origin_chunk);
            world.process_pending_gen_blocking();
        }
        let wo = world.world_origin_voxel();

        // Camera high above the centre of the loaded window, tilted toward the
        // horizon so the frame contains terrain (lower) and sky (upper) — never
        // inside a voxel.
        let mut cam = Camera::new();
        cam.pos.x = wo.x as f32 + 256.0;
        cam.pos.z = wo.z as f32 + 256.0;
        let s = crate::voxel::sample_terrain(cam.pos.x, cam.pos.z, world.seed);
        cam.pos.y = s.h as f32 + 30.0;
        cam.pitch = -0.35;

        let rgba = render_rgba(&world, &cam, 320, 200)?;
        let mut min = 1.0f32;
        let mut max = 0.0f32;
        let mut sum = 0.0f64;
        let n = rgba.len() / 4;
        for px in rgba.chunks_exact(4) {
            let r = px[0] as f32 / 255.0;
            let g = px[1] as f32 / 255.0;
            let b = px[2] as f32 / 255.0;
            let luma = 0.299 * r + 0.587 * g + 0.114 * b;
            min = min.min(luma);
            max = max.max(luma);
            sum += luma as f64;
        }
        Some((min, max, (sum / n as f64) as f32))
    }

    /// Render one 320x200 frame of `world` from `cam` through the full
    /// pipeline (half-res clouds, cs_main, a reprojection-validating second
    /// frame, deferred transparent) and read the RGBA bytes back.
    fn render_rgba(world: &World, cam: &Camera, w: u32, h: u32) -> Option<Vec<u8>> {
        let (device, queue) = headless_device()?;
        let wo = world.world_origin_voxel();
        let cu = CameraUniform::from_camera(cam, w, h, 0.0, wo, [0.0, 0.0], 0.0);

        let camera_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("camera"),
            contents: bytemuck::bytes_of(&cu),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });
        let bricks_buf = storage(&device, "bricks", bytemuck::cast_slice(&world.bricks));
        let tile_mask_buf = storage(&device, "tile_mask", bytemuck::cast_slice(&world.tile_mask));
        let chunk_mask_buf = storage(&device, "chunk_mask", bytemuck::cast_slice(&world.chunk_mask));
        let l4_mask_buf = storage(&device, "l4_mask", bytemuck::cast_slice(&world.l4_mask));
        let brick_uniform_buf = storage(&device, "brick_uniform", bytemuck::cast_slice(&pack_u8_to_u32(&world.brick_uniform)));
        let tile_uniform_buf = storage(&device, "tile_uniform", bytemuck::cast_slice(&pack_u8_to_u32(&world.tile_uniform)));
        let palette = default_palette();
        let palette_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("palette"),
            contents: bytemuck::cast_slice(&palette),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });
        // All tiles dirty → render every pixel.
        let tiles_w = (w + 7) / 8;
        let tiles_h = (h + 7) / 8;
        let words = ((tiles_w * tiles_h) as usize + 31) / 32;
        let tile_dirty_buf = storage(&device, "tile_dirty", bytemuck::cast_slice(&vec![u32::MAX; words]));
        let players_buf = storage(&device, "players", &vec![0u8; 16 + MAX_REMOTE_PLAYERS * 16]);

        let (_otex, output_view) = create_output_texture(&device, w, h);
        let output_tex = _otex;
        let (_btex, beam_view) = create_beam_texture(&device, w, h);
        let (_ctex, cloud_sampled_view, cloud_storage_view) = create_cloud_texture(&device, w, h);
        let cloud_sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("test cloud sampler"),
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            ..Default::default()
        });

        let bgl = create_compute_bgl(&device);
        let (_ltex, light_in_view) = create_lighting_texture(&device, w, h);
        let (_ltex2, light_out_view) = create_lighting_texture(&device, w, h);
        let transp_buf = create_transp_buf(&device, w, h);
        let sprites_buf = storage(&device, "sprites", bytemuck::cast_slice(&crate::sprites::encoded()));
        let bg = make_compute_bg(
            &device, &bgl, &camera_buf, &bricks_buf, &tile_mask_buf, &chunk_mask_buf,
            &palette_buf, &output_view, &beam_view, &tile_dirty_buf, &players_buf,
            &brick_uniform_buf, &tile_uniform_buf, &l4_mask_buf,
            &cloud_sampled_view, &cloud_sampler, &light_in_view, &light_out_view, &transp_buf,
            &sprites_buf,
        );
        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("test pl"),
            bind_group_layouts: &[&bgl],
            push_constant_ranges: &[],
        });
        let src = format!("{}\n{}\n{}", WORLD_CONSTS_WGSL, COMMON_WGSL, include_str!("../shaders/raymarch.wgsl"));
        let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("test raymarch"),
            source: wgpu::ShaderSource::Wgsl(src.into()),
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("test raymarch pipeline"),
            layout: Some(&pl),
            module: &module,
            entry_point: Some("cs_main"),
            compilation_options: Default::default(),
            cache: None,
        });
        // Deferred transparent pass (validates cs_transparent end to end).
        let transparent_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("test transparent pipeline"),
            layout: Some(&pl),
            module: &module,
            entry_point: Some("cs_transparent"),
            compilation_options: Default::default(),
            cache: None,
        });
        // Half-res cloud pre-pass (validates cs_clouds end to end).
        let cloud_bgl = create_cloud_bgl(&device);
        let cloud_pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("test cloud pl"),
            bind_group_layouts: &[&cloud_bgl],
            push_constant_ranges: &[],
        });
        let cloud_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("test cloud pipeline"),
            layout: Some(&cloud_pl),
            module: &module,
            entry_point: Some("cs_clouds"),
            compilation_options: Default::default(),
            cache: None,
        });
        let cloud_bg = make_cloud_bg(&device, &cloud_bgl, &camera_buf, &cloud_storage_view);

        // Readback buffer (bytes_per_row already 256-aligned for w=320).
        let bpr = w * 4;
        let readback = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("readback"),
            size: (bpr * h) as u64,
            usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
            mapped_at_creation: false,
        });

        // Frame 1: reproject OFF (cu has reproject_lighting=0), builds the
        // lighting G-buffer in light_out.
        let mut enc = device.create_command_encoder(&Default::default());
        {
            let mut cp = enc.begin_compute_pass(&Default::default());
            cp.set_pipeline(&cloud_pipeline);
            cp.set_bind_group(0, &cloud_bg, &[]);
            cp.dispatch_workgroups(((w + 1) / 2 + 7) / 8, ((h + 1) / 2 + 7) / 8, 1);
        }
        {
            let mut cp = enc.begin_compute_pass(&Default::default());
            cp.set_pipeline(&pipeline);
            cp.set_bind_group(0, &bg, &[]);
            cp.dispatch_workgroups((w + 7) / 8, (h + 7) / 8, 1);
        }
        // Ping-pong: frame 1's G-buffer (light_out) becomes frame 2's light_in.
        enc.copy_texture_to_texture(
            wgpu::ImageCopyTexture { texture: &_ltex2, mip_level: 0, origin: wgpu::Origin3d::ZERO, aspect: wgpu::TextureAspect::All },
            wgpu::ImageCopyTexture { texture: &_ltex, mip_level: 0, origin: wgpu::Origin3d::ZERO, aspect: wgpu::TextureAspect::All },
            wgpu::Extent3d { width: w, height: h, depth_or_array_layers: 1 },
        );
        queue.submit(std::iter::once(enc.finish()));
        // Frame 2: reproject ON with the same camera as prev → every pixel should
        // reproject to itself, match position, and reuse frame 1's shadow/AO.
        // A static camera means the result must equal frame 1 (validates the
        // reuse path: reprojection math, position match, unpack).
        let mut cu2 = cu;
        cu2.set_prev_camera(&cam, true);
        queue.write_buffer(&camera_buf, 0, bytemuck::bytes_of(&cu2));
        let mut enc = device.create_command_encoder(&Default::default());
        {
            let mut cp = enc.begin_compute_pass(&Default::default());
            cp.set_pipeline(&cloud_pipeline);
            cp.set_bind_group(0, &cloud_bg, &[]);
            cp.dispatch_workgroups(((w + 1) / 2 + 7) / 8, ((h + 1) / 2 + 7) / 8, 1);
        }
        {
            let mut cp = enc.begin_compute_pass(&Default::default());
            cp.set_pipeline(&pipeline);
            cp.set_bind_group(0, &bg, &[]);
            cp.dispatch_workgroups((w + 7) / 8, (h + 7) / 8, 1);
        }
        {
            let mut cp = enc.begin_compute_pass(&Default::default());
            cp.set_pipeline(&transparent_pipeline);
            cp.set_bind_group(0, &bg, &[]);
            cp.dispatch_workgroups((w + 7) / 8, (h + 7) / 8, 1);
        }
        enc.copy_texture_to_buffer(
            wgpu::ImageCopyTexture {
                texture: &output_tex,
                mip_level: 0,
                origin: wgpu::Origin3d::ZERO,
                aspect: wgpu::TextureAspect::All,
            },
            wgpu::ImageCopyBuffer {
                buffer: &readback,
                layout: wgpu::ImageDataLayout {
                    offset: 0,
                    bytes_per_row: Some(bpr),
                    rows_per_image: Some(h),
                },
            },
            wgpu::Extent3d { width: w, height: h, depth_or_array_layers: 1 },
        );
        queue.submit(std::iter::once(enc.finish()));

        let slice = readback.slice(..);
        slice.map_async(wgpu::MapMode::Read, |_| {});
        device.poll(wgpu::Maintain::Wait);
        let data = slice.get_mapped_range();
        Some(data.to_vec())
    }

    fn assert_sane(label: &str, min: f32, max: f32, mean: f32) {
        eprintln!("headless render [{label}] luma: min={min:.3} max={max:.3} mean={mean:.3}");
        // Bright sky pixels present (catches all-black / DDA-returns-nothing).
        assert!(max > 0.55, "[{label}] no bright sky pixels (max luma {max:.3}) — render likely broken");
        // Dark terrain pixels present (catches all-sky / DDA never hits geometry).
        assert!(min < 0.45, "[{label}] no dark terrain pixels (min luma {min:.3}) — DDA not hitting voxels");
        assert!(mean > 0.05 && mean < 0.95, "[{label}] implausible mean luma {mean:.3}");
    }

    /// Densest water / leaf 32x32-column cells of a filled world (columns
    /// sampled at stride 4), plus the ground height under the leaf cell —
    /// deterministic camera anchors shared by the water/foliage content test
    /// and the timing benchmark.
    fn find_scene_anchors(world: &World) -> (glam::IVec2, glam::IVec2, i32) {
        use crate::voxel::{is_water_mat, is_leaf_mat};
        let cells = 512 / 32;
        let mut best_water = (0usize, glam::IVec2::ZERO);
        let mut best_leaf = (0usize, glam::IVec2::ZERO);
        for cz in 0..cells {
            for cx in 0..cells {
                let (mut water_n, mut leaf_n) = (0usize, 0usize);
                for dz in (0..32).step_by(4) {
                    for dx in (0..32).step_by(4) {
                        let (x, z) = (cx * 32 + dx, cz * 32 + dz);
                        for y in (1..200).rev() {
                            let m = world.material_at_world(x, y, z);
                            if m == MAT_AIR { continue; }
                            if is_water_mat(m) { water_n += 1; }
                            break;
                        }
                        for y in 60..140 {
                            if is_leaf_mat(world.material_at_world(x, y, z)) { leaf_n += 1; }
                        }
                    }
                }
                let c = glam::IVec2::new(cx * 32 + 16, cz * 32 + 16);
                if water_n > best_water.0 { best_water = (water_n, c); }
                if leaf_n > best_leaf.0 { best_leaf = (leaf_n, c); }
            }
        }
        let leaf_ground = (1..200)
            .rev()
            .find(|&y| world.material_at_world(best_leaf.1.x, y, best_leaf.1.y) != MAT_AIR)
            .unwrap_or(80);
        eprintln!(
            "scenario anchors: water cell {:?} ({} cols), leaf cell {:?} ({} voxels, ground y={})",
            best_water.1, best_water.0, best_leaf.1, best_leaf.0, leaf_ground
        );
        (best_water.1, best_leaf.1, leaf_ground)
    }

    fn clamp_anchor(v: i32) -> f32 {
        v.max(48).min(464) as f32
    }

    /// Fraction of pixels in the bottom 60% of the frame matching a colour
    /// class. The top rows are excluded so sky can't satisfy a "blue water"
    /// check.
    fn ground_fraction(rgba: &[u8], w: usize, h: usize, class: fn(f32, f32, f32) -> bool) -> f32 {
        let y0 = h * 2 / 5;
        let mut n = 0usize;
        let mut hits = 0usize;
        for y in y0..h {
            for x in 0..w {
                let i = (y * w + x) * 4;
                let r = rgba[i] as f32 / 255.0;
                let g = rgba[i + 1] as f32 / 255.0;
                let b = rgba[i + 2] as f32 / 255.0;
                n += 1;
                if class(r, g, b) { hits += 1; }
            }
        }
        hits as f32 / n.max(1) as f32
    }

    /// The water view must contain water-blue pixels and the foliage view
    /// green foliage pixels — catches "water/foliage renders black, pink, or
    /// vanishes" regressions that the pure luma-stats tests can't see.
    #[test]
    fn renders_water_blue_and_foliage_green() {
        let mut world = World::new();
        world.fill_demo_terrain();
        let (water_c, leaf_c, leaf_ground) = find_scene_anchors(&world);

        let mut wcam = Camera::new();
        wcam.pos = glam::Vec3::new(clamp_anchor(water_c.x), 86.0, clamp_anchor(water_c.y) - 40.0);
        wcam.pitch = -0.45;
        let Some(wframe) = render_rgba(&world, &wcam, 320, 200) else {
            eprintln!("no GPU adapter — skipping water/foliage content test");
            return;
        };
        let blue = ground_fraction(&wframe, 320, 200, |r, g, b| b > r + 0.05 && b > g + 0.02);
        eprintln!("water view blue fraction: {blue:.3}");
        assert!(blue > 0.10, "water view has too few water-blue pixels ({blue:.3})");

        let mut fcam = Camera::new();
        fcam.pos = glam::Vec3::new(
            clamp_anchor(leaf_c.x),
            leaf_ground as f32 + 14.0,
            clamp_anchor(leaf_c.y) - 30.0,
        );
        fcam.pitch = -0.35;
        let fframe = render_rgba(&world, &fcam, 320, 200).unwrap();
        let green = ground_fraction(&fframe, 320, 200, |r, g, b| g > r + 0.03 && g > b + 0.03);
        eprintln!("foliage view green fraction: {green:.3}");
        assert!(green > 0.10, "foliage view has too few green pixels ({green:.3})");
    }

    /// Look-dev screenshots without a window: render a canopy close-up, a
    /// forest mid-shot and a water view to PNGs under target/lookdev/ so
    /// visual iteration can happen headlessly (view the PNGs directly).
    /// `cargo test --lib dump_lookdev_views -- --ignored --nocapture`.
    #[test]
    #[ignore]
    fn dump_lookdev_views() {
        let (w, h) = (960u32, 540u32); // bytes_per_row stays 256-aligned
        let mut world = World::new();
        world.fill_demo_terrain();
        let (water_c, leaf_c, leaf_ground) = find_scene_anchors(&world);
        std::fs::create_dir_all("target/lookdev").unwrap();

        let mut save = |name: &str, cam: &Camera| {
            let Some(rgba) = render_rgba(&world, cam, w, h) else {
                eprintln!("no GPU — skipping lookdev dump");
                return;
            };
            let path = format!("target/lookdev/{name}.png");
            let file = std::fs::File::create(&path).unwrap();
            let mut enc = png::Encoder::new(std::io::BufWriter::new(file), w, h);
            enc.set_color(png::ColorType::Rgba);
            enc.set_depth(png::BitDepth::Eight);
            enc.write_header().unwrap().write_image_data(&rgba).unwrap();
            eprintln!("wrote {path}");
        };

        let mut tree_close = Camera::new();
        tree_close.pos = glam::Vec3::new(
            clamp_anchor(leaf_c.x) + 1.0,
            leaf_ground as f32 + 5.0,
            clamp_anchor(leaf_c.y) - 11.0,
        );
        tree_close.pitch = 0.12;
        save("tree_close", &tree_close);

        let mut forest_mid = Camera::new();
        forest_mid.pos = glam::Vec3::new(
            clamp_anchor(leaf_c.x),
            leaf_ground as f32 + 16.0,
            clamp_anchor(leaf_c.y) - 32.0,
        );
        forest_mid.pitch = -0.08;
        save("forest_mid", &forest_mid);

        let mut water_view = Camera::new();
        water_view.pos = glam::Vec3::new(
            clamp_anchor(water_c.x),
            72.0,
            clamp_anchor(water_c.y) - 26.0,
        );
        water_view.pitch = -0.35;
        save("water_view", &water_view);
    }

    /// Time the raymarch + deferred-transparent dispatches at 1920x1080 for
    /// three scenarios: a high terrain overview, a water-heavy view, and a
    /// foliage-heavy view (found by scanning the demo world), so water and
    /// foliage shader changes can be A/B'd headlessly. Run with
    /// `cargo test --lib raymarch_timing -- --nocapture --ignored`.
    #[test]
    #[ignore]
    fn raymarch_timing() {
        let Some((device, queue)) = headless_device() else {
            eprintln!("no GPU — skipping");
            return;
        };
        let (w, h) = (1920u32, 1080u32);
        let mut world = World::new();
        world.fill_demo_terrain();
        let (water_anchor, leaf_anchor, leaf_ground) = find_scene_anchors(&world);

        let mk_cam = |pos: glam::Vec3, pitch: f32| {
            let mut cam = Camera::new();
            cam.pos = pos;
            cam.pitch = pitch;
            cam
        };
        let scenarios = [
            ("terrain", mk_cam(glam::Vec3::new(256.0, 150.0, 256.0), -0.5)),
            (
                "water",
                mk_cam(
                    glam::Vec3::new(clamp_anchor(water_anchor.x), 86.0, clamp_anchor(water_anchor.y) - 40.0),
                    -0.45,
                ),
            ),
            (
                "foliage",
                mk_cam(
                    glam::Vec3::new(
                        clamp_anchor(leaf_anchor.x),
                        leaf_ground as f32 + 14.0,
                        clamp_anchor(leaf_anchor.y) - 30.0,
                    ),
                    -0.35,
                ),
            ),
        ];

        // World buffers are shared across scenarios; only the camera changes.
        let cu0 = CameraUniform::from_camera(&scenarios[0].1, w, h, 0.0, glam::IVec3::ZERO, [0.0, 0.0], 0.0);
        let camera_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: None, contents: bytemuck::bytes_of(&cu0),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });
        let bricks_buf = storage(&device, "b", bytemuck::cast_slice(&world.bricks));
        let tm = storage(&device, "tm", bytemuck::cast_slice(&world.tile_mask));
        let cm = storage(&device, "cm", bytemuck::cast_slice(&world.chunk_mask));
        let l4 = storage(&device, "l4", bytemuck::cast_slice(&world.l4_mask));
        let bu = storage(&device, "bu", bytemuck::cast_slice(&pack_u8_to_u32(&world.brick_uniform)));
        let tu = storage(&device, "tu", bytemuck::cast_slice(&pack_u8_to_u32(&world.tile_uniform)));
        let palette = default_palette();
        let palette_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: None, contents: bytemuck::cast_slice(&palette),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });
        let tw = (w + 7) / 8; let th = (h + 7) / 8;
        let words = ((tw * th) as usize + 31) / 32;
        let td = storage(&device, "td", bytemuck::cast_slice(&vec![u32::MAX; words]));
        let players = storage(&device, "pl", &vec![0u8; 16 + MAX_REMOTE_PLAYERS * 16]);
        let (_o, ov) = create_output_texture(&device, w, h);
        let (_b, bv) = create_beam_texture(&device, w, h);
        let (_c, csv, _csw) = create_cloud_texture(&device, w, h);
        let csamp = device.create_sampler(&wgpu::SamplerDescriptor { mag_filter: wgpu::FilterMode::Linear, min_filter: wgpu::FilterMode::Linear, ..Default::default() });
        let (_li, liv) = create_lighting_texture(&device, w, h);
        let (_lo, lov) = create_lighting_texture(&device, w, h);
        let tpb = create_transp_buf(&device, w, h);
        let spr = storage(&device, "sprites", bytemuck::cast_slice(&crate::sprites::encoded()));
        let bgl = create_compute_bgl(&device);
        let bg = make_compute_bg(&device, &bgl, &camera_buf, &bricks_buf, &tm, &cm, &palette_buf, &ov, &bv, &td, &players, &bu, &tu, &l4, &csv, &csamp, &liv, &lov, &tpb, &spr);
        let pll = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor { label: None, bind_group_layouts: &[&bgl], push_constant_ranges: &[] });
        let src = format!("{}\n{}\n{}", WORLD_CONSTS_WGSL, COMMON_WGSL, include_str!("../shaders/raymarch.wgsl"));
        let m = device.create_shader_module(wgpu::ShaderModuleDescriptor { label: None, source: wgpu::ShaderSource::Wgsl(src.into()) });
        let pipe = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor { label: None, layout: Some(&pll), module: &m, entry_point: Some("cs_main"), compilation_options: Default::default(), cache: None });
        let pipe_transp = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor { label: None, layout: Some(&pll), module: &m, entry_point: Some("cs_transparent"), compilation_options: Default::default(), cache: None });

        for (name, cam) in &scenarios {
            let cu = CameraUniform::from_camera(cam, w, h, 0.0, glam::IVec3::ZERO, [0.0, 0.0], 0.0);
            queue.write_buffer(&camera_buf, 0, bytemuck::bytes_of(&cu));
            let encode_frame = || {
                let mut e = device.create_command_encoder(&Default::default());
                {
                    let mut cp = e.begin_compute_pass(&Default::default());
                    cp.set_pipeline(&pipe);
                    cp.set_bind_group(0, &bg, &[]);
                    cp.dispatch_workgroups(tw, th, 1);
                }
                {
                    let mut cp = e.begin_compute_pass(&Default::default());
                    cp.set_pipeline(&pipe_transp);
                    cp.set_bind_group(0, &bg, &[]);
                    cp.dispatch_workgroups(tw, th, 1);
                }
                e.finish()
            };
            // Warm up.
            for _ in 0..5 {
                queue.submit(std::iter::once(encode_frame()));
            }
            device.poll(wgpu::Maintain::Wait);
            let n = 60;
            let t0 = std::time::Instant::now();
            for _ in 0..n {
                queue.submit(std::iter::once(encode_frame()));
            }
            device.poll(wgpu::Maintain::Wait);
            let ms = t0.elapsed().as_secs_f64() * 1000.0 / n as f64;
            eprintln!("raymarch+transp [{name}] {w}x{h}: {ms:.2} ms/frame  (~{:.0} fps GPU-bound)", 1000.0 / ms);
        }
    }

    #[test]
    fn renders_terrain_and_sky() {
        let Some((min, max, mean)) = render_luma_stats_at(glam::IVec2::ZERO) else {
            eprintln!("no GPU adapter — skipping headless render test");
            return;
        };
        assert_sane("spawn", min, max, mean);
    }

    /// Stream the window thousands of voxels from spawn and render. Catches
    /// origin-rebasing / large-float-precision regressions ("sky through hills")
    /// that the spawn test (world_origin == 0) can't see. The far-origin frame
    /// should look statistically just like spawn.
    #[test]
    fn renders_far_from_origin() {
        // ~3.2M voxels from spawn: f32 ulp there is ~0.4 voxel, so WITHOUT
        // origin-rebasing the DDA's `f32(voxel) - origin` cancels into garbage
        // and the frame collapses (sky through everything / black). With
        // rebasing the float math is window-local and stays precise, so the
        // frame must still show terrain + sky. (Biome differs from spawn, so we
        // assert sanity, not a luma match.)
        let Some((min, max, mean)) = render_luma_stats_at(glam::IVec2::new(100_000, 100_000)) else {
            eprintln!("no GPU adapter — skipping far-origin render test");
            return;
        };
        assert_sane("far(100k chunks)", min, max, mean);
    }

    #[test]
    fn gpu_physics_sand_falls() {
        use crate::voxel::{brick_idx, brick_voxel_idx, Brick, MAT_SAND, WORLD_BRICKS_TOTAL};
        let Some((device, queue)) = headless_device() else {
            eprintln!("no GPU adapter — skipping GPU physics test");
            return;
        };
        let stride = std::mem::size_of::<Brick>() as u64; // 72
        let total = WORLD_BRICKS_TOTAL as u64;

        // One sand voxel at the TOP of a brick well above the floor; air below.
        let bi = brick_idx(0, 10, 0);
        let vi_top = brick_voxel_idx(0, 3, 0);
        let vi_mid = brick_voxel_idx(0, 2, 0);
        let mut brick = Brick::EMPTY;
        brick.occupancy = 1u64 << vi_top;
        brick.materials[vi_top as usize] = MAT_SAND;

        // Zero-initialised by wgpu; we only write the one seeded brick.
        let bricks_in = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("phys in"),
            size: total * stride,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let bricks_out = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("phys out"),
            size: total * stride,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
            mapped_at_creation: false,
        });
        queue.write_buffer(&bricks_in, bi as u64 * stride, bytemuck::bytes_of(&brick));

        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("phys bgl"),
            entries: &[
                super::bgl_storage(0, true),
                super::bgl_storage(1, false),
            ],
        });
        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("phys bg"), layout: &bgl,
            entries: &[
                wgpu::BindGroupEntry { binding: 0, resource: bricks_in.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bricks_out.as_entire_binding() },
            ],
        });
        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("phys pl"), bind_group_layouts: &[&bgl], push_constant_ranges: &[],
        });
        let src = format!("{}\n{}", WORLD_CONSTS_WGSL, include_str!("../shaders/physics.wgsl"));
        let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("physics"), source: wgpu::ShaderSource::Wgsl(src.into()),
        });
        let pipe = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("physics"), layout: Some(&pl), module: &module,
            entry_point: Some("cs_physics"), compilation_options: Default::default(), cache: None,
        });

        let mut enc = device.create_command_encoder(&Default::default());
        {
            let mut cp = enc.begin_compute_pass(&Default::default());
            cp.set_pipeline(&pipe);
            cp.set_bind_group(0, &bg, &[]);
            cp.dispatch_workgroups(((total as u32) + 63) / 64, 1, 1);
        }
        let readback = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("phys readback"), size: stride,
            usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
            mapped_at_creation: false,
        });
        enc.copy_buffer_to_buffer(&bricks_out, bi as u64 * stride, &readback, 0, stride);
        queue.submit(std::iter::once(enc.finish()));

        let slice = readback.slice(..);
        slice.map_async(wgpu::MapMode::Read, |_| {});
        device.poll(wgpu::Maintain::Wait);
        let data = slice.get_mapped_range();
        let out: Brick = *bytemuck::from_bytes(&data);

        // After one pull step the sand fell exactly one cell: top→air, mid→sand,
        // and mass is conserved (still exactly one sand voxel in the brick).
        assert_eq!(out.materials[vi_top as usize], 0, "top should now be air");
        assert_eq!(out.materials[vi_mid as usize], MAT_SAND, "sand should have fallen one cell");
        let sand_count = out.materials.iter().filter(|&&m| m == MAT_SAND).count();
        assert_eq!(sand_count, 1, "sand mass must be conserved");
        assert_eq!(out.occupancy, 1u64 << vi_mid, "occupancy must track the moved voxel");
        eprintln!("GPU physics: sand fell {vi_top} -> {vi_mid}, mass conserved");
    }
}
