use std::sync::Arc;

use bytemuck::{Pod, Zeroable};
use wgpu::util::DeviceExt;
use winit::window::Window;

/// WGSL world-dimension constants generated by build.rs from `src/world_dims.rs`.
/// Prepended to every shader so the GPU and CPU agree on world size with a
/// single source of truth.
const WORLD_CONSTS_WGSL: &str = include_str!(concat!(env!("OUT_DIR"), "/world_consts.wgsl"));

/// Pack a Vec<u8> into Vec<u32> for storage-buffer upload (WGSL storage
/// buffers can't directly index u8 arrays; reading byte b of word w via
/// `(packed[w] >> ((b & 3) * 8)) & 0xFF` is the canonical pattern).
fn pack_u8_to_u32(src: &[u8]) -> Vec<u32> {
    let n_words = (src.len() + 3) / 4;
    let mut out = vec![0u32; n_words];
    for (i, &b) in src.iter().enumerate() {
        let w = i >> 2;
        let bit = (i & 3) * 8;
        out[w] |= (b as u32) << bit;
    }
    out
}

/// Coalesce a SORTED, DEDUPED slice of element indices into contiguous runs and
/// invoke `f(start, end_inclusive)` once per run. Turns thousands of tiny DMAs
/// into a handful of multi-KB writes.
fn upload_spans(sorted: &[u32], mut f: impl FnMut(u32, u32)) {
    let mut i = 0usize;
    while i < sorted.len() {
        let start = sorted[i];
        let mut end = start;
        let mut j = i + 1;
        while j < sorted.len() && sorted[j] == end + 1 {
            end = sorted[j];
            j += 1;
        }
        f(start, end);
        i = j;
    }
}

/// Upload the given packed-u32 word indices (sorted, deduped) of a byte table
/// (1 byte per element, packed 4 per word) by re-packing each contiguous word
/// run from `bytes` and writing it at the matching word offset.
fn upload_packed_word_spans(
    words: &[u32],
    bytes: &[u8],
    queue: &wgpu::Queue,
    buf: &wgpu::Buffer,
) {
    upload_spans(words, |w_start, w_end| {
        let b0 = (w_start as usize) * 4;
        let b1 = (((w_end as usize) + 1) * 4).min(bytes.len());
        let packed = pack_u8_to_u32(&bytes[b0..b1]);
        queue.write_buffer(buf, w_start as u64 * 4, bytemuck::cast_slice(&packed));
    });
}

use crate::camera::{Camera, CameraUniform};
use crate::voxel::{
    Brick, World, WORLD_BRICKS_X, WORLD_BRICKS_Y, WORLD_TILES_X, WORLD_TILES_Y,
    tile_idx, chunk_idx,
    MAT_AIR, MAT_SAND, MAT_GRASS, MAT_DIRT, MAT_STONE,
    MAT_WATER_L1, MAT_WATER_L8,
    MAT_WOOD, MAT_LEAVES, MAT_SNOW, MAT_LAVA, MAT_ICE, MAT_GLASS,
    MAT_COAL, MAT_IRON, MAT_GOLD, MAT_DIAMOND,
    MAT_WOOD_BIRCH, MAT_WOOD_PINE, MAT_LEAVES_BIRCH, MAT_LEAVES_PINE, MAT_LEAVES_AUTUMN,
    MAT_SMOKE, MAT_FIRE, MAT_FLOWER, MAT_TALL_GRASS,
};

#[repr(C)]
#[derive(Copy, Clone, Pod, Zeroable)]
struct PaletteEntry([f32; 4]);

pub const MAX_REMOTE_PLAYERS: usize = 16;

#[repr(C)]
#[derive(Copy, Clone, Pod, Zeroable)]
struct PlayersBuf {
    count: u32,
    _pad: [u32; 3],
    positions: [[f32; 4]; MAX_REMOTE_PLAYERS],
}

const PALETTE_SIZE: usize = 256;

fn default_palette() -> [PaletteEntry; PALETTE_SIZE] {
    let mut p = [PaletteEntry([0.0; 4]); PALETTE_SIZE];
    p[MAT_AIR   as usize] = PaletteEntry([0.0, 0.0, 0.0, 0.0]);
    p[MAT_SAND  as usize] = PaletteEntry([0.94, 0.85, 0.55, 1.0]);
    p[MAT_GRASS as usize] = PaletteEntry([0.30, 0.65, 0.20, 1.0]);
    p[MAT_DIRT  as usize] = PaletteEntry([0.40, 0.27, 0.15, 1.0]);
    p[MAT_STONE as usize] = PaletteEntry([0.55, 0.55, 0.55, 1.0]);
    let water = [0.10, 0.45, 0.75, 1.0];
    for m in MAT_WATER_L1..=MAT_WATER_L8 {
        p[m as usize] = PaletteEntry(water);
    }
    p[MAT_WOOD as usize]   = PaletteEntry([0.42, 0.27, 0.13, 1.0]);
    p[MAT_LEAVES as usize] = PaletteEntry([0.18, 0.46, 0.16, 1.0]);
    p[MAT_SNOW as usize]   = PaletteEntry([0.95, 0.96, 0.99, 1.0]);
    p[MAT_LAVA as usize]   = PaletteEntry([1.40, 0.40, 0.10, 1.0]);
    p[MAT_ICE as usize]    = PaletteEntry([0.70, 0.85, 0.95, 1.0]);
    p[MAT_GLASS as usize]  = PaletteEntry([0.90, 0.96, 0.99, 1.0]);
    p[MAT_COAL as usize]    = PaletteEntry([0.10, 0.10, 0.12, 1.0]);
    p[MAT_IRON as usize]    = PaletteEntry([0.62, 0.55, 0.45, 1.0]);
    p[MAT_GOLD as usize]    = PaletteEntry([1.20, 0.90, 0.20, 1.0]);
    p[MAT_DIAMOND as usize] = PaletteEntry([0.55, 0.92, 0.98, 1.0]);
    p[MAT_WOOD_BIRCH as usize]    = PaletteEntry([0.85, 0.82, 0.72, 1.0]);
    p[MAT_WOOD_PINE as usize]     = PaletteEntry([0.25, 0.15, 0.08, 1.0]);
    p[MAT_LEAVES_BIRCH as usize]  = PaletteEntry([0.55, 0.78, 0.34, 1.0]);
    p[MAT_LEAVES_PINE as usize]   = PaletteEntry([0.10, 0.32, 0.12, 1.0]);
    p[MAT_LEAVES_AUTUMN as usize] = PaletteEntry([0.90, 0.42, 0.15, 1.0]);
    p[MAT_SMOKE as usize]   = PaletteEntry([0.65, 0.65, 0.70, 1.0]);
    p[MAT_FIRE as usize]    = PaletteEntry([1.60, 0.60, 0.10, 1.0]);
    p[MAT_FLOWER as usize]      = PaletteEntry([1.10, 0.35, 0.65, 1.0]);
    p[MAT_TALL_GRASS as usize]  = PaletteEntry([0.38, 0.70, 0.25, 1.0]);
    p
}

/// Render at 1/N the swapchain resolution per axis. 1 = native resolution,
/// 2 = half-res = 1/4 pixel count. The blit upscales with bilinear filtering
/// + light sharpen so values >1 still read as crisp, but the user prefers
/// the sharp native look so we run at 1:1.
pub const RENDER_SCALE: u32 = 1;

pub struct Renderer {
    pub device: wgpu::Device,
    pub queue: wgpu::Queue,
    pub surface: wgpu::Surface<'static>,
    pub config: wgpu::SurfaceConfiguration,
    /// Compute / raymarch render-target size. = `surface_size / RENDER_SCALE`.
    /// Dispatch counts, temporal-differential tile counts and the camera
    /// uniform's `resolution` all use this.
    pub size: (u32, u32),
    /// Swapchain / window size — used for surface configuration and the blit
    /// pass. Stays at the native resolution the OS gives us.
    pub surface_size: (u32, u32),

    camera_buf: wgpu::Buffer,
    bricks_buf: wgpu::Buffer,
    tile_mask_buf: wgpu::Buffer,
    chunk_mask_buf: wgpu::Buffer,
    l4_mask_buf: wgpu::Buffer,
    brick_uniform_buf: wgpu::Buffer,
    tile_uniform_buf: wgpu::Buffer,
    palette_buf: wgpu::Buffer,
    tile_dirty_buf: wgpu::Buffer,
    players_buf: wgpu::Buffer,

    output_tex: wgpu::Texture,
    output_view: wgpu::TextureView,
    beam_tex: wgpu::Texture,
    beam_view: wgpu::TextureView,
    sampler: wgpu::Sampler,

    beam_bgl: wgpu::BindGroupLayout,
    beam_pipeline: wgpu::ComputePipeline,
    beam_bg: wgpu::BindGroup,

    compute_bgl: wgpu::BindGroupLayout,
    compute_pipeline: wgpu::ComputePipeline,
    compute_bg: wgpu::BindGroup,

    blit_bgl: wgpu::BindGroupLayout,
    blit_pipeline: wgpu::RenderPipeline,
    blit_bg: wgpu::BindGroup,

    // Reused per-frame scratch for incremental mask/uniform uploads — derived
    // from the dirty-brick list so no extra dirty tracking is needed and no
    // allocation happens on the upload hot path.
    dirty_tiles_scratch: Vec<u32>,
    dirty_chunks_scratch: Vec<u32>,
    dirty_words_scratch: Vec<u32>,
}

impl Renderer {
    pub fn new(window: Arc<Window>, world: &World) -> Result<Self, String> {
        let inner = window.inner_size();
        let (surface_w, surface_h) = (inner.width.max(1), inner.height.max(1));
        let (width, height) = (
            (surface_w / RENDER_SCALE).max(1),
            (surface_h / RENDER_SCALE).max(1),
        );

        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            backends: wgpu::Backends::PRIMARY,
            ..Default::default()
        });

        let surface = instance
            .create_surface(window.clone())
            .map_err(|e| format!("create_surface failed: {e}"))?;

        let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::HighPerformance,
            compatible_surface: Some(&surface),
            force_fallback_adapter: false,
        }))
        .ok_or_else(|| "no compatible GPU adapter found".to_string())?;

        let (device, queue) = pollster::block_on(adapter.request_device(
            &wgpu::DeviceDescriptor {
                label: Some("voxel device"),
                required_features: wgpu::Features::empty(),
                required_limits: wgpu::Limits {
                    max_storage_buffer_binding_size: 256 << 20, // 256 MB headroom
                    ..wgpu::Limits::default()
                },
                memory_hints: wgpu::MemoryHints::Performance,
            },
            None,
        ))
        .map_err(|e| format!("request_device failed: {e}"))?;

        let caps = surface.get_capabilities(&adapter);
        let surface_format = caps
            .formats
            .iter()
            .copied()
            .find(|f| !f.is_srgb())
            .unwrap_or(caps.formats[0]);
        let config = wgpu::SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format: surface_format,
            width: surface_w,
            height: surface_h,
            // Explicit present policy: prefer Mailbox (low-latency, tear-free,
            // capped to the display refresh) and fall back to Fifo (vsync,
            // always supported). We deliberately avoid Immediate — it was the
            // source of the uncapped ~1800 fps idle GPU burn.
            present_mode: if caps.present_modes.contains(&wgpu::PresentMode::Mailbox) {
                wgpu::PresentMode::Mailbox
            } else {
                wgpu::PresentMode::Fifo
            },
            alpha_mode: caps.alpha_modes[0],
            view_formats: vec![],
            desired_maximum_frame_latency: 2,
        };
        surface.configure(&device, &config);

        // -- buffers --
        let camera_init = CameraUniform::from_camera(&Camera::new(), width, height, 0.0, glam::IVec3::ZERO);
        let camera_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("camera"),
            contents: bytemuck::bytes_of(&camera_init),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });

        let bricks_bytes: &[u8] = bytemuck::cast_slice(&world.bricks);
        let bricks_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("bricks"),
            contents: bricks_bytes,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });

        let tile_mask_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("tile_mask"),
            contents: bytemuck::cast_slice(&world.tile_mask),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });
        let chunk_mask_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("chunk_mask"),
            contents: bytemuck::cast_slice(&world.chunk_mask),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });
        let l4_mask_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("l4_mask"),
            contents: bytemuck::cast_slice(&world.l4_mask),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });

        // Packed uniform-material lookups (1 byte per brick / tile, packed
        // 4 per u32 word). Lets the DDA skip uniform regions in 1 lookup
        // instead of walking them.
        let brick_uniform_packed = pack_u8_to_u32(&world.brick_uniform);
        let tile_uniform_packed = pack_u8_to_u32(&world.tile_uniform);
        let brick_uniform_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("brick_uniform"),
            contents: bytemuck::cast_slice(&brick_uniform_packed),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });
        let tile_uniform_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("tile_uniform"),
            contents: bytemuck::cast_slice(&tile_uniform_packed),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });

        let palette = default_palette();
        let palette_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("palette"),
            contents: bytemuck::cast_slice(&palette),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });

        // Tile-dirty bitmask.
        let tile_dirty_words: u64 = ((3840u64 / 8 + 1) * (2160u64 / 8 + 1) + 31) / 32;
        let tile_dirty_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("tile_dirty"),
            size: tile_dirty_words * 4,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        // Remote-player marker positions (multiplayer rendering).
        let players_init = PlayersBuf {
            count: 0,
            _pad: [0; 3],
            positions: [[0.0; 4]; MAX_REMOTE_PLAYERS],
        };
        let players_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("players"),
            contents: bytemuck::bytes_of(&players_init),
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        });

        let (output_tex, output_view) = create_output_texture(&device, width, height);
        let (beam_tex, beam_view) = create_beam_texture(&device, width, height);

        // Bilinear filtering for the half-res → full-res blit upscale.
        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("blit sampler"),
            address_mode_u: wgpu::AddressMode::ClampToEdge,
            address_mode_v: wgpu::AddressMode::ClampToEdge,
            address_mode_w: wgpu::AddressMode::ClampToEdge,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::FilterMode::Nearest,
            ..Default::default()
        });

        // -- compute pipeline --
        let compute_bgl = create_compute_bgl(&device);

        let compute_pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("compute pl"),
            bind_group_layouts: &[&compute_bgl],
            push_constant_ranges: &[],
        });
        let raymarch_src = format!(
            "{}\n{}",
            WORLD_CONSTS_WGSL,
            include_str!("../shaders/raymarch.wgsl")
        );
        let compute_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("raymarch shader"),
            source: wgpu::ShaderSource::Wgsl(raymarch_src.into()),
        });
        let compute_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("raymarch pipeline"),
            layout: Some(&compute_pl),
            module: &compute_shader,
            entry_point: Some("cs_main"),
            compilation_options: Default::default(),
            cache: None,
        });

        let compute_bg = make_compute_bg(
            &device, &compute_bgl, &camera_buf, &bricks_buf,
            &tile_mask_buf, &chunk_mask_buf, &palette_buf, &output_view, &beam_view,
            &tile_dirty_buf, &players_buf, &brick_uniform_buf, &tile_uniform_buf, &l4_mask_buf,
        );

        // -- beam pipeline (1/8-res coarse pre-pass) --
        let beam_bgl = create_beam_bgl(&device);
        let beam_pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("beam pl"),
            bind_group_layouts: &[&beam_bgl],
            push_constant_ranges: &[],
        });
        let beam_src = format!(
            "{}\n{}",
            WORLD_CONSTS_WGSL,
            include_str!("../shaders/beam.wgsl")
        );
        let beam_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("beam shader"),
            source: wgpu::ShaderSource::Wgsl(beam_src.into()),
        });
        let beam_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("beam pipeline"),
            layout: Some(&beam_pl),
            module: &beam_shader,
            entry_point: Some("cs_beam"),
            compilation_options: Default::default(),
            cache: None,
        });
        let beam_bg = make_beam_bg(&device, &beam_bgl, &camera_buf, &chunk_mask_buf, &beam_view);

        // -- blit pipeline --
        let blit_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("blit bgl"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
            ],
        });
        let blit_pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("blit pl"),
            bind_group_layouts: &[&blit_bgl],
            push_constant_ranges: &[],
        });
        let blit_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("blit shader"),
            source: wgpu::ShaderSource::Wgsl(include_str!("../shaders/blit.wgsl").into()),
        });
        let blit_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("blit pipeline"),
            layout: Some(&blit_pl),
            vertex: wgpu::VertexState {
                module: &blit_shader,
                entry_point: Some("vs_main"),
                buffers: &[],
                compilation_options: Default::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &blit_shader,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: surface_format,
                    blend: None,
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: Default::default(),
            }),
            primitive: wgpu::PrimitiveState::default(),
            depth_stencil: None,
            multisample: wgpu::MultisampleState::default(),
            multiview: None,
            cache: None,
        });

        let blit_bg = make_blit_bg(&device, &blit_bgl, &output_view, &sampler);

        Ok(Self {
            device, queue, surface, config,
            size: (width, height),
            surface_size: (surface_w, surface_h),
            camera_buf, bricks_buf, tile_mask_buf, chunk_mask_buf, l4_mask_buf, palette_buf,
            brick_uniform_buf, tile_uniform_buf,
            tile_dirty_buf, players_buf,
            output_tex, output_view, beam_tex, beam_view, sampler,
            beam_bgl, beam_pipeline, beam_bg,
            compute_bgl, compute_pipeline, compute_bg,
            blit_bgl, blit_pipeline, blit_bg,
            dirty_tiles_scratch: Vec::with_capacity(4096),
            dirty_chunks_scratch: Vec::with_capacity(512),
            dirty_words_scratch: Vec::with_capacity(4096),
        })
    }

    pub fn resize(&mut self, w: u32, h: u32) {
        if w == 0 || h == 0 || (w, h) == self.surface_size { return; }
        self.surface_size = (w, h);
        let rw = (w / RENDER_SCALE).max(1);
        let rh = (h / RENDER_SCALE).max(1);
        self.size = (rw, rh);
        self.config.width = w;
        self.config.height = h;
        self.surface.configure(&self.device, &self.config);

        let (tex, view) = create_output_texture(&self.device, rw, rh);
        self.output_tex = tex;
        self.output_view = view;
        let (btex, bview) = create_beam_texture(&self.device, rw, rh);
        self.beam_tex = btex;
        self.beam_view = bview;

        self.compute_bg = make_compute_bg(
            &self.device, &self.compute_bgl, &self.camera_buf, &self.bricks_buf,
            &self.tile_mask_buf, &self.chunk_mask_buf, &self.palette_buf, &self.output_view, &self.beam_view,
            &self.tile_dirty_buf, &self.players_buf, &self.brick_uniform_buf, &self.tile_uniform_buf,
            &self.l4_mask_buf,
        );
        self.beam_bg = make_beam_bg(
            &self.device, &self.beam_bgl, &self.camera_buf, &self.chunk_mask_buf, &self.beam_view,
        );
        self.blit_bg = make_blit_bg(&self.device, &self.blit_bgl, &self.output_view, &self.sampler);
    }

    pub fn upload_world(&mut self, world: &mut World) {
        // Whole-world refresh (first frame / explicit invalidate only). A chunk
        // cross must NEVER reach this path — it goes through the incremental
        // path below, which is why crossing a boundary no longer re-DMAs ~75 MB.
        if world.all_dirty {
            self.queue.write_buffer(&self.bricks_buf, 0, bytemuck::cast_slice(&world.bricks));
            self.queue.write_buffer(&self.tile_mask_buf, 0, bytemuck::cast_slice(&world.tile_mask));
            self.queue.write_buffer(&self.chunk_mask_buf, 0, bytemuck::cast_slice(&world.chunk_mask));
            self.queue.write_buffer(&self.l4_mask_buf, 0, bytemuck::cast_slice(&world.l4_mask));
            let bu = pack_u8_to_u32(&world.brick_uniform);
            let tu = pack_u8_to_u32(&world.tile_uniform);
            self.queue.write_buffer(&self.brick_uniform_buf, 0, bytemuck::cast_slice(&bu));
            self.queue.write_buffer(&self.tile_uniform_buf, 0, bytemuck::cast_slice(&tu));
            world.all_dirty = false;
            world.dirty_bricks.clear();
            return;
        }
        if world.dirty_bricks.is_empty() { return; }
        world.dirty_bricks.sort_unstable();
        world.dirty_bricks.dedup();

        // 1. Brick voxel data — coalesced contiguous spans (one DMA per run).
        let stride = std::mem::size_of::<Brick>() as u64;
        upload_spans(&world.dirty_bricks, |s, e| {
            let slice = &world.bricks[s as usize..=e as usize];
            self.queue.write_buffer(&self.bricks_buf, s as u64 * stride, bytemuck::cast_slice(slice));
        });

        // 2. Per-brick uniform-material table (packed 4 bricks / u32 word).
        //    Re-pack and upload only the words touched by dirty bricks — this
        //    is the table the DDA's uniform-skip reads, and it was previously
        //    NEVER refreshed incrementally, so streamed chunks rendered with
        //    stale skip data.
        self.dirty_words_scratch.clear();
        for &b in &world.dirty_bricks {
            let w = b >> 2;
            if self.dirty_words_scratch.last() != Some(&w) {
                self.dirty_words_scratch.push(w);
            }
        }
        upload_packed_word_spans(
            &self.dirty_words_scratch, &world.brick_uniform, &self.queue, &self.brick_uniform_buf,
        );

        // 3. Tiles touched by the dirty bricks → tile_mask (u64) + tile_uniform.
        self.dirty_tiles_scratch.clear();
        for &b in &world.dirty_bricks {
            let bx = b % WORLD_BRICKS_X;
            let by = (b / WORLD_BRICKS_X) % WORLD_BRICKS_Y;
            let bz = b / (WORLD_BRICKS_X * WORLD_BRICKS_Y);
            self.dirty_tiles_scratch.push(tile_idx(bx / 4, by / 4, bz / 4));
        }
        self.dirty_tiles_scratch.sort_unstable();
        self.dirty_tiles_scratch.dedup();
        upload_spans(&self.dirty_tiles_scratch, |s, e| {
            let slice = &world.tile_mask[s as usize..=e as usize];
            self.queue.write_buffer(&self.tile_mask_buf, s as u64 * 8, bytemuck::cast_slice(slice));
        });
        self.dirty_words_scratch.clear();
        for &t in &self.dirty_tiles_scratch {
            let w = t >> 2;
            if self.dirty_words_scratch.last() != Some(&w) {
                self.dirty_words_scratch.push(w);
            }
        }
        upload_packed_word_spans(
            &self.dirty_words_scratch, &world.tile_uniform, &self.queue, &self.tile_uniform_buf,
        );

        // 4. Chunks touched by those tiles → chunk_mask (u64).
        self.dirty_chunks_scratch.clear();
        for &t in &self.dirty_tiles_scratch {
            let tx = t % WORLD_TILES_X;
            let ty = (t / WORLD_TILES_X) % WORLD_TILES_Y;
            let tz = t / (WORLD_TILES_X * WORLD_TILES_Y);
            self.dirty_chunks_scratch.push(chunk_idx(tx / 4, ty / 4, tz / 4));
        }
        self.dirty_chunks_scratch.sort_unstable();
        self.dirty_chunks_scratch.dedup();
        upload_spans(&self.dirty_chunks_scratch, |s, e| {
            let slice = &world.chunk_mask[s as usize..=e as usize];
            self.queue.write_buffer(&self.chunk_mask_buf, s as u64 * 8, bytemuck::cast_slice(slice));
        });
        // L4 mask is only a handful of u64s — if any chunk changed, just push
        // the whole thing.
        if !self.dirty_chunks_scratch.is_empty() {
            self.queue.write_buffer(&self.l4_mask_buf, 0, bytemuck::cast_slice(&world.l4_mask));
        }

        world.dirty_bricks.clear();
    }

    pub fn upload_tile_dirty(&self, mask: &[u32]) {
        if mask.is_empty() { return; }
        self.queue.write_buffer(&self.tile_dirty_buf, 0, bytemuck::cast_slice(mask));
    }

    pub fn upload_players(&self, positions: &[(glam::Vec3, u32)]) {
        let mut data = PlayersBuf {
            count: 0,
            _pad: [0; 3],
            positions: [[0.0; 4]; MAX_REMOTE_PLAYERS],
        };
        let n = positions.len().min(MAX_REMOTE_PLAYERS);
        data.count = n as u32;
        for (i, (p, id)) in positions.iter().take(n).enumerate() {
            data.positions[i] = [p.x, p.y, p.z, *id as f32];
        }
        self.queue.write_buffer(&self.players_buf, 0, bytemuck::bytes_of(&data));
    }

    pub fn update_camera(&self, camera: &Camera, time: f32, world_origin_voxel: glam::IVec3) {
        let u = CameraUniform::from_camera(camera, self.size.0, self.size.1, time, world_origin_voxel);
        self.queue.write_buffer(&self.camera_buf, 0, bytemuck::bytes_of(&u));
    }

    pub fn render(&mut self, any_dirty: bool) -> Result<(), wgpu::SurfaceError> {
        let frame = self.surface.get_current_texture()?;
        let frame_view = frame
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        let mut encoder = self.device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
            label: Some("frame"),
        });

        // Temporal-differential: if no tile is dirty, we still blit (so the
        // swapchain stays in sync), but skip the beam + raymarch compute
        // passes entirely. The output_tex from the prior frame is preserved.
        if any_dirty {
            // ---- beam pre-pass at 1/8 resolution ----
            {
                let mut cp = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                    label: Some("beam"),
                    timestamp_writes: None,
                });
                cp.set_pipeline(&self.beam_pipeline);
                cp.set_bind_group(0, &self.beam_bg, &[]);
                let bx = ((self.size.0 + 7) / 8 + 7) / 8;
                let by = ((self.size.1 + 7) / 8 + 7) / 8;
                cp.dispatch_workgroups(bx, by, 1);
            }
            // ---- main raymarch (skips clean tiles in-shader) ----
            {
                let mut cp = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                    label: Some("raymarch"),
                    timestamp_writes: None,
                });
                cp.set_pipeline(&self.compute_pipeline);
                cp.set_bind_group(0, &self.compute_bg, &[]);
                let gx = (self.size.0 + 7) / 8;
                let gy = (self.size.1 + 7) / 8;
                cp.dispatch_workgroups(gx, gy, 1);
            }
        }

        {
            let mut rp = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("blit"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &frame_view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: 0.0, g: 0.0, b: 0.0, a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
                occlusion_query_set: None,
            });
            rp.set_pipeline(&self.blit_pipeline);
            rp.set_bind_group(0, &self.blit_bg, &[]);
            rp.draw(0..3, 0..1);
        }

        self.queue.submit(std::iter::once(encoder.finish()));
        frame.present();
        Ok(())
    }
}

fn create_output_texture(device: &wgpu::Device, w: u32, h: u32) -> (wgpu::Texture, wgpu::TextureView) {
    let tex = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("output"),
        size: wgpu::Extent3d { width: w, height: h, depth_or_array_layers: 1 },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8Unorm,
        // COPY_SRC lets the headless render test read the frame back for
        // automated validation; harmless for the windowed path.
        usage: wgpu::TextureUsages::STORAGE_BINDING
            | wgpu::TextureUsages::TEXTURE_BINDING
            | wgpu::TextureUsages::COPY_SRC,
        view_formats: &[],
    });
    let view = tex.create_view(&wgpu::TextureViewDescriptor::default());
    (tex, view)
}

fn create_beam_texture(device: &wgpu::Device, w: u32, h: u32) -> (wgpu::Texture, wgpu::TextureView) {
    let bw = ((w + 7) / 8).max(1);
    let bh = ((h + 7) / 8).max(1);
    let tex = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("beam"),
        size: wgpu::Extent3d { width: bw, height: bh, depth_or_array_layers: 1 },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::R32Float,
        usage: wgpu::TextureUsages::STORAGE_BINDING | wgpu::TextureUsages::TEXTURE_BINDING,
        view_formats: &[],
    });
    let view = tex.create_view(&wgpu::TextureViewDescriptor::default());
    (tex, view)
}

/// Compute-pass bind-group layout. Single definition shared by the renderer and
/// the headless render test so the two can never drift. Binding order matches
/// `make_compute_bg` and the `@group(0) @binding(N)` declarations in
/// shaders/raymarch.wgsl.
fn create_compute_bgl(device: &wgpu::Device) -> wgpu::BindGroupLayout {
    let storage_ro = |binding: u32| wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::Buffer {
            ty: wgpu::BufferBindingType::Storage { read_only: true },
            has_dynamic_offset: false,
            min_binding_size: None,
        },
        count: None,
    };
    let uniform = |binding: u32| wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::Buffer {
            ty: wgpu::BufferBindingType::Uniform,
            has_dynamic_offset: false,
            min_binding_size: None,
        },
        count: None,
    };
    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some("compute bgl"),
        entries: &[
            uniform(0),    // camera
            storage_ro(1), // bricks
            storage_ro(2), // tile_mask
            storage_ro(3), // chunk_mask
            uniform(4),    // palette
            wgpu::BindGroupLayoutEntry {
                binding: 5, // output storage texture
                visibility: wgpu::ShaderStages::COMPUTE,
                ty: wgpu::BindingType::StorageTexture {
                    access: wgpu::StorageTextureAccess::WriteOnly,
                    format: wgpu::TextureFormat::Rgba8Unorm,
                    view_dimension: wgpu::TextureViewDimension::D2,
                },
                count: None,
            },
            wgpu::BindGroupLayoutEntry {
                binding: 6, // beam depth texture
                visibility: wgpu::ShaderStages::COMPUTE,
                ty: wgpu::BindingType::Texture {
                    sample_type: wgpu::TextureSampleType::Float { filterable: false },
                    view_dimension: wgpu::TextureViewDimension::D2,
                    multisampled: false,
                },
                count: None,
            },
            storage_ro(7),  // tile_dirty
            storage_ro(8),  // players
            storage_ro(9),  // brick_uniform
            storage_ro(10), // tile_uniform
            storage_ro(11), // l4_mask (coarsest pyramid level)
        ],
    })
}

fn create_beam_bgl(device: &wgpu::Device) -> wgpu::BindGroupLayout {
    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some("beam bgl"),
        entries: &[
            wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::COMPUTE,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Uniform,
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            },
            wgpu::BindGroupLayoutEntry {
                binding: 1,
                visibility: wgpu::ShaderStages::COMPUTE,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Storage { read_only: true },
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            },
            wgpu::BindGroupLayoutEntry {
                binding: 2,
                visibility: wgpu::ShaderStages::COMPUTE,
                ty: wgpu::BindingType::StorageTexture {
                    access: wgpu::StorageTextureAccess::WriteOnly,
                    format: wgpu::TextureFormat::R32Float,
                    view_dimension: wgpu::TextureViewDimension::D2,
                },
                count: None,
            },
        ],
    })
}

fn make_compute_bg(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    camera_buf: &wgpu::Buffer,
    bricks_buf: &wgpu::Buffer,
    tile_mask_buf: &wgpu::Buffer,
    chunk_mask_buf: &wgpu::Buffer,
    palette_buf: &wgpu::Buffer,
    output_view: &wgpu::TextureView,
    beam_view: &wgpu::TextureView,
    tile_dirty_buf: &wgpu::Buffer,
    players_buf: &wgpu::Buffer,
    brick_uniform_buf: &wgpu::Buffer,
    tile_uniform_buf: &wgpu::Buffer,
    l4_mask_buf: &wgpu::Buffer,
) -> wgpu::BindGroup {
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("compute bg"),
        layout,
        entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: camera_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 1, resource: bricks_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 2, resource: tile_mask_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 3, resource: chunk_mask_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 4, resource: palette_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 5, resource: wgpu::BindingResource::TextureView(output_view) },
            wgpu::BindGroupEntry { binding: 6, resource: wgpu::BindingResource::TextureView(beam_view) },
            wgpu::BindGroupEntry { binding: 7, resource: tile_dirty_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 8, resource: players_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 9, resource: brick_uniform_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 10, resource: tile_uniform_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 11, resource: l4_mask_buf.as_entire_binding() },
        ],
    })
}

fn make_beam_bg(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    camera_buf: &wgpu::Buffer,
    chunk_mask_buf: &wgpu::Buffer,
    beam_view: &wgpu::TextureView,
) -> wgpu::BindGroup {
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("beam bg"),
        layout,
        entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: camera_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 1, resource: chunk_mask_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 2, resource: wgpu::BindingResource::TextureView(beam_view) },
        ],
    })
}

fn make_blit_bg(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    view: &wgpu::TextureView,
    sampler: &wgpu::Sampler,
) -> wgpu::BindGroup {
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("blit bg"),
        layout,
        entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: wgpu::BindingResource::TextureView(view) },
            wgpu::BindGroupEntry { binding: 1, resource: wgpu::BindingResource::Sampler(sampler) },
        ],
    })
}

#[cfg(test)]
mod shader_tests {
    //! Headless WGSL parse + validation. Catches shader regressions in
    //! `cargo test` without a window or a GPU — the shaders are otherwise only
    //! validated at runtime when the pipelines are created. The const-prepending
    //! mirrors exactly what `Renderer::new` does, so the validated source is the
    //! source that actually runs.
    use super::WORLD_CONSTS_WGSL;

    fn validate(name: &str, src: &str) {
        let module = naga::front::wgsl::parse_str(src)
            .unwrap_or_else(|e| panic!("WGSL parse error in {name}:\n{}", e.emit_to_string(src)));
        let mut v = naga::valid::Validator::new(
            naga::valid::ValidationFlags::all(),
            naga::valid::Capabilities::all(),
        );
        v.validate(&module)
            .unwrap_or_else(|e| panic!("WGSL validation error in {name}: {e:?}"));
    }

    #[test]
    fn raymarch_wgsl_valid() {
        let src = format!("{}\n{}", WORLD_CONSTS_WGSL, include_str!("../shaders/raymarch.wgsl"));
        validate("raymarch.wgsl", &src);
    }

    #[test]
    fn beam_wgsl_valid() {
        let src = format!("{}\n{}", WORLD_CONSTS_WGSL, include_str!("../shaders/beam.wgsl"));
        validate("beam.wgsl", &src);
    }

    #[test]
    fn blit_wgsl_valid() {
        validate("blit.wgsl", include_str!("../shaders/blit.wgsl"));
    }
}

#[cfg(test)]
mod gpu_render_tests {
    //! Headless offscreen render + pixel readback. Runs the REAL raymarch
    //! pipeline (reusing the renderer's own bind-group / buffer helpers) on a
    //! windowless device, then reads the frame back and asserts the scene has
    //! both sky and terrain. This is the automated regression net for shader
    //! changes (the DDA rewrite, LOD, etc.) where there's no display to look at.
    //! Skips cleanly when no GPU adapter is available (e.g. headless CI).
    use super::*;
    use crate::camera::{Camera, CameraUniform};
    use crate::voxel::World;
    use wgpu::util::DeviceExt;

    fn headless_device() -> Option<(wgpu::Device, wgpu::Queue)> {
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            backends: wgpu::Backends::PRIMARY,
            ..Default::default()
        });
        let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::HighPerformance,
            compatible_surface: None,
            force_fallback_adapter: false,
        }))?;
        let (device, queue) = pollster::block_on(adapter.request_device(
            &wgpu::DeviceDescriptor {
                label: Some("headless test device"),
                required_features: wgpu::Features::empty(),
                required_limits: wgpu::Limits {
                    max_storage_buffer_binding_size: 256 << 20,
                    ..wgpu::Limits::default()
                },
                memory_hints: wgpu::MemoryHints::Performance,
            },
            None,
        ))
        .ok()?;
        Some((device, queue))
    }

    fn storage(device: &wgpu::Device, label: &str, bytes: &[u8]) -> wgpu::Buffer {
        device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some(label),
            contents: bytes,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        })
    }

    /// Render the default world from a camera placed high above spawn and read
    /// the frame back. Returns per-pixel luma (min, max, mean) or None if no GPU.
    pub(super) fn render_luma_stats() -> Option<(f32, f32, f32)> {
        let (device, queue) = headless_device()?;
        let (w, h) = (320u32, 200u32);

        let mut world = World::new();
        world.fill_demo_terrain();

        // Camera high above the spawn column, tilted toward the horizon so the
        // frame contains terrain (lower) and sky (upper) — never inside a voxel.
        let mut cam = Camera::new();
        let s = crate::voxel::sample_terrain(cam.pos.x, cam.pos.z, world.seed);
        cam.pos.y = s.h as f32 + 30.0;
        cam.pitch = -0.35;
        let cu = CameraUniform::from_camera(&cam, w, h, 0.0, glam::IVec3::ZERO);

        let camera_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("camera"),
            contents: bytemuck::bytes_of(&cu),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });
        let bricks_buf = storage(&device, "bricks", bytemuck::cast_slice(&world.bricks));
        let tile_mask_buf = storage(&device, "tile_mask", bytemuck::cast_slice(&world.tile_mask));
        let chunk_mask_buf = storage(&device, "chunk_mask", bytemuck::cast_slice(&world.chunk_mask));
        let l4_mask_buf = storage(&device, "l4_mask", bytemuck::cast_slice(&world.l4_mask));
        let brick_uniform_buf = storage(&device, "brick_uniform", bytemuck::cast_slice(&pack_u8_to_u32(&world.brick_uniform)));
        let tile_uniform_buf = storage(&device, "tile_uniform", bytemuck::cast_slice(&pack_u8_to_u32(&world.tile_uniform)));
        let palette = default_palette();
        let palette_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("palette"),
            contents: bytemuck::cast_slice(&palette),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });
        // All tiles dirty → render every pixel.
        let tiles_w = (w + 7) / 8;
        let tiles_h = (h + 7) / 8;
        let words = ((tiles_w * tiles_h) as usize + 31) / 32;
        let tile_dirty_buf = storage(&device, "tile_dirty", bytemuck::cast_slice(&vec![u32::MAX; words]));
        let players_buf = storage(&device, "players", &vec![0u8; 16 + MAX_REMOTE_PLAYERS * 16]);

        let (_otex, output_view) = create_output_texture(&device, w, h);
        let output_tex = _otex;
        let (_btex, beam_view) = create_beam_texture(&device, w, h);

        let bgl = create_compute_bgl(&device);
        let bg = make_compute_bg(
            &device, &bgl, &camera_buf, &bricks_buf, &tile_mask_buf, &chunk_mask_buf,
            &palette_buf, &output_view, &beam_view, &tile_dirty_buf, &players_buf,
            &brick_uniform_buf, &tile_uniform_buf, &l4_mask_buf,
        );
        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("test pl"),
            bind_group_layouts: &[&bgl],
            push_constant_ranges: &[],
        });
        let src = format!("{}\n{}", WORLD_CONSTS_WGSL, include_str!("../shaders/raymarch.wgsl"));
        let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("test raymarch"),
            source: wgpu::ShaderSource::Wgsl(src.into()),
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("test raymarch pipeline"),
            layout: Some(&pl),
            module: &module,
            entry_point: Some("cs_main"),
            compilation_options: Default::default(),
            cache: None,
        });

        // Readback buffer (bytes_per_row already 256-aligned for w=320).
        let bpr = w * 4;
        let readback = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("readback"),
            size: (bpr * h) as u64,
            usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
            mapped_at_creation: false,
        });

        let mut enc = device.create_command_encoder(&Default::default());
        {
            let mut cp = enc.begin_compute_pass(&Default::default());
            cp.set_pipeline(&pipeline);
            cp.set_bind_group(0, &bg, &[]);
            cp.dispatch_workgroups((w + 7) / 8, (h + 7) / 8, 1);
        }
        enc.copy_texture_to_buffer(
            wgpu::ImageCopyTexture {
                texture: &output_tex,
                mip_level: 0,
                origin: wgpu::Origin3d::ZERO,
                aspect: wgpu::TextureAspect::All,
            },
            wgpu::ImageCopyBuffer {
                buffer: &readback,
                layout: wgpu::ImageDataLayout {
                    offset: 0,
                    bytes_per_row: Some(bpr),
                    rows_per_image: Some(h),
                },
            },
            wgpu::Extent3d { width: w, height: h, depth_or_array_layers: 1 },
        );
        queue.submit(std::iter::once(enc.finish()));

        let slice = readback.slice(..);
        slice.map_async(wgpu::MapMode::Read, |_| {});
        device.poll(wgpu::Maintain::Wait);
        let data = slice.get_mapped_range();

        let mut min = 1.0f32;
        let mut max = 0.0f32;
        let mut sum = 0.0f64;
        let n = (w * h) as usize;
        for px in data.chunks_exact(4) {
            let r = px[0] as f32 / 255.0;
            let g = px[1] as f32 / 255.0;
            let b = px[2] as f32 / 255.0;
            let luma = 0.299 * r + 0.587 * g + 0.114 * b;
            min = min.min(luma);
            max = max.max(luma);
            sum += luma as f64;
        }
        Some((min, max, (sum / n as f64) as f32))
    }

    #[test]
    fn renders_terrain_and_sky() {
        let Some((min, max, mean)) = render_luma_stats() else {
            eprintln!("no GPU adapter — skipping headless render test");
            return;
        };
        eprintln!("headless render luma: min={min:.3} max={max:.3} mean={mean:.3}");
        // Bright sky pixels present (catches all-black / DDA-returns-nothing).
        assert!(max > 0.55, "no bright sky pixels (max luma {max:.3}) — render likely broken");
        // Dark terrain pixels present (catches all-sky / DDA never hits geometry).
        assert!(min < 0.45, "no dark terrain pixels (min luma {min:.3}) — DDA likely not hitting voxels");
        // Sane overall exposure.
        assert!(mean > 0.05 && mean < 0.95, "implausible mean luma {mean:.3}");
    }
}
